"""Convert a Wavefront OBJ (+MTL) instrument model into MuJoCo-ready meshes.

Splits the model into one mesh per material (MuJoCo meshes carry a single
colour), rotates Y-up exports to MuJoCo's Z-up, scales to metres, centres it in
XY and rests it on z=0. Writes <out>/<name>/*.obj plus an MJCF snippet
<out>/<name>.xml that can be <attach>-ed into a scene as body "<name>".

    python tools/convert_instrument.py model.obj --name gc_ms --scale 0.0254 --out models/instruments
"""
import argparse
from collections import defaultdict
from pathlib import Path

import numpy as np
import trimesh

# Y-up -> Z-up: (x, y, z) -> (x, -z, y)
Y_UP_TO_Z_UP = np.array([[1, 0, 0, 0], [0, 0, -1, 0], [0, 1, 0, 0], [0, 0, 0, 1]], dtype=float)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("obj", type=Path)
    p.add_argument("--name", required=True)
    p.add_argument("--scale", type=float, required=True, help="model units -> metres")
    p.add_argument("--out", type=Path, default=Path("models/instruments"))
    p.add_argument("--z-up", action="store_true", help="source is already Z-up")
    p.add_argument("--min-faces", type=int, default=0, help="drop materials with fewer faces")
    args = p.parse_args()

    scene = trimesh.load(args.obj, force="scene")
    parts: dict[str, list[trimesh.Trimesh]] = defaultdict(list)
    colours: dict[str, np.ndarray] = {}
    for node in scene.graph.nodes_geometry:
        transform, geom_name = scene.graph[node]
        mesh = scene.geometry[geom_name].copy()
        mesh.apply_transform(transform)
        mat = getattr(mesh.visual, "material", None)
        key = getattr(mat, "name", None) or "default"
        colour = getattr(mat, "main_color", None)
        colours[key] = np.asarray(colour if colour is not None else [180, 180, 180, 255]) / 255.0
        parts[key].append(mesh)

    merged = {k: trimesh.util.concatenate(v) for k, v in parts.items()}
    merged = {k: m for k, m in merged.items() if len(m.faces) >= args.min_faces}

    whole = trimesh.util.concatenate(list(merged.values()))
    transform = np.eye(4) if args.z_up else Y_UP_TO_Z_UP.copy()
    transform[:3, :3] *= args.scale
    whole.apply_transform(transform)
    lo, hi = whole.bounds
    offset = np.array([-(lo[0] + hi[0]) / 2, -(lo[1] + hi[1]) / 2, -lo[2]])
    size = hi - lo

    mesh_dir = args.out / args.name
    mesh_dir.mkdir(parents=True, exist_ok=True)
    assets, geoms = [], []
    for i, (key, mesh) in enumerate(sorted(merged.items())):
        mesh.apply_transform(transform)
        mesh.apply_translation(offset)
        mesh.visual = trimesh.visual.ColorVisuals(mesh)  # drop MTL refs; colour lives in MJCF
        fname = f"part_{i:02d}.obj"
        mesh.export(mesh_dir / fname)
        r, g, b, a = colours[key]
        assets.append(f'    <mesh name="{args.name}_{i:02d}" file="{args.name}/{fname}" inertia="shell"/>')
        geoms.append(
            f'      <geom type="mesh" mesh="{args.name}_{i:02d}" rgba="{r:.3f} {g:.3f} {b:.3f} {a:.3f}"'
            f' contype="0" conaffinity="0" group="1"/>  <!-- {key} -->'
        )

    # Visual meshes don't collide; a single box stands in for the instrument's body.
    hx, hy, hz = size / 2
    xml = f"""<!-- Generated by tools/convert_instrument.py from {args.obj.name}; size {size[0]:.3f} x {size[1]:.3f} x {size[2]:.3f} m -->
<mujoco model="{args.name}">
  <compiler meshdir="."/>
  <asset>
{chr(10).join(assets)}
  </asset>
  <worldbody>
    <body name="{args.name}">
{chr(10).join(geoms)}
      <geom name="{args.name}_collision" type="box" size="{hx:.4f} {hy:.4f} {hz:.4f}" pos="0 0 {hz:.4f}" group="3" rgba=".5 .5 .5 .3"/>
    </body>
  </worldbody>
</mujoco>
"""
    (args.out / f"{args.name}.xml").write_text(xml)
    print(f"{args.name}: {len(merged)} meshes, size {size.round(3)} m -> {args.out / (args.name + '.xml')}")


if __name__ == "__main__":
    main()
