#!/usr/bin/env python3
"""Assemble a COCO-format detection manifest from the BasicWriter output and
package a clean dataset directory. Run on the pod with Isaac's python (numpy).

    /isaac-sim/python.sh build_coco.py /root/dataset /root/lab_dataset_v1

Produces <out>/images/<cam>/rgb_NNNN.png, <out>/masks/<cam>/semantic_NNNN.png,
<out>/annotations/instances.json (COCO), and README.md.
"""
import os, sys, glob, json, shutil, collections
import numpy as np

SRC = sys.argv[1] if len(sys.argv) > 1 else "/root/dataset"
OUT = sys.argv[2] if len(sys.argv) > 2 else "/root/lab_dataset_v1"
CAMS = sorted(os.path.basename(d) for d in glob.glob(os.path.join(SRC, "*")) if os.path.isdir(d))

os.makedirs(os.path.join(OUT, "annotations"), exist_ok=True)

# categories: union of barcode classes across all label jsons
cats = set()
for cam in CAMS:
    for lf in glob.glob(os.path.join(SRC, cam, "bounding_box_2d_tight_labels_*.json")):
        for v in json.load(open(lf)).values():
            c = v.get("class", "")
            if c and c.lower() not in ("background", "unlabelled", "unlabeled"):
                cats.add(c.upper())
cat_list = sorted(cats)
cat_id = {c: i + 1 for i, c in enumerate(cat_list)}
categories = [{"id": i + 1, "name": c, "supercategory": "bottle"} for i, c in enumerate(cat_list)]

images, annotations = [], []
img_id, ann_id = 0, 0
for cam in CAMS:
    npys = sorted(glob.glob(os.path.join(SRC, cam, "bounding_box_2d_tight_*.npy")))
    for npy in npys:
        idx = npy.rsplit("_", 1)[-1].split(".")[0]
        rgb = os.path.join(SRC, cam, f"rgb_{idx}.png")
        if not os.path.exists(rgb):
            continue
        img_id += 1
        rel = f"images/{cam}/rgb_{idx}.png"
        os.makedirs(os.path.join(OUT, "images", cam), exist_ok=True)
        shutil.copy(rgb, os.path.join(OUT, rel))
        seg = os.path.join(SRC, cam, f"semantic_segmentation_{idx}.png")
        if os.path.exists(seg):
            os.makedirs(os.path.join(OUT, "masks", cam), exist_ok=True)
            shutil.copy(seg, os.path.join(OUT, "masks", cam, f"semantic_{idx}.png"))
        images.append({"id": img_id, "file_name": rel, "width": 1600, "height": 900,
                       "camera": cam})
        bb = np.load(npy)
        labels = json.load(open(os.path.join(SRC, cam,
                            f"bounding_box_2d_tight_labels_{idx}.json")))
        for row in bb:
            x0, y0, x1, y1 = (float(row["x_min"]), float(row["y_min"]),
                              float(row["x_max"]), float(row["y_max"]))
            w, h = x1 - x0, y1 - y0
            if w <= 1 or h <= 1:
                continue
            cls = labels.get(str(int(row["semanticId"])), {}).get("class", "").upper()
            if cls not in cat_id:
                continue
            ann_id += 1
            annotations.append({
                "id": ann_id, "image_id": img_id, "category_id": cat_id[cls],
                "bbox": [round(x0, 1), round(y0, 1), round(w, 1), round(h, 1)],
                "area": round(w * h, 1), "iscrowd": 0,
                "occlusion": round(float(row["occlusionRatio"]), 3),
            })

coco = {"info": {"description": "MiniHannover perfumery lab — synthetic barcode "
                 "detection dataset (Isaac Sim RTX)", "version": "1.0"},
        "images": images, "annotations": annotations, "categories": categories}
json.dump(coco, open(os.path.join(OUT, "annotations", "instances.json"), "w"))

readme = f"""# MiniHannover lab — synthetic dataset v1

Isaac Sim 4.5 RTX renders of the perfumery lab bench, {len(images)} labelled
images across {len(CAMS)} camera viewpoints, with per-bottle 2D bounding boxes
labelled by **EAN-13 barcode id** (the product), plus semantic-segmentation masks.

Domain randomization: interior light intensity + colour tint per frame.

## Layout
- `images/<cam>/rgb_NNNN.png`  — RGB (1600x900)
- `masks/<cam>/semantic_NNNN.png` — colorized semantic segmentation
- `annotations/instances.json` — COCO detection ({len(categories)} categories,
  {len(annotations)} boxes). category name == barcode id (e.g. PWD_0005).

Cameras: {", ".join(CAMS)}.
Generated by simulation/scripts/dataset_gen.py + build_coco.py.
"""
open(os.path.join(OUT, "README.md"), "w").write(readme)
print(f"images={len(images)} annotations={len(annotations)} categories={len(categories)}")
print("wrote", OUT)
