#!/usr/bin/env python3
"""Put a UR10e on an overhead linear rail above the shelf-free MiniHannover bench.

Run from simulation/: python scripts/generate_rail_scene.py.
Needs the Menagerie models first: bash scripts/fetch_menagerie.sh.

Writes two generated files:

* ``assets/ur10e_2f85/ur10e_2f85.xml`` --- Menagerie's UR10e with a Robotiq
  2F-85 attached at its wrist flange, plus the eye-in-hand camera: the MJCF
  camera, a site the IK aims, and the modelled camera body from
  ``assets/wrist_camera/`` at exactly the same pose, so the scene shows the
  hardware the pictures come from. MJCF cannot attach a child model to a *site*
  of an already-attached model, so all of it has to be spliced into a copy of
  the arm rather than added from the scene file.
* ``models/minihannover_rail_scene.xml`` --- the open scene plus the gantry:
  two end posts, a beam along the bench, and a carriage on a slide joint that
  carries the arm.

Why a rail at all: the UR10e reaches 1.30 m, the widest in Menagerie, and the
bench is 6 x 2 m. One static base covers a 1.30 m disc, about a third of the
worktop; a base that slides along the 6 m axis covers all of it.

Why the rail sits where it does, all measured off the open scene:

* ``RAIL_Y`` at the back edge strip. The wall camera looks at the bench from
  -Y, so a gantry behind the glassware hides the back edge instead of the
  bottles. Everything the arm has to pick lives in y = -0.83 .. 0.03.
* ``BEAM_BOTTOM`` clears 1.30 m, the top of the two analytical balances that
  stand on that strip, by 60 mm.
* The arm base ends up 0.55 m above the worktop, about the height
  its own gripper works at, so the full 1.30 m stays available horizontally
  instead of being spent on the drop to the bench.
"""
import argparse
import re
import xml.etree.ElementTree as ET
from pathlib import Path

import generate_open_vessels as open_vessels
import numpy as np

SIM = Path(__file__).resolve().parents[1]
MENAGERIE = SIM / 'third_party/mujoco_menagerie'
ARM_DIR = SIM / 'assets/ur10e_2f85'
GRIPPER_DIR = SIM / 'assets/robotiq_2f85_sensed'
BASE_SCENE = 'minihannover_open_scene.xml'
ROOM = SIM / 'assets/minihannover_open/lab_room.xml'
# Written beside the original so its ../labelled_bottles/... mesh paths still
# resolve; it is the same room with the dynamic vessels cut out of it.
DYNAMIC_ROOM = SIM / 'assets/minihannover_open/lab_room_dynamic.xml'
OUT_SCENE = SIM / 'models/minihannover_rail_scene.xml'
HEADER = '<!-- Generated by scripts/generate_rail_scene.py; do not edit by hand. -->\n'

# Bench, from assets/minihannover_open/bench.xml: 6 x 2 m worktop, top at 0.90.
BENCH_X = (-4.5, 1.5)
BENCH_Y = (-1.4, 0.6)
BENCH_TOP = 0.90

RAIL_Y = 0.30          # rail axis, on the back edge strip
BEAM_BOTTOM = 1.36     # underside of the beam; balances on that strip top out at 1.30
BEAM_HALF_Z = 0.04
BEAM_HALF_Y = 0.06
BEAM_OVERHANG = 0.40   # beam sticks out past each end of the bench
POST_HALF = 0.06
CARRIAGE_HALF = (0.16, 0.20, 0.05)
CARRIAGE_Y = 0.14      # carriage hangs off the bench side of the beam
ARM_BASE_DZ = 0.05     # arm base sits on the top face of the carriage plate

BEAM_Z = BEAM_BOTTOM + BEAM_HALF_Z
BEAM_HALF_X = (BENCH_X[1] - BENCH_X[0]) / 2 + BEAM_OVERHANG
BEAM_X = (BENCH_X[0] + BENCH_X[1]) / 2
POST_X = BEAM_HALF_X - POST_HALF - 0.02
# Travel: the carriage can stand over any point of the worktop and a little past
# each end, stopping short of the posts.
TRAVEL = BEAM_HALF_X - POST_HALF * 2 - CARRIAGE_HALF[0] - 0.08
ARM_BASE_Z = BEAM_Z + ARM_BASE_DZ

# Scan pose: hand pointing straight down, wrist about 0.45 m below the base, the
# arm folded toward -Y so it leans over the bench rather than the back wall.
SCAN_POSE = (-1.5708, -1.9199, 2.0944, -1.7453, -1.5708, 0.0)

# How many vessels stand on the bench in this scene, spread along it. The open
# scene the computer-vision work renders from keeps its full population; here
# the bench is cleared down to a handful so the manipulation case is simple to
# watch and to debug. All of them are free bodies that can be picked up.
#
# Twelve is the manipulation scene. Raising it makes the task harder, and the
# two jobs want different benches: at thirty the vision scan is a good test
# --- more targets, still 98 mm apart --- and the pipette starts clipping
# neighbours on the way in, 12 mm of mean tip error against 1.1 at twelve.
# Pass --vessels to regenerate at another count.
BENCH_VESSELS = 12

# Which tool hangs on the flange. 'pipette' is the pipetting scene; 'gripper'
# puts the Robotiq back for scripts/grasp_test.py.
TOOL = 'pipette'

# Which of the scene's five balances gets its roof cut off and takes the beaker.
# balance_5 stands at x = -0.75 on the back strip, the closest one to the rail.
OPEN_BALANCE = 'balance_5_'
BALANCE_PAN = (-0.005, 0.031, 0.077)    # pan centre in the balance's own frame
# and it moves here. Left where it stood on the back strip, the beaker's rim
# sits at 1.08 m, which puts the pipette's flange at 1.34 --- 20 mm under the
# gantry beam, with the whole wrist in the way. Out in front of the rail there
# is nothing overhead.
BALANCE_POS = (0.60, -0.45, BENCH_TOP)

# Eye-in-hand camera, in the tool frame (+Z is the approach direction).
EIH_OFFSET = 0.09   # to the side of the tool axis, clear of the fingers
EIH_DROP = 0.03     # below the flange: on the wrist, just under it
EIH_TILT = 0.0      # degrees of convergence toward the tool axis. Zero on
                    # purpose: the gripper sits ON that axis, so a converging
                    # camera aims straight at the back of its own fingers.
                    # Parallel puts the gripper at the frame edge instead and
                    # whatever the camera is aimed at in the middle.


def _fmt(vector) -> str:
    """Format a 3-vector for an MJCF attribute."""
    return ' '.join(f'{v:.4f}' for v in vector)


def build_gripper() -> Path:
    """Write a Robotiq 2F-85 that can feel what it is holding.

    Menagerie's gripper already behaves like the real one when it closes on
    something: the actuator is a position servo on a tendon with
    ``forcerange="-5 5"``, so the pads stall against the object and keep
    squeezing at the limit instead of crushing through it. What it has no way of
    doing is *reporting* that, and the scene has no sensors at all --- which
    leaves a grasp check with nothing to go on but the object's true height,
    which no real cell can see.

    This copy adds a touch site over each pad and the sensors that reconstruct
    the 2F-85's own object-detection status: how hard each pad is pressed, what
    the finger servo is putting out, and how far the fingers actually closed.
    Fingers stalled short of shut plus force on the pads is a held object;
    fingers all the way shut with no force is a closure on thin air.

    Returns:
        Path of the generated gripper MJCF.

    Raises:
        FileNotFoundError: If the Menagerie models have not been fetched.
    """
    source = MENAGERIE / 'robotiq_2f85/2f85.xml'
    if not source.exists():
        raise FileNotFoundError(
            f'{source} missing --- run: bash scripts/fetch_menagerie.sh')

    xml = source.read_text()
    xml = xml.replace(
        'meshdir="assets"',
        'meshdir="../../third_party/mujoco_menagerie/robotiq_2f85/assets"')
    # One site per finger, spanning both pad boxes, for the touch sensors.
    for side in ('right', 'left'):
        xml = xml.replace(
            f'<geom class="pad_box2" name="{side}_pad2"/>',
            f'<geom class="pad_box2" name="{side}_pad2"/>\n'
            f'              <site name="{side}_pad_touch" type="box"\n'
            f'                    pos="0 -0.0026 0.01875" size="0.013 0.006 0.021"\n'
            f'                    rgba="0.9 0.4 0.1 0.25" group="4"/>')
    xml = xml.replace('</mujoco>',
                      '  <sensor>\n'
                      '    <touch name="right_pad_force" site="right_pad_touch"/>\n'
                      '    <touch name="left_pad_force" site="left_pad_touch"/>\n'
                      '    <actuatorfrc name="finger_drive" actuator="fingers_actuator"/>\n'
                      '    <jointpos name="right_finger" joint="right_driver_joint"/>\n'
                      '    <jointpos name="left_finger" joint="left_driver_joint"/>\n'
                      '  </sensor>\n'
                      '</mujoco>')
    xml = xml.replace('<mujoco model="2f85">',
                      '<mujoco model="2f85_sensed">\n  ' + HEADER.strip())

    GRIPPER_DIR.mkdir(parents=True, exist_ok=True)
    out = GRIPPER_DIR / '2f85_sensed.xml'
    out.write_text(xml)
    return out


def build_pipette() -> Path:
    """Generate the pipette, and the beaker it dispenses into.

    Returns:
        Path of the generated pipette MJCF.
    """
    import generate_beaker
    import generate_open_balance
    import generate_pipette

    generate_beaker.main()
    generate_open_balance.main()
    generate_pipette.main()
    return SIM / 'assets/pipette/pipette.xml'


def build_arm() -> Path:
    """Write the UR10e + Robotiq 2F-85 model used by the scene.

    Returns:
        Path of the generated arm MJCF.

    Raises:
        FileNotFoundError: If the Menagerie models have not been fetched.
    """
    source = MENAGERIE / 'universal_robots_ur10e/ur10e.xml'
    if not source.exists():
        raise FileNotFoundError(
            f'{source} missing --- run: bash scripts/fetch_menagerie.sh')

    xml = source.read_text()
    # A thin visual-only wrap on both sides of the upper arm. Keep the supplied
    # vector wordmark in assets/branding; UVs preserve its original proportions.
    vertices, uv, faces = [], [], []
    segments = 32
    for i in range(segments + 1):
        v = i / segments
        angle = (v - 0.5) * (0.28 * 350 / 1540) / 0.061
        for u in (0, 1):
            vertices.extend((0.061 * np.sin(angle),
                             -0.061 * np.cos(angle), 0.3065 + (u - 0.5) * 0.28))
            uv.extend((1 - u, 1 - v))
    for i in range(segments):
        a = 2 * i
        faces.extend((a, a + 2, a + 1, a + 1, a + 2, a + 3))
    xml = xml.replace('<asset>', '<asset>\n'
        '    <texture name="mafer_logo" type="2d" file="../branding/mafer-label.png"/>\n'
        '    <material name="mafer_label" texture="mafer_logo" specular="0.1" shininess="0.1"/>\n'
        f'    <mesh name="mafer_wrap" vertex="{_fmt(vertices)}" '
        f'texcoord="{_fmt(uv)}" face="{" ".join(map(str, faces))}"/>', 1)
    anchor = '<geom mesh="upperarm_3" material="linkgray" class="visual"/>'
    xml = xml.replace(anchor, anchor + '\n'
        '          <geom name="mafer_front" mesh="mafer_wrap" material="mafer_label" class="visual" mass="0"/>\n'
        '          <geom name="mafer_back" mesh="mafer_wrap" material="mafer_label" class="visual" mass="0" quat="0 0 0 1"/>')
    rel = '../../third_party/mujoco_menagerie'
    xml = xml.replace('meshdir="assets"',
                      f'meshdir="{rel}/universal_robots_ur10e/assets"')
    xml = xml.replace(
        '<asset>',
        '<asset>\n'
        + ('    <model name="robotiq_2f85" file="../robotiq_2f85_sensed/2f85_sensed.xml"/>\n'
           if TOOL == 'gripper' else
           '    <model name="pipette" file="../pipette/pipette.xml"/>\n')
        + '    <model name="wrist_camera" file="../wrist_camera/wrist_camera.xml"/>',
        1)
    # The flange site is where UR documents the tool frame; put the gripper on it,
    # and the eye-in-hand camera beside it. Both live in a frame whose +Z is the
    # tool's approach direction.
    #
    # The camera sits EIH_OFFSET to the side and EIH_DROP below the flange --- on
    # the wrist, just under it, clear of the fingers --- looking EIH_TILT off the
    # tool axis. A MuJoCo camera looks along its own -Z; `eih_site` is the same
    # pose with +Z along the view instead, which is what solve_ik expects.
    view = np.array([-np.sin(np.radians(EIH_TILT)), 0.0,
                     np.cos(np.radians(EIH_TILT))])
    up = np.cross(-view, (0.0, 1.0, 0.0))
    xml = xml.replace(
        '<site name="attachment_site" pos="0 0.1 0" quat="-1 1 0 0"/>',
        '<site name="attachment_site" pos="0 0.1 0" quat="-1 1 0 0"/>\n'
        '                  <frame pos="0 0.1 0" quat="-1 1 0 0">\n'
        + ('                    <attach model="robotiq_2f85" body="base_mount" prefix="grip_"/>\n'
           if TOOL == 'gripper' else
           '                    <attach model="pipette" body="pipette" prefix="pip_"/>\n')
        +
        f'                    <camera name="eih" pos="{EIH_OFFSET} 0 {EIH_DROP}"\n'
        f'                            xyaxes="0 1 0 {_fmt(up)}"\n'
        '                            fovy="60.44" resolution="1920 1080"/>\n'
        f'                    <site name="eih_site" pos="{EIH_OFFSET} 0 {EIH_DROP}"\n'
        f'                          xyaxes="0 1 0 {_fmt(-up)}" size="0.004" group="4"/>\n'
        f'                    <frame pos="{EIH_OFFSET} 0 {EIH_DROP}"\n'
        f'                           xyaxes="0 1 0 {_fmt(-up)}">\n'
        '                      <attach model="wrist_camera" body="wrist_camera"\n'
        '                              prefix="cam_"/>\n'
        '                    </frame>\n'
        '                  </frame>')
    # Gravity compensation on the arm links. Menagerie's stock position gains
    # leave about 20 mm of droop at the tool under gravity, which is more than
    # the radius of a 20 ml flask --- the gripper closes off-centre and catches
    # the vessel with one pad instead of pinching it. Compensating gravity
    # leaves the servos only inertia to fight. The payload is deliberately not
    # compensated: a held vessel should still weigh something.
    xml = re.sub(r'<body name="(base|shoulder_link|upper_arm_link|forearm_link|'
                 r'wrist_1_link|wrist_2_link|wrist_3_link)"',
                 r'<body gravcomp="1" name="\1"', xml)
    # The arm's own keyframe no longer matches nq once the gripper is on, and the
    # scene sets poses from Python anyway.
    xml = re.sub(r'\n  <keyframe>.*?</keyframe>', '', xml, flags=re.DOTALL)
    xml = xml.replace('<mujoco model="ur10e">',
                      '<mujoco model="ur10e_2f85">\n  ' + HEADER.strip())

    ARM_DIR.mkdir(parents=True, exist_ok=True)
    out = ARM_DIR / 'ur10e_2f85.xml'
    out.write_text(xml)
    return out


def build_bench(keep: int) -> list[dict[str, str]]:
    """Clear the bench down to `keep` vessels, and hand them to the scene.

    The bench population is baked into the room model as static geometry: five
    geoms per vessel, one of them a collision cylinder. That makes every vessel
    an obstacle and none of them an object --- no body, no joint, no mass, so a
    closed gripper slides straight through the pose. Vessels that need to be
    picked up have to become bodies with a free joint in the *scene*, because
    MuJoCo only allows a free joint on a child of the world, and the room is
    attached as a body.

    Everything not kept is deleted rather than left standing, so the survivors
    have room for the fingers. The open scene keeps its full population; this
    only thins the copy the rail scene loads.

    Each catalogued sample already exists as its own model under
    assets/labelled_bottles/, which is how the scene's seven loose vessels are
    built, so the scene re-adds them the same way rather than rebuilding the
    geometry.

    Args:
        count: How many vessels to lift, spread along the bench.

    The static geoms are nested inside the room's sub-bodies, so their ``pos``
    attributes are not world coordinates. The pose to re-create each vessel at
    is read from the compiled base scene instead, where MuJoCo has already
    composed the whole chain.

    Returns:
        One dict per lifted vessel with its sample id, world position and yaw.
    """
    tree = ET.parse(ROOM)
    # The population is nested inside the room's sub-bodies, so walk the whole
    # tree and keep a parent map: ElementTree has no parent pointers and the
    # geoms have to be removed from wherever they actually live.
    parent_of = {child: parent for parent in tree.getroot().iter()
                 for child in parent}
    vessels: dict[str, list[ET.Element]] = {}
    for geom in list(tree.getroot().iter('geom')):
        # Keep the wash-zone balance clear in the rail scene.
        if geom.get('name') == 'funnel_0':
            parent_of[geom].remove(geom)
            continue
        match = re.match(r'stock_(.+?)_(?:glass|cap|label|label_back|collision)',
                         geom.get('name', ''))
        if match:
            vessels.setdefault(match.group(1), []).append(geom)

    # Only catalogued samples have a model of their own to re-attach; the
    # unbarcoded reserve stock is scenery either way, so it always goes.
    catalogued = [s for s in vessels
                  if (SIM / f'assets/labelled_bottles/{s}.xml').exists()]
    ordered = sorted(catalogued,
                     key=lambda k: float(vessels[k][0].get('pos').split()[0]))
    step = max(len(ordered) // max(keep, 1), 1)
    picked = ordered[::step][:keep]

    import mujoco

    base = mujoco.MjModel.from_xml_path(str(SIM / 'models' / BASE_SCENE))
    state = mujoco.MjData(base)
    mujoco.mj_forward(base, state)

    for sample, geoms in vessels.items():
        if sample in picked:
            continue
        for geom in geoms:
            parent_of[geom].remove(geom)

    lifted = []
    for sample in picked:
        geoms = vessels[sample]
        # A mesh geom's xpos is the mesh's own centre, because the compiler
        # re-centres mesh vertices and records the shift in mesh_pos. Undoing
        # that shift recovers the authored origin --- the vessel's bottom
        # centre, which is the frame the per-sample model under
        # assets/labelled_bottles/ is built in.
        placed = state.geom(f'room_stock_{sample}_glass_0')
        rotation = placed.xmat.reshape(3, 3)
        shift = base.mesh_pos[base.geom_dataid[base.geom(f'room_stock_{sample}_glass_0').id]]
        origin = placed.xpos - rotation @ shift
        yaw = np.degrees(np.arctan2(rotation[1, 0], rotation[0, 0]))
        lifted.append({'sample': sample,
                       'pos': ' '.join(f'{v:.6g}' for v in origin),
                       'euler': f'0 0 {yaw:.6g}'})
        for geom in geoms:
            parent_of[geom].remove(geom)

    ET.indent(tree.getroot(), space='  ')
    DYNAMIC_ROOM.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n' + HEADER
        + ET.tostring(tree.getroot(), encoding='unicode') + '\n')
    return lifted


def build_scene() -> Path:
    """Write the rail scene: the open bench scene plus the gantry and the arm.

    The base scene is spliced in rather than ``<include>``d: MuJoCo resolves the
    asset paths of an included file against the *including* file's directory,
    which breaks the ``../assets/...`` references. Both files sit in models/, so
    copying the tree over keeps every path valid.

    Returns:
        Path of the generated scene MJCF.
    """
    tree = ET.parse(SIM / 'models' / BASE_SCENE)
    root = tree.getroot()
    root.set('model', 'minihannover_rail_scene')

    # The gripper wants elliptic friction cones, the arm wants implicitfast.
    ET.SubElement(root, 'option', integrator='implicitfast', impratio='10',
                  cone='elliptic')

    asset = root.find('asset')
    ET.SubElement(asset, 'material', name='gantry', rgba='0.42 0.44 0.48 1',
                  specular='0.4', shininess='0.5')
    ET.SubElement(asset, 'material', name='carriage', rgba='0.22 0.24 0.28 1',
                  specular='0.5', shininess='0.6')
    ET.SubElement(asset, 'model', name='ur10e_2f85',
                  file='../assets/ur10e_2f85/ur10e_2f85.xml')

    # Swap the room for the one without the vessels the scene now owns, and
    # declare each of those as its own model.
    lifted = build_bench(BENCH_VESSELS)
    asset.find('model[@name="lab_room"]').set(
        'file', f'../{DYNAMIC_ROOM.relative_to(SIM)}')
    open_vessels.main_for([v['sample'] for v in lifted])
    for vessel in lifted:
        ET.SubElement(asset, 'model', name=f'dyn_{vessel["sample"]}',
                      file=f'../assets/open_vessels/{vessel["sample"]}.xml')
    if TOOL == 'pipette':
        ET.SubElement(asset, 'model', name='beaker',
                      file='../assets/beaker/beaker.xml')
        ET.SubElement(asset, 'model', name='balance_open',
                      file='../assets/balance_open/balance_open.xml')

    world = root.find('worldbody')
    for vessel in lifted:
        body = ET.SubElement(world, 'body', name=f'dyn_{vessel["sample"]}',
                             pos=vessel['pos'], euler=vessel['euler'])
        ET.SubElement(body, 'freejoint')
        ET.SubElement(body, 'attach', model=f'dyn_{vessel["sample"]}',
                      body=vessel['sample'], prefix=f'dyn_{vessel["sample"]}_')
    if TOOL == 'pipette':
        # One balance loses its roof and gains a pan; the beaker stands on it.
        frame = next(f for f in world.iter('frame')
                     if any(a.get('prefix') == OPEN_BALANCE
                            for a in f.findall('attach')))
        frame.find('attach').set('model', 'balance_open')
        frame.set('pos', ' '.join(f'{v:g}' for v in BALANCE_POS))
        frame.attrib.pop('euler', None)
        base = list(BALANCE_POS)
        beaker = ET.SubElement(
            world, 'body', name='beaker',
            pos=' '.join(f'{base[i] + BALANCE_PAN[i]:.5g}' for i in range(3)))
        ET.SubElement(beaker, 'freejoint')
        ET.SubElement(beaker, 'attach', model='beaker', body='beaker',
                      prefix='beaker_')

    post_z = BEAM_BOTTOM / 2
    rail = ET.SubElement(world, 'body', name='rail')
    for side, x in (('left', BEAM_X - POST_X), ('right', BEAM_X + POST_X)):
        ET.SubElement(rail, 'geom', name=f'rail_post_{side}', type='box',
                      material='gantry', pos=f'{x:.3f} {RAIL_Y} {post_z:.3f}',
                      size=f'{POST_HALF} {POST_HALF} {post_z:.3f}')
    ET.SubElement(rail, 'geom', name='rail_beam', type='box', material='gantry',
                  pos=f'{BEAM_X} {RAIL_Y} {BEAM_Z:.3f}',
                  size=f'{BEAM_HALF_X:.3f} {BEAM_HALF_Y} {BEAM_HALF_Z}')

    carriage = ET.SubElement(world, 'body', name='rail_carriage',
                             pos=f'{BEAM_X} {CARRIAGE_Y} {BEAM_Z:.3f}')
    ET.SubElement(carriage, 'joint', name='rail_x', type='slide', axis='1 0 0',
                  range=f'{-TRAVEL:.3f} {TRAVEL:.3f}', damping='200',
                  armature='20')
    ET.SubElement(carriage, 'geom', name='rail_carriage_plate', type='box',
                  material='carriage', mass='40', contype='0', conaffinity='0',
                  size=' '.join(str(h) for h in CARRIAGE_HALF))
    frame = ET.SubElement(carriage, 'frame', pos=f'0 0 {ARM_BASE_DZ}')
    ET.SubElement(frame, 'attach', model='ur10e_2f85', body='base',
                  prefix='arm_')
    # Rides with the arm, looking down the bench from behind the carriage.
    ET.SubElement(carriage, 'camera', name='carriage', pos='0 -0.9 0.75',
                  xyaxes='1 0 0 0 0.6 0.8', fovy='60.44',
                  resolution='1920 1080')

    actuator = ET.SubElement(root, 'actuator')
    ET.SubElement(actuator, 'position', name='rail_x', joint='rail_x',
                  kp='60000', kv='6000', forcerange='-4000 4000',
                  ctrlrange=f'{-TRAVEL:.3f} {TRAVEL:.3f}')

    keyframe = ET.SubElement(root, 'keyframe')
    # Rail, the six arm joints, and the gripper's finger drive when it is on.
    pose = ' '.join(f'{q:.4f}' for q in SCAN_POSE)
    tail = ' 0' if TOOL == 'gripper' else ''
    ET.SubElement(keyframe, 'key', name='scan', ctrl=f'0 {pose}{tail}')

    ET.indent(root, space='  ')
    OUT_SCENE.write_text('<?xml version="1.0" encoding="utf-8"?>\n' + HEADER
                         + ET.tostring(root, encoding='unicode') + '\n')
    return OUT_SCENE


def check_camera_clearance() -> float:
    """Confirm no part of the modelled camera can appear in its own picture.

    The camera body is placed relative to the lens front, so a change to either
    the mount offsets or the model can quietly push hardware in front of the
    lens, where it shows up as a black crescent on every frame. Cheap to assert
    here instead.

    Returns:
        The clearance in metres: how far the frontmost camera part sits behind
        the viewpoint.

    Raises:
        AssertionError: If anything sits in front of it.
    """
    import mujoco

    model = mujoco.MjModel.from_xml_path(str(OUT_SCENE))
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)
    camera = model.camera('arm_eih').id
    view = -data.cam_xmat[camera].reshape(3, 3)[:, 2]
    worst, worst_name = -np.inf, ''
    for i in range(model.ngeom):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, i) or ''
        if not name.startswith('arm_cam_'):
            continue
        # Frontmost corner of the geom's own bounding box, which is tight for
        # the boxes and cylinders this camera is made of.
        centre, half = model.geom_aabb[i][:3], model.geom_aabb[i][3:]
        signs = np.array([[sx, sy, sz] for sx in (-1, 1) for sy in (-1, 1)
                          for sz in (-1, 1)])
        corners = ((signs * half + centre)
                   @ data.geom_xmat[i].reshape(3, 3).T + data.geom_xpos[i])
        front = float(np.dot(corners - data.cam_xpos[camera], view).max())
        if front > worst:
            worst, worst_name = front, name
    assert worst < 0, f'{worst_name} sticks {worst * 1000:.1f} mm into the view'
    return -worst


def main() -> None:
    global BENCH_VESSELS
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--vessels', type=int, default=BENCH_VESSELS,
                        help='vessels to leave standing on the bench')
    BENCH_VESSELS = parser.parse_args().vessels

    tool = build_gripper() if TOOL == 'gripper' else build_pipette()
    arm = build_arm()
    scene = build_scene()
    print(f'wrote {tool.relative_to(SIM)}')
    print(f'wrote {arm.relative_to(SIM)}')
    print(f'wrote {scene.relative_to(SIM)}')
    print(f'rail: y={RAIL_Y} m, beam underside {BEAM_BOTTOM} m, '
          f'arm base {ARM_BASE_Z:.3f} m ({ARM_BASE_Z - BENCH_TOP:.2f} m over the worktop)')
    print(f'travel: x = {BEAM_X - TRAVEL:.2f} .. {BEAM_X + TRAVEL:.2f} m '
          f'({2 * TRAVEL:.2f} m), bench spans {BENCH_X[0]} .. {BENCH_X[1]} m')
    print(f'camera: modelled body clears its own lens by '
          f'{check_camera_clearance() * 1000:.1f} mm')
    print(f'bench: cleared to {BENCH_VESSELS} vessels, all of them liftable')


if __name__ == '__main__':
    main()
