#!/usr/bin/env python3
"""Create a shelf-free MiniHannover variant with a centered 6 x 2 m desk.

Run from simulation/: python scripts/generate_minihannover_open.py.
Reuses the original room builders and scene assets without rewriting them.
"""
import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET

import numpy as np

import bottle_patterns as patterns
import generate_lab_room as room
import generate_minihannover as bench

SIM = Path(__file__).resolve().parents[1]
OUT = SIM / 'assets/minihannover_open'
WIDTH = 2.0
CENTER = np.array(((room.X0 + room.X1) / 2, (room.Y0 + room.Y1) / 2, 0.0))
EDGE_SHIFT = 0.25
EXTRA_AMBER = 0  # no blank reserve vials: every bottle is a uniquely-labelled catalogue sample
POPULATION_SEED = 29
PATTERNS = OUT / 'patterns'   # one population file per seeded pattern
HEADER = '<!-- Generated by scripts/generate_minihannover_open.py; do not edit by hand. -->\n'


def write_xml(path, root):
    ET.indent(root, space='  ')
    path.write_text('<?xml version="1.0" encoding="utf-8"?>\n' + HEADER + ET.tostring(root, encoding='unicode') + '\n')


def camera(m, name, eye, target, fovy=60):
    eye, target = np.array(eye, float), np.array(target, float)
    forward = (target - eye) / np.linalg.norm(target - eye)
    right = np.cross(forward, (0, 0, 1))
    right /= np.linalg.norm(right)
    up = np.cross(right, forward)
    m.add(f'<camera name="{name}" pos="{room.fmt(eye)}" xyaxes="{room.fmt(right)} {room.fmt(up)}" fovy="{fovy}"/>')


def edge_props(m):
    """Move each side's work stations outward; end-mounted wash/scale stay put."""
    start = len(m.lines)
    room.bench_props(m)
    fragment = ET.fromstring('<frame>' + '\n'.join(m.lines[start:]) + '</frame>')
    del m.lines[start:]
    for geom in fragment:
        if geom.tag != 'geom':
            continue
        attr = 'fromto' if 'fromto' in geom.attrib else 'pos'
        values = np.fromstring(geom.get(attr, '0 0 0'), sep=' ').reshape(-1, 3)
        center = values.mean(axis=0)
        if -2.5 < center[0] < 2.0:
            values[:, 1] += EDGE_SHIFT if center[1] >= 0 else -EDGE_SHIFT
            geom.set(attr, room.fmt(values.ravel()))
        m.add(ET.tostring(geom, encoding='unicode'))


def stem(pattern, base):
    """Name a build: plain for the full bench, suffixed for a seeded pattern.

    Used for both the file and the MJCF model name, so a variant announces
    itself in the viewer instead of looking like the default scene.
    """
    return base if pattern is None else f'{base}_{pattern.name}'


def catalogue_samples():
    """Manifest entries for the flasks the desk may stand on the worktop.

    Returns:
        The vessel classes, and the liquid samples the scene does not place by
        hand --- powders and the thirteen hand-placed work samples are out.
    """
    manifest = json.loads((room.BOTTLES / 'manifest.json').read_text())
    vessels = manifest['vessels']
    samples = {k: v for k, v in manifest['samples'].items()
               if k not in room.PLACED_BY_SCENE
               and vessels[v['vessel_class']]['phase'] == 'liquid'}
    return vessels, samples


def full_population(vessels, samples):
    """The bench as it has always been: every catalogue flask, one fixed seed.

    Kept exactly as it was --- same seed, same draw order, same 9 mm spacing ---
    so regenerating the default scene reproduces the committed XML byte for
    byte. Seeded patterns are the variable bench; this one is the reference.

    Args:
        vessels: ``manifest['vessels']``.
        samples: The liquid samples that may be placed.

    Returns:
        The placed containers, and the header of their population file.
    """
    rng = np.random.default_rng(POPULATION_SEED)
    records = [dict(sample_id=k, vessel_class=v['vessel_class'])
               for k, v in sorted(samples.items())]
    # Preserve catalogued sizes/barcodes. Extra stock has blank labels, not duplicate IDs.
    for i in range(EXTRA_AMBER):
        vessel = str(rng.choice(['flask_10ml', 'flask_20ml', 'flask_30ml', 'flask_50ml'],
                               p=[0.40, 0.32, 0.20, 0.08]))
        records.append(dict(sample_id=None, vessel_class=vessel, extra_id=i))
    # Pack larger containers first; each position is random rather than a size-sorted row.
    records.sort(key=lambda r: -vessels[r['vessel_class']]['diameter_m'])
    placed = []
    for record in records:
        radius = vessels[record['vessel_class']]['diameter_m'] / 2
        for attempt in range(20000):
            x = rng.uniform(-2.42 + radius, 1.90 - radius)
            y = rng.uniform(-0.43 + radius, 0.43 - radius)
            if all((x-p['x'])**2 + (y-p['y'])**2 > (radius+p['radius']+0.009)**2 for p in placed):
                break
        else:
            raise RuntimeError('Population does not fit with required spacing')
        record.update(x=float(x), y=float(y), radius=radius,
                      yaw=float(rng.uniform(-180, 180)))
        placed.append(record)
    return placed, dict(seed=POPULATION_SEED)


def pattern_population(pattern, vessels, samples):
    """The bench a seed asks for: its crowd, its spacing, its layout.

    Args:
        pattern: A ``bottle_patterns.Pattern``.
        vessels: ``manifest['vessels']``.
        samples: The liquid samples that may be placed.

    Returns:
        The placed containers, and the header of their population file.
    """
    records = patterns.pick_samples(pattern, samples, vessels)
    placed, gap = patterns.place(pattern, records)
    if pattern.seed == 176:
        # Scene 2: these two flasks account for all four gaps below 3.68 cm.
        placed = [p for p in placed if p['sample_id'] not in {'SMP-0183', 'SMP-0060'}]
    if pattern.seed == 327:
        # Scene 4: remove one flask from each of the two closest pairs.
        placed = [p for p in placed if p['sample_id'] not in {'SMP-0138', 'SMP-0144'}]
        # The next gap is 3.675084 cm, rounded to 3.68 cm in the layout review.
        # Move 0.05 mm away from its neighbour to meet 3.68 cm strictly.
        by_id = {p['sample_id']: p for p in placed}
        fixed, moved = by_id['SMP-0053'], by_id['SMP-0123']
        delta = np.array([moved['x'] - fixed['x'], moved['y'] - fixed['y']])
        delta *= 0.00005 / np.linalg.norm(delta)
        moved['x'] += float(delta[0])
        moved['y'] += float(delta[1])
    if pattern.seed in {176, 327}:
        gap = min(
            np.hypot(a['x'] - b['x'], a['y'] - b['y']) - a['radius'] - b['radius']
            for i, a in enumerate(placed) for b in placed[i + 1:]
        )
    return placed, patterns.describe(pattern, placed, gap)


def write_population(placed, header, path, vessels):
    """Record what stands on the worktop, for the twin and the dataset tools."""
    containers = []
    for record in placed:
        spec = vessels[record['vessel_class']]
        containers.append(dict(record, phase=spec['phase'],
                               container_ml=spec['container_ml']))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(dict(
        header,
        coordinate_frame='desk local, origin at floor; containers rest at z=0.90 m',
        containers=containers), indent=2) + '\n')
    return containers


def tabletop_population(m, placed, vessels):
    """Write the worktop stock into the room: meshes, labels and a contact proxy.

    Args:
        m: The room's MJCF builder.
        placed: Containers from ``full_population`` or ``pattern_population``.
        vessels: ``manifest['vessels']``.
    """
    used_meshes = set()
    for record in placed:
        vessel = record['vessel_class']
        spec = vessels[vessel]
        x, y, yaw, radius = record['x'], record['y'], record['yaw'], record['radius']
        sample = record['sample_id']
        tag = sample if sample else f"reserve_{record['extra_id']:03d}"
        if sample:
            m.assets.append(f'<texture name="stock_{tag}" type="2d" file="../labelled_bottles/textures/shelf/{sample}.png"/>')
            m.assets.append(f'<material name="stock_{tag}" texture="stock_{tag}" specular="0.05"/>')
        for part in spec['parts']:
            mesh = f'{vessel}_{part}' if part.startswith('label') else f'{vessel}_shelf_{part}'
            used_meshes.add(mesh)
            material = {'glass':'amber', 'body':'sample_hdpe', 'cap':'sample_cap',
                        'label':'paper', 'label_back':'paper'}[part]
            if part == 'label' and sample:
                material = f'stock_{tag}'
            m.mesh(f'stock_{tag}_{part}', mesh, (x,y,room.BENCH_TOP), material, euler=(0,0,yaw))
        # Welded stock, matching the original shelf behavior, with a simple contact proxy.
        height = spec['height_m']
        m.add(f'<geom name="stock_{tag}_collision" type="cylinder" '
              f'pos="{room.fmt((x,y,room.BENCH_TOP+height/2))}" size="{radius:g} {height/2:g}" '
              'group="3" rgba="0 0 0 0"/>')
    for mesh in sorted(used_meshes):
        m.assets.append(f'<mesh name="{mesh}" file="../labelled_bottles/meshes/{mesh}.obj" inertia="shell"/>')


def build_population(pattern=None):
    """Lay the worktop out and write its population file.

    Args:
        pattern: A ``bottle_patterns.Pattern``, or None for the full bench.

    Returns:
        The placed containers and the manifest's vessel classes.
    """
    vessels, samples = catalogue_samples()
    if pattern is None:
        placed, header = full_population(vessels, samples)
        path = OUT / 'population.json'
    else:
        placed, header = pattern_population(pattern, vessels, samples)
        path = PATTERNS / f'{pattern.name}.json'
    write_population(placed, header, path, vessels)
    label = 'full bench' if pattern is None else f'{pattern.name} (seed {pattern.seed}, {pattern.style})'
    print(f"{label}: {len(placed)} containers -> {path.relative_to(SIM)}")
    return placed, vessels


def build_room(pattern=None):
    """Write the room, with either the full bench or one seeded pattern on it."""
    placed, vessels = build_population(pattern)
    m = room.Mjcf()
    for build in (room.shell, room.ceiling, room.lights):
        build(m)
    m.add(f'<frame pos="{room.fmt(CENTER)}">')
    room.central_bench(m, half_width=WIDTH / 2)
    edge_props(m)
    tabletop_population(m, placed, vessels)
    room.snorkels(m)
    m.add('</frame>')
    for build in (room.wall_bench, room.entrance_corner, room.instrument_bench,
                  room.far_end, room.office_beyond):
        build(m)
    cx, cy, _ = CENTER
    camera(m, 'entrance', (room.X0 + 0.6, cy - 1.35, 1.7), (cx, cy, 1.0))
    camera(m, 'aisle', (cx - 3.4, cy - 1.45, 1.7), (cx, cy, 0.95))
    camera(m, 'desk', (cx, cy - 1.55, 2.55), (cx, cy, 0.9), 80)
    camera(m, 'wash', (cx + 4.2, cy - 1.5, 1.9), (cx + 2.9, cy, 0.95))
    camera(m, 'overview', (cx, cy - 0.01, 8.0), (cx, cy, 0.9), 60)
    materials = '\n'.join(f'<material name="{k}" {v}/>' for k,v in room.MATERIALS.items())
    meshes = '\n'.join(f'<mesh name="{n}" file="../lab_room/meshes/{n}.obj" inertia="shell"/>' for n in room.LATHES)
    meshes += '\n' + '\n'.join(m.assets)
    meshes += '\n' + '\n'.join(f'<mesh name="{name}" vertex="{room.fmt(vertices)}"/>' for name,vertices in m.bevel_meshes.values())
    root = ET.fromstring(f'<mujoco model="{stem(pattern, "lab_room_open")}"><asset>' + materials + meshes
                         + '</asset><worldbody><body name="lab_room">'
                         + '\n'.join(m.lines) + '</body></worldbody></mujoco>')
    write_xml(OUT / f'{stem(pattern, "lab_room")}.xml', root)


def build_bench():
    root = ET.Element('mujoco', model='minihannover_open')
    ET.SubElement(root, 'compiler', angle='radian', autolimits='true')
    body = ET.SubElement(ET.SubElement(root, 'worldbody'), 'body', name='minihannover', pos=room.fmt(CENTER))
    for p in bench.build(width=WIDTH):
        ET.SubElement(body, 'geom', name=p.name, type='box', pos=bench.vec(p.center),
                      size=bench.vec(p.half), density=bench.f(p.density), rgba=bench.vec(p.rgba))
    write_xml(OUT / 'bench.xml', root)


def build_scene(pattern=None):
    """Write the scene file, pointing it at this build's room."""
    root = ET.parse(SIM / 'models/minihannover_scene.xml').getroot()
    root.set('model', stem(pattern, 'minihannover_open_scene'))
    root.find('include').set('file', '../assets/minihannover_open/bench.xml')
    root.find("asset/model[@name='lab_room']").set(
        'file', f'../assets/minihannover_open/{stem(pattern, "lab_room")}.xml')
    root.find('statistic').set('center', room.fmt(CENTER + (-2.8, -0.6, 1.1)))
    root.find('statistic').set('extent', '2.4')
    root.find('visual/global').set('azimuth', '8')
    root.find('visual/global').set('elevation', '-15')
    for node in root.find('worldbody'):
        attachment = node.find('attach')
        on_desk = (attachment is not None and attachment.get('model') in {'sink', 'balance'})
        on_desk |= node.tag == 'body' and (node.get('name', '').startswith('loose_') or node.get('name') == 'wrist_camera_mount')
        if on_desk:
            pos = np.fromstring(node.get('pos', '0 0 0'), sep=' ')
            if attachment is not None and attachment.get('model') == 'balance':
                pos[1] += np.sign(pos[1]) * EDGE_SHIFT
            elif node.tag == 'body':
                # Keep loose work samples and their wrist-camera viewing pose together.
                pos[1] += np.sign(pos[1]) * EDGE_SHIFT
            node.set('pos', room.fmt(pos + CENTER))
    # The fixed wall camera already aims at the room center; retain its calibration.
    # The wrist mount moves with loose_2, preserving its barcode viewing distance.
    path = SIM / f'models/{stem(pattern, "minihannover_open_scene")}.xml'
    write_xml(path, root)
    return path


def write_index():
    """Write the catalogue index: what each of the ten seeded patterns holds."""
    PATTERNS.mkdir(parents=True, exist_ok=True)
    rows = []
    for pattern in patterns.catalogue():
        population = json.loads((PATTERNS / f'{pattern.name}.json').read_text())
        rows.append({k: v for k, v in population.items() if k != 'containers'}
                    | dict(file=f'{pattern.name}.json'))
    (PATTERNS / 'index.json').write_text(json.dumps(dict(
        note='Seeded worktop layouts; regenerate with '
             'scripts/generate_minihannover_open.py --all-patterns',
        patterns=rows), indent=2) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--pattern', metavar='NAME',
                        help='build the scene for one seeded pattern: p03, s42 or a raw seed')
    parser.add_argument('--all-patterns', action='store_true',
                        help='write the ten catalogue population files (no scene XML)')
    parser.add_argument('--list', action='store_true',
                        help='print the ten catalogue patterns and exit')
    args = parser.parse_args()

    if args.list:
        for pattern in patterns.catalogue():
            print(pattern.summary())
        return

    OUT.mkdir(parents=True, exist_ok=True)
    if args.all_patterns:
        for pattern in patterns.catalogue():
            build_population(pattern)
        write_index()
        print(f'Wrote {len(patterns.CATALOGUE)} patterns to '
              f'{PATTERNS.relative_to(SIM)}; build one with --pattern <name>')
        return

    pattern = patterns.by_name(args.pattern) if args.pattern else None
    build_room(pattern)
    build_bench()
    scene = build_scene(pattern)
    print(f'Created {scene.relative_to(SIM)}: 6 x {WIDTH:g} m desk centered at {room.fmt(CENTER)}')


if __name__ == '__main__':
    main()
