#!/usr/bin/env python3
"""The UR10e hand picking up an amber bottle, for MuJoCo and for Isaac.

Run from simulation/: python scripts/generate_hand_scene.py.
Then play it: python scripts/hand_pick.py (MuJoCo) or
scripts/hand_pick_isaac.py (Isaac Lab).

One kinematic description, two formats, the way ``assets/minihannover`` ships
MJCF and URDF side by side:

* ``assets/ur10e_hand/ur10e_hand.xml`` --- the hand as an attachable MJCF: the
  arm stub, ``wrist_3_joint`` with the flange, and the Robotiq 2F-85 from
  ``assets/robotiq_2f85_sensed/``. The same two degrees of freedom as
  ``ur10e_hand.blend``: the wrist roll and the gripper.
* ``models/hand_pick_scene.xml`` --- the MuJoCo scene: a floor, the 60 ml amber
  bottle with the white cap from ``assets/amber_bottles/`` loose on it, and the
  hand held out sideways from a two-axis carriage (``reach`` along X,
  ``lift`` along Z) so it can come to the bottle.
* ``models/hand_pick_rig.urdf`` and ``assets/amber_bottles/amber_060ml.urdf``
  --- the same carriage, hand and bottle for Isaac's URDF importer.

The one real difference between the two: the 2F-85's fingers are closed
four-bar linkages, which MuJoCo closes with ``<connect>`` equalities and a URDF
cannot express at all. The URDF opens each loop at the coupler (whose joint
stays within a milliradian of zero over the whole stroke, so it is made fixed)
and slaves every other finger joint to ``right_driver_joint`` with a ``mimic``
tag. The ratios are fitted here from MuJoCo's own solution of the linkage; the
fit has to hold to 0.01 rad over the stroke or the script stops. Only the pads
collide in the URDF, as boxes, which is also what grips in MuJoCo.

Frames: the hand is in the tool frame of the arm (origin on the flange face,
+Z the approach). The carriage holds it for a side grasp: the fingers point
along +X, tilted ``APPROACH_TILT`` below the horizontal (hand_pick_plan.py),
and open and close along world Y. The carriage's joints read in world terms:
``reach`` is the flange's world X, ``lift`` its world Z.
"""
import math

import mujoco
import numpy as np

import hand_pick_plan as plan
from hand_linkage import (GRIPPER, MATERIALS, MESH_MATERIAL, OUT_DIR,
                          RING_HEIGHT, SIM, STUB_LENGTH, STUB_RADIUS, STUB_TOP,
                          gripper_bodies, sweep_linkage, wrist3_pose)

HAND_XML = OUT_DIR / 'ur10e_hand.xml'
SCENE_XML = SIM / 'models/hand_pick_scene.xml'
RIG_URDF = SIM / 'models/hand_pick_rig.urdf'
BOTTLE_DIR = SIM / 'assets/amber_bottles'
BOTTLE = 'amber_060ml'
BOTTLE_URDF = BOTTLE_DIR / f'{BOTTLE}.urdf'

# wrist_3_link's inertial in the arm MJCF (Menagerie's ur10e.xml).
WRIST3_MASS = 0.202
WRIST3_IPOS = np.array([0.0, 0.092, 0.0])
WRIST3_IQUAT = np.array([0.0, 1.0, -1.0, 0.0]) / np.sqrt(2)
WRIST3_INERTIA = (0.000204525, 0.000144346, 0.000144346)
STUB_MASS = 1.0              # the stand-in cylinder; it rides the carriage
CARRIAGE_MASS = 1.0          # each of the reach and lift links

ACTUATED = 'right_driver_joint'
REACH_RANGE = (-0.5, 0.5)
LIFT_RANGE = (0.0, 0.6)
HOME = {'reach': plan.HOME_REACH, 'lift': plan.HOME_LIFT}
BOTTLE_POS = (*plan.BOTTLE_XY, 0.0)

HEADER = 'Generated by scripts/generate_hand_scene.py; do not edit by hand.'


def num(x) -> str:
    """A number for XML, short and without a negative zero."""
    return f'{float(x) + 0.0:.6g}'


def vec(v) -> str:
    return ' '.join(num(x) for x in v)


def rpy(quat) -> np.ndarray:
    """URDF roll-pitch-yaw (fixed X, Y, Z) of a MuJoCo (w, x, y, z) quaternion."""
    m = np.zeros(9)
    mujoco.mju_quat2Mat(m, np.asarray(quat, float) / np.linalg.norm(quat))
    r = m.reshape(3, 3)
    if abs(r[2, 0]) > 1 - 1e-9:
        # Gimbal lock, pitch straight up or down: roll and yaw are one angle;
        # put it all in roll (e.g. the tool frame turned back onto the hand).
        sign = -math.copysign(1.0, r[2, 0])
        return np.array([math.atan2(sign * r[0, 1], sign * r[0, 2]), sign * math.pi / 2, 0.0])
    return np.array([math.atan2(r[2, 1], r[2, 2]),
                     math.asin(max(-1.0, min(1.0, -r[2, 0]))),
                     math.atan2(r[1, 0], r[0, 0])])


def rotate(quat, v) -> np.ndarray:
    out = np.zeros(3)
    mujoco.mju_rotVecQuat(out, np.asarray(v, float), np.asarray(quat, float))
    return out


def hand_mount_quat() -> np.ndarray:
    """The tool frame on the carriage: approach (+Z) along +X, tilted down by
    APPROACH_TILT; the fingers' spread (+X) along world +Y."""
    a = plan.APPROACH_TILT
    x, z = np.array([0.0, 1.0, 0.0]), np.array([np.cos(a), 0.0, -np.sin(a)])
    quat = np.zeros(4)
    mujoco.mju_mat2Quat(quat, np.column_stack([x, np.cross(z, x), z]).ravel())
    return quat


def wrist3_inertial() -> tuple[np.ndarray, np.ndarray]:
    """wrist_3_link's inertial frame, moved from its link frame to the tool frame."""
    to_tool_pos, to_tool_quat = wrist3_pose()
    pos, quat = np.zeros(3), np.zeros(4)
    mujoco.mju_mulPose(pos, quat, to_tool_pos, to_tool_quat,
                       WRIST3_IPOS, WRIST3_IQUAT)
    return pos, quat


def mimic_ratios() -> dict[str, float]:
    """Each finger joint as a multiple of the actuated driver joint.

    Raises:
        RuntimeError: If a joint strays from its linear fit by more than
            0.01 rad anywhere in the stroke, or has an offset worth keeping.
    """
    _, angles = sweep_linkage()
    driver = angles[ACTUATED]
    ratios = {}
    for name, q in angles.items():
        slope, offset = np.polyfit(driver, q, 1)
        error = np.abs(np.polyval((slope, offset), driver) - q).max()
        if error > 0.01 or abs(offset) > 0.005:
            raise RuntimeError(f'{name}: not linear in {ACTUATED} '
                               f'(off by {error:.4f} rad, offset {offset:.4f})')
        ratios[name] = 0.0 if abs(slope) < 0.01 else round(float(slope), 4)
    return ratios


# --- MJCF --------------------------------------------------------------------


def write_hand_mjcf() -> None:
    wpos, wquat = wrist3_pose()
    ipos, iquat = wrist3_inertial()
    c = {k: vec(v) for k, v in MATERIALS.items()}
    HAND_XML.write_text(f'''<mujoco model="ur10e_hand">
  <!-- {HEADER} -->
  <!-- The UR10e past its last wrist joint, in the arm's tool frame: origin on
       the flange face, +Z the approach. A fixed cylinder stands in for the arm.
       Two degrees of freedom: wrist_3_joint and the 2F-85's fingers_actuator
       (ctrl 0 open .. 255 closed). -->
  <compiler angle="radian" meshdir="../../third_party/mujoco_menagerie/universal_robots_ur10e/assets" autolimits="true"/>
  <option cone="elliptic" impratio="10"/>   <!-- the 2F-85's, so its pads grip the same -->

  <asset>
    <model name="robotiq_2f85" file="../robotiq_2f85_sensed/2f85_sensed.xml"/>
    <material name="linkgray" rgba="{c['linkgray']}" specular="0.5" shininess="0.25"/>
    <material name="urblue" rgba="{c['urblue']}" specular="0.5" shininess="0.25"/>
    <mesh file="wrist3.obj"/>
  </asset>

  <worldbody>
    <body name="ur10e_hand">
      <inertial pos="0 0 {num(STUB_TOP - STUB_LENGTH / 2)}" mass="{num(STUB_MASS)}" diaginertia="0.002 0.002 0.001"/>
      <geom name="arm_stub_housing" type="cylinder" size="{num(STUB_RADIUS)} {num(STUB_LENGTH / 2)}"
            pos="0 0 {num(STUB_TOP - STUB_LENGTH / 2)}" material="linkgray" contype="0" conaffinity="0" group="2" mass="0"/>
      <geom name="arm_stub_ring" type="cylinder" size="{num(STUB_RADIUS + 0.001)} {num(RING_HEIGHT / 2)}"
            pos="0 0 {num(STUB_TOP - RING_HEIGHT / 2)}" material="urblue" contype="0" conaffinity="0" group="2" mass="0"/>
      <body name="wrist_3_link">
        <inertial pos="{vec(ipos)}" quat="{vec(iquat)}" mass="{num(WRIST3_MASS)}" diaginertia="{vec(WRIST3_INERTIA)}"/>
        <joint name="wrist_3_joint" type="hinge" axis="0 0 1" range="-6.28319 6.28319" armature="0.1" damping="2"/>
        <geom name="wrist_3_visual" type="mesh" mesh="wrist3" pos="{vec(wpos)}" quat="{vec(wquat)}"
              material="linkgray" contype="0" conaffinity="0" group="2"/>
        <site name="tool" size="0.004" rgba="0.9 0.3 0.1 0.5" group="4"/>
        <attach model="robotiq_2f85" body="base_mount" prefix=""/>
      </body>
    </body>
  </worldbody>

  <actuator>
    <general name="wrist_3" joint="wrist_3_joint" biastype="affine" gainprm="500" biasprm="0 -500 -50"
             ctrlrange="-6.2831 6.2831" forcerange="-56 56"/>
  </actuator>
</mujoco>
''')


def write_scene_mjcf() -> None:
    lo_r, hi_r = REACH_RANGE
    lo_l, hi_l = LIFT_RANGE
    SCENE_XML.write_text(f'''<mujoco model="hand_pick_scene">
  <!-- {HEADER} -->
  <!-- The UR10e hand comes to a 60 ml amber bottle, picks it up and sets it
       down again: python scripts/hand_pick.py. The carriage's joints read in
       world terms: reach = flange X, lift = flange Z. The hand points along +X,
       tilted down {num(np.degrees(plan.APPROACH_TILT))} deg, and grips sideways. -->
  <compiler angle="radian" autolimits="true"/>
  <option integrator="implicitfast" timestep="0.002" cone="elliptic" impratio="10"/>
  <statistic center="-0.15 0 0.1" extent="0.5"/>
  <visual>
    <headlight diffuse="0.5 0.5 0.5" ambient="0.3 0.3 0.3" specular="0.1 0.1 0.1"/>
    <global azimuth="135" elevation="-20" offwidth="1280" offheight="720"/>
    <quality shadowsize="4096"/>
  </visual>

  <asset>
    <model name="ur10e_hand" file="../assets/ur10e_hand/ur10e_hand.xml"/>
    <model name="{BOTTLE}" file="../assets/amber_bottles/{BOTTLE}.xml"/>
    <texture name="grid" type="2d" builtin="checker" rgb1="0.86 0.87 0.88" rgb2="0.8 0.81 0.82" width="512" height="512"/>
    <material name="floor" texture="grid" texrepeat="8 8" reflectance="0.1"/>
    <material name="carriage" rgba="0.3 0.32 0.35 1"/>
  </asset>

  <worldbody>
    <light name="key" pos="0.4 -0.6 1.2" dir="-0.3 0.5 -1" diffuse="0.7 0.7 0.7" castshadow="true"/>
    <geom name="floor" type="plane" size="1 1 0.05" material="floor"/>
    <camera name="side" pos="0.05 -0.65 0.28" xyaxes="0.956 0.294 0 -0.083 0.27 0.959"/>

    <body name="reach_link" gravcomp="1">
      <inertial pos="0 0 0" mass="{num(CARRIAGE_MASS)}" diaginertia="0.01 0.01 0.01"/>
      <joint name="reach" type="slide" axis="1 0 0" range="{num(lo_r)} {num(hi_r)}" damping="40" armature="1"/>
      <body name="lift_link" gravcomp="1">
        <inertial pos="0 0 0" mass="{num(CARRIAGE_MASS)}" diaginertia="0.01 0.01 0.01"/>
        <joint name="lift" type="slide" axis="0 0 1" range="{num(lo_l)} {num(hi_l)}" damping="40" armature="1"/>
        <frame quat="{vec(hand_mount_quat())}">
          <attach model="ur10e_hand" body="ur10e_hand" prefix=""/>
        </frame>
      </body>
    </body>

    <body name="bottle" pos="{vec(BOTTLE_POS)}">
      <freejoint name="bottle"/>
      <attach model="{BOTTLE}" body="{BOTTLE}" prefix="bottle_"/>
    </body>
  </worldbody>

  <actuator>
    <position name="reach" joint="reach" kp="10000" kv="800" ctrlrange="{num(lo_r)} {num(hi_r)}" forcerange="-200 200"/>
    <position name="lift" joint="lift" kp="10000" kv="800" ctrlrange="{num(lo_l)} {num(hi_l)}" forcerange="-200 200"/>
  </actuator>

  <keyframe>
    <key name="home" qpos="{num(HOME['reach'])} {num(HOME['lift'])} {' '.join(['0'] * 9)} {vec(BOTTLE_POS)} 1 0 0 0"
         ctrl="{num(HOME['reach'])} {num(HOME['lift'])} 0 0"/>
  </keyframe>
</mujoco>
''')


# --- URDF --------------------------------------------------------------------


def inertial_xml(mass, pos, quat, diag, indent='    ') -> str:
    mass = max(float(mass), 1e-3)
    diag = [max(float(d), 1e-7) for d in diag]
    return (f'{indent}<inertial>\n'
            f'{indent}  <origin xyz="{vec(pos)}" rpy="{vec(rpy(quat))}"/>\n'
            f'{indent}  <mass value="{num(mass)}"/>\n'
            f'{indent}  <inertia ixx="{num(diag[0])}" ixy="0" ixz="0" iyy="{num(diag[1])}"'
            f' iyz="0" izz="{num(diag[2])}"/>\n'
            f'{indent}</inertial>\n')


def mesh_visual(filename, material, pos=(0, 0, 0), quat=(1, 0, 0, 0), scale=1.0) -> str:
    return ('    <visual>\n'
            f'      <origin xyz="{vec(pos)}" rpy="{vec(rpy(quat))}"/>\n'
            f'      <geometry><mesh filename="{filename}" scale="{vec([scale] * 3)}"/></geometry>\n'
            f'      <material name="{material}"/>\n'
            '    </visual>\n')


def joint_xml(name, kind, parent, child, pos=(0, 0, 0), quat=(1, 0, 0, 0), axis=None,
              limit=None, effort=100.0, velocity=1.0, mimic=None) -> str:
    out = (f'  <joint name="{name}" type="{kind}">\n'
           f'    <parent link="{parent}"/>\n    <child link="{child}"/>\n'
           f'    <origin xyz="{vec(pos)}" rpy="{vec(rpy(quat))}"/>\n')
    if axis is not None:
        out += f'    <axis xyz="{vec(axis)}"/>\n'
    if limit is not None:
        out += (f'    <limit lower="{num(limit[0])}" upper="{num(limit[1])}"'
                f' effort="{num(effort)}" velocity="{num(velocity)}"/>\n')
    if mimic is not None:
        out += f'    <mimic joint="{mimic[0]}" multiplier="{num(mimic[1])}" offset="0"/>\n'
    return out + '  </joint>\n'


def gripper_urdf(model, ratios: dict[str, float], parent: str, links: list[str], joints: list[str]) -> None:
    """Append the 2F-85 to a URDF, body by body, hanging off `parent`.

    A link frame sits on its joint's axis, so a body whose joint is off its
    origin (the followers) is shifted by jpos. Every finger joint mimics
    ACTUATED with its fitted ratio; the couplers, which the linkage keeps at
    zero, are fixed. Only the pad boxes collide.
    """
    grip_dir = '../third_party/mujoco_menagerie/robotiq_2f85/assets'
    names = {0: parent}
    shift = {0: np.zeros(3)}
    for b, name, parent_id, pos, quat, joint, jpos, meshes in gripper_bodies(model):
        names[b], shift[b] = name, jpos
        origin = pos + rotate(quat, jpos) - shift[parent_id]
        body = ''.join(mesh_visual(f'{grip_dir}/{m}.stl', MESH_MATERIAL[m], -jpos, scale=0.001)
                       for m in meshes)
        for g in range(model.body_geomadr[b], model.body_geomadr[b] + model.body_geomnum[b]):
            if model.geom_type[g] == mujoco.mjtGeom.mjGEOM_BOX:
                body += ('    <collision>\n'
                         f'      <origin xyz="{vec(model.geom_pos[g] - jpos)}" rpy="{vec(rpy(model.geom_quat[g]))}"/>\n'
                         f'      <geometry><box size="{vec(2 * model.geom_size[g])}"/></geometry>\n'
                         '    </collision>\n')
        inertial = inertial_xml(model.body_mass[b], model.body_ipos[b] - jpos,
                                model.body_iquat[b], model.body_inertia[b])
        links.append(f'  <link name="{name}">\n{inertial}{body}  </link>\n')
        if joint is None or ratios.get(joint) == 0.0:
            # No joint, or one the linkage keeps at zero (the couplers).
            joints.append(joint_xml(joint or f'{name}_mount', 'fixed', names[parent_id], name,
                                    origin, quat))
            continue
        limit = model.jnt_range[model.joint(joint).id]
        mimic = None if joint == ACTUATED else (ACTUATED, ratios[joint])
        joints.append(joint_xml(joint, 'revolute', names[parent_id], name, origin, quat,
                                axis=(1, 0, 0), limit=limit, effort=5, velocity=2,
                                mimic=mimic))


def write_rig_urdf(ratios: dict[str, float]) -> None:
    """Carriage + hand as one fixed-base articulation for Isaac's URDF importer."""
    model = mujoco.MjModel.from_xml_path(str(GRIPPER))
    ur_dir = '../third_party/mujoco_menagerie/universal_robots_ur10e/assets'
    materials = ''.join(f'  <material name="{k}"><color rgba="{vec(v)}"/></material>\n'
                        for k, v in {**MATERIALS, 'carriage': (0.3, 0.32, 0.35, 1)}.items())
    links, joints = [], []

    def link(name, body='', extra_inertial=None):
        inertial = extra_inertial or inertial_xml(1e-3, (0, 0, 0), (1, 0, 0, 0), (1e-7,) * 3)
        links.append(f'  <link name="{name}">\n{inertial}{body}  </link>\n')

    # The carriage: world X, then world Z, then the hand's side-grasp tilt.
    link('rig_base')
    link('reach_link', extra_inertial=inertial_xml(CARRIAGE_MASS, (0, 0, 0), (1, 0, 0, 0), (0.01,) * 3))
    link('lift_link', extra_inertial=inertial_xml(CARRIAGE_MASS, (0, 0, 0), (1, 0, 0, 0), (0.01,) * 3))
    joints.append(joint_xml('reach', 'prismatic', 'rig_base', 'reach_link', axis=(1, 0, 0),
                            limit=REACH_RANGE, effort=200, velocity=0.5))
    joints.append(joint_xml('lift', 'prismatic', 'reach_link', 'lift_link', axis=(0, 0, 1),
                            limit=LIFT_RANGE, effort=200, velocity=0.5))

    stub_z = STUB_TOP - STUB_LENGTH / 2
    stub = ('    <visual>\n'
            f'      <origin xyz="0 0 {num(stub_z)}" rpy="0 0 0"/>\n'
            f'      <geometry><cylinder radius="{num(STUB_RADIUS)}" length="{num(STUB_LENGTH)}"/></geometry>\n'
            '      <material name="linkgray"/>\n'
            '    </visual>\n'
            '    <visual>\n'
            f'      <origin xyz="0 0 {num(STUB_TOP - RING_HEIGHT / 2)}" rpy="0 0 0"/>\n'
            f'      <geometry><cylinder radius="{num(STUB_RADIUS + 0.001)}" length="{num(RING_HEIGHT)}"/></geometry>\n'
            '      <material name="urblue"/>\n'
            '    </visual>\n')
    link('ur10e_hand', stub, inertial_xml(STUB_MASS, (0, 0, stub_z), (1, 0, 0, 0), (0.002, 0.002, 0.001)))
    joints.append(joint_xml('hand_mount', 'fixed', 'lift_link', 'ur10e_hand',
                            quat=hand_mount_quat()))

    wpos, wquat = wrist3_pose()
    ipos, iquat = wrist3_inertial()
    link('wrist_3_link', mesh_visual(f'{ur_dir}/wrist3.obj', 'linkgray', wpos, wquat),
         inertial_xml(WRIST3_MASS, ipos, iquat, WRIST3_INERTIA))
    joints.append(joint_xml('wrist_3_joint', 'revolute', 'ur10e_hand', 'wrist_3_link',
                            axis=(0, 0, 1), limit=(-2 * math.pi, 2 * math.pi), effort=56,
                            velocity=3.14))

    gripper_urdf(model, ratios, 'wrist_3_link', links, joints)

    RIG_URDF.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- {HEADER} -->\n'
        '<!-- The UR10e hand on a two-axis carriage, for Isaac\'s URDF importer (fix the\n'
        f'     base). The 2F-85 is actuated at {ACTUATED} (0 open .. 0.8 closed); every\n'
        '     other finger joint mimics it, and the couplers are fixed. See the generator. -->\n'
        '<robot name="hand_pick_rig">\n'
        '  <!-- Hints for MuJoCo\'s URDF loader; ignored by every other importer. -->\n'
        '  <mujoco>\n'
        '    <compiler discardvisual="false" fusestatic="false"/>\n'
        '  </mujoco>\n\n'
        f'{materials}\n' + ''.join(links) + '\n' + ''.join(joints) + '</robot>\n')


def write_bottle_urdf() -> None:
    """The amber bottle as a free rigid body, mass and inertia as MuJoCo has them."""
    spec = mujoco.MjSpec.from_file(str(BOTTLE_DIR / f'{BOTTLE}.xml'))
    spec.body(BOTTLE).add_freejoint()
    model = spec.compile()
    b = model.body(BOTTLE).id
    body = ''
    for g in range(model.body_geomadr[b], model.body_geomadr[b] + model.body_geomnum[b]):
        mesh = model.mesh(model.geom_dataid[g]).name
        material = f'{BOTTLE}_{g}'
        body += (f'    <visual>\n'
                 f'      <geometry><mesh filename="{mesh}.obj"/></geometry>\n'
                 f'      <material name="{material}"><color rgba="{vec(model.geom_rgba[g])}"/></material>\n'
                 f'    </visual>\n'
                 f'    <collision>\n'
                 f'      <geometry><mesh filename="{mesh}.obj"/></geometry>\n'
                 f'    </collision>\n')
    BOTTLE_URDF.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- {HEADER} -->\n'
        f'<!-- {BOTTLE}.xml as a URDF: one free rigid body, origin bottom-centre, +Z up.\n'
        '     The meshes collide as convex hulls, as in MuJoCo. -->\n'
        f'<robot name="{BOTTLE}">\n'
        f'  <link name="{BOTTLE}">\n'
        + inertial_xml(model.body_mass[b], model.body_ipos[b], model.body_iquat[b],
                       model.body_inertia[b])
        + body + '  </link>\n</robot>\n')


def main() -> None:
    ratios = mimic_ratios()
    for name, ratio in ratios.items():
        print(f'  {name}: {ratio:+.4f} x {ACTUATED}')
    write_hand_mjcf()
    write_scene_mjcf()
    write_rig_urdf(ratios)
    write_bottle_urdf()
    for path in (HAND_XML, SCENE_XML, RIG_URDF, BOTTLE_URDF):
        mujoco.MjModel.from_xml_path(str(path))   # every file must at least load
        print(f'wrote {path.relative_to(SIM)}')


if __name__ == '__main__':
    main()
