#!/usr/bin/env python3
"""Generate the `minihannover` lab bench assets.

This is the single source of truth for the bench: edit the constants below and
re-run to regenerate the interchange mesh (OBJ/MTL), the MuJoCo models (MJCF)
and the URDF used by the Isaac Lab importer, so the three stay in sync.

    python scripts/generate_minihannover.py

Everything is written to assets/minihannover/. Frame convention (shared by all
outputs): origin on the floor, centred in X/Y, +X along the length, +Z up.
"""

from __future__ import annotations

import pathlib

NAME = "minihannover"

# --- Geometry (metres) ------------------------------------------------------
LENGTH = 6.0          # worktop extent along X
WIDTH = 1.5           # worktop extent along Y
HEIGHT = 0.90         # height of the work surface above the floor
TOP_THICKNESS = 0.05  # worktop slab thickness
LEG_SIZE = 0.10       # square leg cross-section
LEG_INSET = 0.10      # gap between the bench edge and the outer face of a leg
LEG_PAIRS = 3         # leg pairs along X; a 6 m worktop needs a mid support

# --- Materials --------------------------------------------------------------
TOP_DENSITY = 700.0   # laminated worktop (kg/m^3)
LEG_DENSITY = 800.0   # hollow steel legs, approximated as solid (kg/m^3)
TOP_RGBA = (0.78, 0.80, 0.82, 1.0)
LEG_RGBA = (0.20, 0.22, 0.25, 1.0)

OUT = pathlib.Path(__file__).resolve().parent.parent / "assets" / NAME


class Box:
    """An axis-aligned box: the bench is built entirely out of these."""

    def __init__(self, name, center, half, density, rgba, material):
        self.name = name
        self.center = center
        self.half = half
        self.density = density
        self.rgba = rgba
        self.material = material

    @property
    def mass(self):
        hx, hy, hz = self.half
        return 8.0 * hx * hy * hz * self.density


def build(width=WIDTH):
    parts = [
        Box(
            f"{NAME}_worktop",
            (0.0, 0.0, HEIGHT - TOP_THICKNESS / 2),
            (LENGTH / 2, width / 2, TOP_THICKNESS / 2),
            TOP_DENSITY,
            TOP_RGBA,
            f"{NAME}_top",
        )
    ]

    leg_h = HEIGHT - TOP_THICKNESS
    dx = LENGTH / 2 - LEG_INSET - LEG_SIZE / 2
    dy = width / 2 - LEG_INSET - LEG_SIZE / 2
    xs = [-dx + 2 * dx * i / (LEG_PAIRS - 1) for i in range(LEG_PAIRS)] if LEG_PAIRS > 1 else [0.0]

    for i, x in enumerate(xs):
        for side, y in (("y0", -dy), ("y1", dy)):
            parts.append(
                Box(
                    f"{NAME}_leg_x{i}_{side}",
                    (x, y, leg_h / 2),
                    (LEG_SIZE / 2, LEG_SIZE / 2, leg_h / 2),
                    LEG_DENSITY,
                    LEG_RGBA,
                    f"{NAME}_frame",
                )
            )
    return parts


def inertial(parts):
    """Total mass, centre of mass and inertia tensor about the COM."""
    mass = sum(p.mass for p in parts)
    com = [sum(p.mass * p.center[k] for p in parts) / mass for k in range(3)]

    ixx = iyy = izz = ixy = ixz = iyz = 0.0
    for p in parts:
        m = p.mass
        hx, hy, hz = p.half
        dx, dy, dz = (p.center[k] - com[k] for k in range(3))
        ixx += m / 3.0 * (hy * hy + hz * hz) + m * (dy * dy + dz * dz)
        iyy += m / 3.0 * (hx * hx + hz * hz) + m * (dx * dx + dz * dz)
        izz += m / 3.0 * (hx * hx + hy * hy) + m * (dx * dx + dy * dy)
        ixy -= m * dx * dy
        ixz -= m * dx * dz
        iyz -= m * dy * dz
    return mass, com, (ixx, iyy, izz, ixy, ixz, iyz)


def f(x):
    """Compact fixed-point formatting; keeps the generated files diffable."""
    return f"{x:.6f}".rstrip("0").rstrip(".") or "0"


def vec(v):
    return " ".join(f(x) for x in v)


# --- OBJ / MTL --------------------------------------------------------------

_FACES = (  # (vertex indices into the 8 corners, normal index)
    ((0, 1, 3, 2), 0), ((4, 6, 7, 5), 1),   # -X, +X
    ((0, 4, 5, 1), 2), ((2, 3, 7, 6), 3),   # -Y, +Y
    ((0, 2, 6, 4), 4), ((1, 5, 7, 3), 5),   # -Z, +Z
)
_NORMALS = ((-1, 0, 0), (1, 0, 0), (0, -1, 0), (0, 1, 0), (0, 0, -1), (0, 0, 1))


def write_obj(parts):
    lines = [
        f"# {NAME} — lab bench, {f(LENGTH)} x {f(WIDTH)} x {f(HEIGHT)} m",
        "# Generated by scripts/generate_minihannover.py — do not edit by hand.",
        "# Units: metres. Origin on the floor, centred in X/Y, +Z up.",
        f"mtllib {NAME}.mtl",
        f"o {NAME}",
    ]
    verts, norms, faces = [], [], []

    for p in parts:
        base = len(verts) + 1
        cx, cy, cz = p.center
        hx, hy, hz = p.half
        for sx in (-1, 1):
            for sy in (-1, 1):
                for sz in (-1, 1):
                    verts.append((cx + sx * hx, cy + sy * hy, cz + sz * hz))
        # Corner order above is (x, y, z) major-to-minor, matching _FACES.
        nbase = len(norms) + 1
        norms.extend(_NORMALS)
        for quad, ni in _FACES:
            a, b, c, d = (base + i for i in quad)
            n = nbase + ni
            faces.append((p.material, (a, b, c), n))
            faces.append((p.material, (a, c, d), n))

    for v in verts:
        lines.append(f"v {vec(v)}")
    for n in norms:
        lines.append(f"vn {vec(n)}")

    current = None
    for material, tri, n in faces:
        if material != current:
            lines.append(f"usemtl {material}")
            current = material
        lines.append("f " + " ".join(f"{i}//{n}" for i in tri))

    (OUT / f"{NAME}.obj").write_text("\n".join(lines) + "\n")


def write_mtl():
    def block(name, rgba):
        r, g, b, _ = rgba
        return (
            f"newmtl {name}\n"
            f"Kd {f(r)} {f(g)} {f(b)}\n"
            f"Ka 0 0 0\n"
            f"Ks 0.2 0.2 0.2\n"
            f"Ns 40\n"
            f"d 1\n"
            f"illum 2\n"
        )

    (OUT / f"{NAME}.mtl").write_text(
        "# Generated by scripts/generate_minihannover.py — do not edit by hand.\n"
        + block(f"{NAME}_top", TOP_RGBA)
        + "\n"
        + block(f"{NAME}_frame", LEG_RGBA)
    )


# --- MJCF -------------------------------------------------------------------

_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_minihannover.py - do not edit by hand. -->
"""


def write_mjcf_primitives(parts):
    """Box-only model: no external files, so it loads and `<include>`s anywhere."""
    geoms = "\n".join(
        f'      <geom name="{p.name}" type="box" pos="{vec(p.center)}" size="{vec(p.half)}"'
        f' density="{f(p.density)}" rgba="{vec(p.rgba)}"/>'
        for p in parts
    )
    (OUT / f"{NAME}.xml").write_text(
        _HEADER
        + f'<mujoco model="{NAME}">\n'
        "  <compiler angle=\"radian\" autolimits=\"true\"/>\n\n"
        "  <worldbody>\n"
        f'    <body name="{NAME}" pos="0 0 0">\n'
        "      <!-- No joint: the bench is welded to the world. Add <freejoint/>\n"
        "           here to make it a movable rigid body. -->\n"
        f"{geoms}\n"
        "    </body>\n"
        "  </worldbody>\n"
        "</mujoco>\n"
    )


def write_mjcf_mesh(parts):
    """Mesh visual + box collision: the usual MuJoCo split, and it exercises the OBJ."""
    geoms = "\n".join(
        f'      <geom name="{p.name}" class="{NAME}_collision" pos="{vec(p.center)}"'
        f' size="{vec(p.half)}" density="{f(p.density)}"/>'
        for p in parts
    )
    (OUT / f"{NAME}_mesh.xml").write_text(
        _HEADER
        + f'<mujoco model="{NAME}_mesh">\n'
        '  <compiler angle="radian" autolimits="true" meshdir="."/>\n\n'
        "  <asset>\n"
        f'    <mesh name="{NAME}_mesh" file="{NAME}.obj"/>\n'
        f'    <material name="{NAME}_top" rgba="{vec(TOP_RGBA)}" specular="0.2" shininess="0.3"/>\n'
        "  </asset>\n\n"
        "  <default>\n"
        f'    <default class="{NAME}_collision">\n'
        '      <geom type="box" group="3" contype="1" conaffinity="1"/>\n'
        "    </default>\n"
        "  </default>\n\n"
        "  <worldbody>\n"
        f'    <body name="{NAME}" pos="0 0 0">\n'
        f'      <geom name="{NAME}_visual" type="mesh" mesh="{NAME}_mesh"'
        f' material="{NAME}_top" contype="0" conaffinity="0" group="0" density="0"/>\n'
        f"{geoms}\n"
        "    </body>\n"
        "  </worldbody>\n"
        "</mujoco>\n"
    )


# --- URDF -------------------------------------------------------------------


def write_urdf(parts):
    mass, com, (ixx, iyy, izz, ixy, ixz, iyz) = inertial(parts)
    collisions = "\n".join(
        "    <collision>\n"
        f'      <origin xyz="{vec(p.center)}" rpy="0 0 0"/>\n'
        f'      <geometry><box size="{vec([2 * h for h in p.half])}"/></geometry>\n'
        "    </collision>"
        for p in parts
    )
    (OUT / f"{NAME}.urdf").write_text(
        _HEADER
        + f'<robot name="{NAME}">\n'
        "  <!-- Hints for MuJoCo's URDF loader; ignored by every other importer. -->\n"
        "  <mujoco>\n"
        '    <compiler meshdir="." balanceinertia="true" discardvisual="false"/>\n'
        "  </mujoco>\n\n"
        '  <material name="{0}_top">\n'
        '    <color rgba="{1}"/>\n'
        "  </material>\n\n".format(NAME, vec(TOP_RGBA))
        + '  <link name="base_link">\n'
        "    <inertial>\n"
        f'      <origin xyz="{vec(com)}" rpy="0 0 0"/>\n'
        f'      <mass value="{f(mass)}"/>\n'
        f'      <inertia ixx="{f(ixx)}" ixy="{f(ixy)}" ixz="{f(ixz)}"'
        f' iyy="{f(iyy)}" iyz="{f(iyz)}" izz="{f(izz)}"/>\n'
        "    </inertial>\n"
        "    <visual>\n"
        '      <origin xyz="0 0 0" rpy="0 0 0"/>\n'
        f'      <geometry><mesh filename="{NAME}.obj" scale="1 1 1"/></geometry>\n'
        f'      <material name="{NAME}_top"/>\n'
        "    </visual>\n"
        f"{collisions}\n"
        "  </link>\n"
        "</robot>\n"
    )


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    parts = build()
    write_obj(parts)
    write_mtl()
    write_mjcf_primitives(parts)
    write_mjcf_mesh(parts)
    write_urdf(parts)

    mass, com, _ = inertial(parts)
    print(f"{NAME}: {LENGTH} x {WIDTH} m worktop, {HEIGHT} m high, {len(parts)} boxes")
    print(f"  mass {mass:.1f} kg, com ({com[0]:.3f}, {com[1]:.3f}, {com[2]:.3f})")
    for path in sorted(OUT.iterdir()):
        print(f"  {path.relative_to(OUT.parent.parent)}")


if __name__ == "__main__":
    main()
