#!/usr/bin/env python3
"""Put a UR10e on an overhead linear rail above the shelf-free MiniHannover bench.

Run from simulation/: python scripts/generate_rail_scene.py.
Needs the Menagerie models first: bash scripts/fetch_menagerie.sh.

Writes two generated files:

* ``assets/ur10e_2f85/ur10e_2f85.xml`` --- Menagerie's UR10e with a Robotiq
  2F-85 attached at its wrist flange. MJCF cannot attach a child model to a
  *site* of an already-attached model, so the gripper has to be spliced into a
  copy of the arm rather than added from the scene file.
* ``models/minihannover_rail_scene.xml`` --- the open scene plus the gantry:
  two end posts, a beam along the bench, and a carriage on a slide joint that
  carries the arm.

Why a rail at all: the UR10e reaches 1.30 m, the widest in Menagerie, and the
bench is 6 x 2 m. One static base covers a 1.30 m disc, about a third of the
worktop; a base that slides along the 6 m axis covers all of it.

Why the rail sits where it does, all measured off the open scene:

* ``RAIL_Y`` at the back edge strip. The wall camera looks at the bench from
  -Y, so a gantry behind the glassware hides the back edge instead of the
  bottles. Everything the arm has to pick lives in y = -0.83 .. 0.03.
* ``BEAM_BOTTOM`` clears 1.30 m, the top of the two analytical balances that
  stand on that strip, by 60 mm.
* The arm base ends up 0.55 m above the worktop, about the height
  its own gripper works at, so the full 1.30 m stays available horizontally
  instead of being spent on the drop to the bench.
"""
import re
import xml.etree.ElementTree as ET
from pathlib import Path

SIM = Path(__file__).resolve().parents[1]
MENAGERIE = SIM / 'third_party/mujoco_menagerie'
ARM_DIR = SIM / 'assets/ur10e_2f85'
BASE_SCENE = 'minihannover_open_scene.xml'
OUT_SCENE = SIM / 'models/minihannover_rail_scene.xml'
HEADER = '<!-- Generated by scripts/generate_rail_scene.py; do not edit by hand. -->\n'

# Bench, from assets/minihannover_open/bench.xml: 6 x 2 m worktop, top at 0.90.
BENCH_X = (-4.5, 1.5)
BENCH_Y = (-1.4, 0.6)
BENCH_TOP = 0.90

RAIL_Y = 0.30          # rail axis, on the back edge strip
BEAM_BOTTOM = 1.36     # underside of the beam; balances on that strip top out at 1.30
BEAM_HALF_Z = 0.04
BEAM_HALF_Y = 0.06
BEAM_OVERHANG = 0.40   # beam sticks out past each end of the bench
POST_HALF = 0.06
CARRIAGE_HALF = (0.16, 0.20, 0.05)
CARRIAGE_Y = 0.14      # carriage hangs off the bench side of the beam
ARM_BASE_DZ = 0.05     # arm base sits on the top face of the carriage plate

BEAM_Z = BEAM_BOTTOM + BEAM_HALF_Z
BEAM_HALF_X = (BENCH_X[1] - BENCH_X[0]) / 2 + BEAM_OVERHANG
BEAM_X = (BENCH_X[0] + BENCH_X[1]) / 2
POST_X = BEAM_HALF_X - POST_HALF - 0.02
# Travel: the carriage can stand over any point of the worktop and a little past
# each end, stopping short of the posts.
TRAVEL = BEAM_HALF_X - POST_HALF * 2 - CARRIAGE_HALF[0] - 0.08
ARM_BASE_Z = BEAM_Z + ARM_BASE_DZ

# Scan pose: hand pointing straight down, wrist about 0.45 m below the base, the
# arm folded toward -Y so it leans over the bench rather than the back wall.
SCAN_POSE = (-1.5708, -1.9199, 2.0944, -1.7453, -1.5708, 0.0)


def build_arm() -> Path:
    """Write the UR10e + Robotiq 2F-85 model used by the scene.

    Returns:
        Path of the generated arm MJCF.

    Raises:
        FileNotFoundError: If the Menagerie models have not been fetched.
    """
    source = MENAGERIE / 'universal_robots_ur10e/ur10e.xml'
    if not source.exists():
        raise FileNotFoundError(
            f'{source} missing --- run: bash scripts/fetch_menagerie.sh')

    xml = source.read_text()
    rel = '../../third_party/mujoco_menagerie'
    xml = xml.replace('meshdir="assets"',
                      f'meshdir="{rel}/universal_robots_ur10e/assets"')
    xml = xml.replace(
        '<asset>',
        f'<asset>\n    <model name="robotiq_2f85" file="{rel}/robotiq_2f85/2f85.xml"/>',
        1)
    # The flange site is where UR documents the tool frame; put the gripper on it,
    # and an eye-in-hand camera beside it looking down the same approach axis.
    # A MuJoCo camera looks along its own -Z, hence the 180-degree flip.
    xml = xml.replace(
        '<site name="attachment_site" pos="0 0.1 0" quat="-1 1 0 0"/>',
        '<site name="attachment_site" pos="0 0.1 0" quat="-1 1 0 0"/>\n'
        '                  <frame pos="0 0.1 0" quat="-1 1 0 0">\n'
        '                    <attach model="robotiq_2f85" body="base_mount" prefix="grip_"/>\n'
        '                    <camera name="eih" pos="0.105 0 -0.02"\n'
        '                            xyaxes="0 1 0 0.874 0 0.486"\n'
        '                            fovy="60.44" resolution="1920 1080"/>\n'
        '                  </frame>')
    # The arm's own keyframe no longer matches nq once the gripper is on, and the
    # scene sets poses from Python anyway.
    xml = re.sub(r'\n  <keyframe>.*?</keyframe>', '', xml, flags=re.DOTALL)
    xml = xml.replace('<mujoco model="ur10e">',
                      '<mujoco model="ur10e_2f85">\n  ' + HEADER.strip())

    ARM_DIR.mkdir(parents=True, exist_ok=True)
    out = ARM_DIR / 'ur10e_2f85.xml'
    out.write_text(xml)
    return out


def build_scene() -> Path:
    """Write the rail scene: the open bench scene plus the gantry and the arm.

    The base scene is spliced in rather than ``<include>``d: MuJoCo resolves the
    asset paths of an included file against the *including* file's directory,
    which breaks the ``../assets/...`` references. Both files sit in models/, so
    copying the tree over keeps every path valid.

    Returns:
        Path of the generated scene MJCF.
    """
    tree = ET.parse(SIM / 'models' / BASE_SCENE)
    root = tree.getroot()
    root.set('model', 'minihannover_rail_scene')

    # The gripper wants elliptic friction cones, the arm wants implicitfast.
    ET.SubElement(root, 'option', integrator='implicitfast', impratio='10',
                  cone='elliptic')

    asset = root.find('asset')
    ET.SubElement(asset, 'material', name='gantry', rgba='0.42 0.44 0.48 1',
                  specular='0.4', shininess='0.5')
    ET.SubElement(asset, 'material', name='carriage', rgba='0.22 0.24 0.28 1',
                  specular='0.5', shininess='0.6')
    ET.SubElement(asset, 'model', name='ur10e_2f85',
                  file='../assets/ur10e_2f85/ur10e_2f85.xml')

    world = root.find('worldbody')
    post_z = BEAM_BOTTOM / 2
    rail = ET.SubElement(world, 'body', name='rail')
    for side, x in (('left', BEAM_X - POST_X), ('right', BEAM_X + POST_X)):
        ET.SubElement(rail, 'geom', name=f'rail_post_{side}', type='box',
                      material='gantry', pos=f'{x:.3f} {RAIL_Y} {post_z:.3f}',
                      size=f'{POST_HALF} {POST_HALF} {post_z:.3f}')
    ET.SubElement(rail, 'geom', name='rail_beam', type='box', material='gantry',
                  pos=f'{BEAM_X} {RAIL_Y} {BEAM_Z:.3f}',
                  size=f'{BEAM_HALF_X:.3f} {BEAM_HALF_Y} {BEAM_HALF_Z}')

    carriage = ET.SubElement(world, 'body', name='rail_carriage',
                             pos=f'{BEAM_X} {CARRIAGE_Y} {BEAM_Z:.3f}')
    ET.SubElement(carriage, 'joint', name='rail_x', type='slide', axis='1 0 0',
                  range=f'{-TRAVEL:.3f} {TRAVEL:.3f}', damping='200',
                  armature='20')
    ET.SubElement(carriage, 'geom', name='rail_carriage_plate', type='box',
                  material='carriage', mass='40', contype='0', conaffinity='0',
                  size=' '.join(str(h) for h in CARRIAGE_HALF))
    frame = ET.SubElement(carriage, 'frame', pos=f'0 0 {ARM_BASE_DZ}')
    ET.SubElement(frame, 'attach', model='ur10e_2f85', body='base',
                  prefix='arm_')
    # Rides with the arm, looking down the bench from behind the carriage.
    ET.SubElement(carriage, 'camera', name='carriage', pos='0 -0.9 0.75',
                  xyaxes='1 0 0 0 0.6 0.8', fovy='60.44',
                  resolution='1920 1080')

    actuator = ET.SubElement(root, 'actuator')
    ET.SubElement(actuator, 'position', name='rail_x', joint='rail_x',
                  kp='60000', kv='6000', forcerange='-4000 4000',
                  ctrlrange=f'{-TRAVEL:.3f} {TRAVEL:.3f}')

    keyframe = ET.SubElement(root, 'keyframe')
    pose = ' '.join(f'{q:.4f}' for q in SCAN_POSE)
    ET.SubElement(keyframe, 'key', name='scan', ctrl=f'0 {pose} 0')

    ET.indent(root, space='  ')
    OUT_SCENE.write_text('<?xml version="1.0" encoding="utf-8"?>\n' + HEADER
                         + ET.tostring(root, encoding='unicode') + '\n')
    return OUT_SCENE


def main() -> None:
    arm = build_arm()
    scene = build_scene()
    print(f'wrote {arm.relative_to(SIM)}')
    print(f'wrote {scene.relative_to(SIM)}')
    print(f'rail: y={RAIL_Y} m, beam underside {BEAM_BOTTOM} m, '
          f'arm base {ARM_BASE_Z:.3f} m ({ARM_BASE_Z - BENCH_TOP:.2f} m over the worktop)')
    print(f'travel: x = {BEAM_X - TRAVEL:.2f} .. {BEAM_X + TRAVEL:.2f} m '
          f'({2 * TRAVEL:.2f} m), bench spans {BENCH_X[0]} .. {BENCH_X[1]} m')


if __name__ == '__main__':
    main()
