#!/usr/bin/env python3
"""Generate the detailed lab sink; metres, floor origin, tap toward +Y.

Run from simulation/: python scripts/generate_sink.py.
The original vendor meshes remain available, but this procedural model is the
source of truth for sink.xml. Basin panels collide individually so it stays open.
"""
from pathlib import Path
import math
from generate_lab_room import Mjcf, MATERIALS, fmt


def main():
    m = Mjcf()
    # Same footprint and worktop height as the original imported sink.
    for x in (-0.67, 0.67):
        for y in (-0.30, 0.30):
            m.box('leg', (x, y, 0.44), (0.028, 0.028, 0.40), 'white', solid=True)
            m.cyl('adjustable_foot', (x, y, 0.025), 0.037, 0.025, 'dark', solid=True)
            m.cyl('foot_thread', (x, y, 0.061), 0.014, 0.027, 'steel')
        m.box('end_rail', (x, 0, 0.24), (0.024, 0.30, 0.024), 'white', solid=True)
    m.box('rear_rail', (0, 0.30, 0.24), (0.67, 0.024, 0.024), 'white', solid=True)
    for y in (-0.32, 0.32):
        m.box('apron', (0, y, 0.83), (0.71, 0.022, 0.045), 'white', solid=True)
    # Four worktop sections surround the basin instead of capping it with a box.
    for x in (-0.55, 0.55):
        m.box('draining_board', (x, 0, 0.901), (0.201, 0.377, 0.019), 'steel', solid=True)
        for k in range(7):
            xx = x - 0.13 + k * 0.043
            m.rod('drainer_rib', (xx, -0.26, 0.922), (xx, 0.23, 0.922), 0.003, 'steel')
    for y in (-0.3185, 0.3185):
        m.box('basin_rim', (0, y, 0.901), (0.349, 0.0585, 0.019), 'steel', solid=True)
    m.box('backsplash', (0, 0.369, 0.957), (0.751, 0.008, 0.043), 'steel', solid=True)
    # Rounded rectangular bowl, tapered toward its drain; individual convex strips.
    def ring(hx, hy, r, z):
        pts = []
        for cx, cy, start in ((hx-r, hy-r, 0), (-hx+r, hy-r, 90),
                              (-hx+r, -hy+r, 180), (hx-r, -hy+r, 270)):
            for i in range(9):
                a = math.radians(start + i * 90 / 8)
                pts.append((cx + r * math.cos(a), cy + r * math.sin(a), z))
        return pts
    top = ring(0.349, 0.26, 0.075, 0.919)
    bottom = ring(0.27, 0.18, 0.065, 0.715)
    bowl_assets = []
    for i in range(len(top)):
        j = (i + 1) % len(top)
        pts = [top[i], top[j], bottom[i], bottom[j]]
        pts += [(x, y, z - 0.004) for x, y, z in pts]
        name = f'bowl_panel_{i}'
        bowl_assets.append(f'<mesh name="{name}" vertex="{fmt([v for p in pts for v in p])}"/>')
        m.add(f'<geom name="{name}" type="mesh" mesh="{name}" material="steel" group="1"/>')
        m.rod('rolled_rim', top[i], top[j], 0.004, 'steel')
    floor_pts = bottom + [(x, y, z-0.006) for x, y, z in bottom]
    bowl_assets.append(f'<mesh name="bowl_floor" vertex="{fmt([v for p in floor_pts for v in p])}"/>')
    m.add('<geom name="bowl_floor" type="mesh" mesh="bowl_floor" material="steel" group="1"/>')
    m.cyl('drain_flange', (0, 0, 0.717), 0.047, 0.002, 'aluminium')
    m.cyl('drain_inset', (0, 0, 0.720), 0.034, 0.001, 'dark')
    m.cyl('strainer', (0, 0, 0.722), 0.029, 0.001, 'steel')
    for k in range(12):
        a = k * math.tau / 12
        m.cyl('strainer_hole', (0.022*math.cos(a), 0.022*math.sin(a), 0.7232), 0.003, 0.0003, 'dark')
    # Gooseneck faucet, aerator, mixer lever and visible P-trap.
    m.cyl('tap_mount', (0, 0.31, 0.925), 0.036, 0.005, 'steel')
    m.rod('tap_stem', (0, 0.31, 0.93), (0, 0.31, 1.15), 0.018, 'steel')
    arc = [(0, 0.21 + 0.1*math.cos(math.pi*i/24), 1.15 + 0.1*math.sin(math.pi*i/24)) for i in range(25)]
    for a, b in zip(arc, arc[1:]):
        m.rod('tap_bend', a, b, 0.017, 'steel')
    m.rod('tap_spout', arc[-1], (0, 0.11, 1.115), 0.017, 'steel')
    m.cyl('aerator', (0, 0.11, 1.111), 0.020, 0.01, 'aluminium')
    m.cyl('aerator_mesh', (0, 0.11, 1.1005), 0.015, 0.0005, 'dark')
    m.rod('mixer', (0, 0.31, 0.96), (0.072, 0.31, 0.96), 0.024, 'steel')
    m.rod('lever', (0.072, 0.31, 0.96), (0.072, 0.29, 1.06), 0.008, 'steel')
    m.ellipsoid('hot_indicator', (0.074, 0.287, 0.98), (0.005, 0.002, 0.004), 'red_cap')
    m.ellipsoid('cold_indicator', (0.074, 0.287, 0.967), (0.005, 0.002, 0.004), 'blue_hdpe')
    path = [(0,0,0.71), (0,0,0.50), (0,0.03,0.46), (0,0.10,0.46), (0,0.14,0.50), (0,0.14,0.57), (0,0.31,0.57)]
    for a,b in zip(path,path[1:]):
        m.rod('waste_pipe', a,b,0.022,'white')
    for z in (0.68,0.53):
        m.cyl('pipe_coupling',(0,0,z),0.029,0.014,'white_matte')
    materials = '\n'.join(f'<material name="{k}" {v}/>' for k,v in MATERIALS.items())
    meshes = '\n'.join(f'<mesh name="{name}" vertex="{fmt(vertices)}"/>' for name,vertices in m.bevel_meshes.values())
    xml = ('<!-- Generated by scripts/generate_sink.py; do not edit by hand. -->\n'
           '<mujoco model="sink"><asset>\n' + materials + '\n' + meshes + '\n' + '\n'.join(bowl_assets)
           + '\n</asset><worldbody><body name="sink">\n' + '\n'.join(m.lines) + '\n</body></worldbody></mujoco>\n')
    out = Path(__file__).resolve().parents[1] / 'assets/sink/sink.xml'
    out.write_text(xml)
    print(f'Generated {out}')

if __name__ == '__main__':
    main()
