#!/usr/bin/env python3
"""Create a shelf-free MiniHannover variant with a centered 6 x 2 m desk.

Run from simulation/: python scripts/generate_minihannover_open.py.
Reuses the original room builders and scene assets without rewriting them.
"""
import json
from pathlib import Path
import xml.etree.ElementTree as ET

import numpy as np

import generate_lab_room as room
import generate_minihannover as bench

SIM = Path(__file__).resolve().parents[1]
OUT = SIM / 'assets/minihannover_open'
WIDTH = 2.0
CENTER = np.array(((room.X0 + room.X1) / 2, (room.Y0 + room.Y1) / 2, 0.0))
EDGE_SHIFT = 0.25
EXTRA_AMBER = 220
POPULATION_SEED = 29
HEADER = '<!-- Generated by scripts/generate_minihannover_open.py; do not edit by hand. -->\n'


def write_xml(path, root):
    ET.indent(root, space='  ')
    path.write_text('<?xml version="1.0" encoding="utf-8"?>\n' + HEADER + ET.tostring(root, encoding='unicode') + '\n')


def camera(m, name, eye, target, fovy=60):
    eye, target = np.array(eye, float), np.array(target, float)
    forward = (target - eye) / np.linalg.norm(target - eye)
    right = np.cross(forward, (0, 0, 1))
    right /= np.linalg.norm(right)
    up = np.cross(right, forward)
    m.add(f'<camera name="{name}" pos="{room.fmt(eye)}" xyaxes="{room.fmt(right)} {room.fmt(up)}" fovy="{fovy}"/>')


def edge_props(m):
    """Move each side's work stations outward; end-mounted wash/scale stay put."""
    start = len(m.lines)
    room.bench_props(m)
    fragment = ET.fromstring('<frame>' + '\n'.join(m.lines[start:]) + '</frame>')
    del m.lines[start:]
    for geom in fragment:
        if geom.tag != 'geom':
            continue
        attr = 'fromto' if 'fromto' in geom.attrib else 'pos'
        values = np.fromstring(geom.get(attr, '0 0 0'), sep=' ').reshape(-1, 3)
        center = values.mean(axis=0)
        if -2.5 < center[0] < 2.0:
            values[:, 1] += EDGE_SHIFT if center[1] >= 0 else -EDGE_SHIFT
            geom.set(attr, room.fmt(values.ravel()))
        m.add(ET.tostring(geom, encoding='unicode'))


def tabletop_population(m):
    """Rehouse all shelved samples and add smaller unbarcoded amber reserve vials."""
    manifest = json.loads((room.BOTTLES / 'manifest.json').read_text())
    vessels = manifest['vessels']
    rng = np.random.default_rng(POPULATION_SEED)
    # Keep only liquid stock on the open desk; solid/powder jars are dropped.
    records = [dict(sample_id=k, vessel_class=v['vessel_class'])
               for k,v in sorted(manifest['samples'].items())
               if k not in room.PLACED_BY_SCENE
               and vessels[v['vessel_class']]['phase'] == 'liquid']
    # Preserve catalogued sizes/barcodes. Extra stock has blank labels, not duplicate IDs.
    for i in range(EXTRA_AMBER):
        vessel = str(rng.choice(['flask_10ml', 'flask_20ml', 'flask_30ml', 'flask_50ml'],
                               p=[0.40, 0.32, 0.20, 0.08]))
        records.append(dict(sample_id=None, vessel_class=vessel, extra_id=i))
    # Pack larger containers first; each position is random rather than a size-sorted row.
    records.sort(key=lambda r: -vessels[r['vessel_class']]['diameter_m'])
    placed, used_meshes = [], set()
    for record in records:
        vessel = record['vessel_class']
        spec = vessels[vessel]
        radius = spec['diameter_m'] / 2
        for attempt in range(20000):
            x = rng.uniform(-2.42 + radius, 1.90 - radius)
            y = rng.uniform(-0.43 + radius, 0.43 - radius)
            if all((x-p['x'])**2 + (y-p['y'])**2 > (radius+p['radius']+0.009)**2 for p in placed):
                break
        else:
            raise RuntimeError('Population does not fit with required spacing')
        yaw = float(rng.uniform(-180, 180))
        record.update(x=float(x), y=float(y), radius=radius, yaw=yaw,
                      phase=spec['phase'], container_ml=spec['container_ml'])
        placed.append(record)
        sample = record['sample_id']
        tag = sample if sample else f"reserve_{record['extra_id']:03d}"
        if sample:
            m.assets.append(f'<texture name="stock_{tag}" type="2d" file="../labelled_bottles/textures/shelf/{sample}.png"/>')
            m.assets.append(f'<material name="stock_{tag}" texture="stock_{tag}" specular="0.05"/>')
        for part in spec['parts']:
            mesh = f'{vessel}_{part}' if part.startswith('label') else f'{vessel}_shelf_{part}'
            used_meshes.add(mesh)
            material = {'glass':'amber', 'body':'sample_hdpe', 'cap':'sample_cap',
                        'label':'paper', 'label_back':'paper'}[part]
            if part == 'label' and sample:
                material = f'stock_{tag}'
            m.mesh(f'stock_{tag}_{part}', mesh, (x,y,room.BENCH_TOP), material, euler=(0,0,yaw))
        # Welded stock, matching the original shelf behavior, with a simple contact proxy.
        height = spec['height_m']
        m.add(f'<geom name="stock_{tag}_collision" type="cylinder" '
              f'pos="{room.fmt((x,y,room.BENCH_TOP+height/2))}" size="{radius:g} {height/2:g}" '
              'group="3" rgba="0 0 0 0"/>')
    for mesh in sorted(used_meshes):
        m.assets.append(f'<mesh name="{mesh}" file="../labelled_bottles/meshes/{mesh}.obj" inertia="shell"/>')
    (OUT / 'population.json').write_text(json.dumps(dict(seed=POPULATION_SEED,
        coordinate_frame='desk local, origin at floor; containers rest at z=0.90 m',
        containers=placed), indent=2) + '\n')
    print(f"Center population: {len(placed)} containers; "
          f"{sum(p['phase']=='liquid' for p in placed)} amber / "
          f"{sum(p['phase']!='liquid' for p in placed)} white")


def build_room():
    m = room.Mjcf()
    for build in (room.shell, room.ceiling, room.lights):
        build(m)
    m.add(f'<frame pos="{room.fmt(CENTER)}">')
    room.central_bench(m, half_width=WIDTH / 2)
    edge_props(m)
    tabletop_population(m)
    room.snorkels(m)
    m.add('</frame>')
    for build in (room.wall_bench, room.entrance_corner, room.instrument_bench,
                  room.far_end, room.office_beyond):
        build(m)
    cx, cy, _ = CENTER
    camera(m, 'entrance', (room.X0 + 0.6, cy - 1.35, 1.7), (cx, cy, 1.0))
    camera(m, 'aisle', (cx - 3.4, cy - 1.45, 1.7), (cx, cy, 0.95))
    camera(m, 'desk', (cx, cy - 1.55, 2.55), (cx, cy, 0.9), 80)
    camera(m, 'wash', (cx + 4.2, cy - 1.5, 1.9), (cx + 2.9, cy, 0.95))
    camera(m, 'overview', (cx, cy - 0.01, 8.0), (cx, cy, 0.9), 60)
    materials = '\n'.join(f'<material name="{k}" {v}/>' for k,v in room.MATERIALS.items())
    meshes = '\n'.join(f'<mesh name="{n}" file="../lab_room/meshes/{n}.obj" inertia="shell"/>' for n in room.LATHES)
    meshes += '\n' + '\n'.join(m.assets)
    meshes += '\n' + '\n'.join(f'<mesh name="{name}" vertex="{room.fmt(vertices)}"/>' for name,vertices in m.bevel_meshes.values())
    root = ET.fromstring('<mujoco model="lab_room_open"><asset>' + materials + meshes
                         + '</asset><worldbody><body name="lab_room">'
                         + '\n'.join(m.lines) + '</body></worldbody></mujoco>')
    write_xml(OUT / 'lab_room.xml', root)


def build_bench():
    root = ET.Element('mujoco', model='minihannover_open')
    ET.SubElement(root, 'compiler', angle='radian', autolimits='true')
    body = ET.SubElement(ET.SubElement(root, 'worldbody'), 'body', name='minihannover', pos=room.fmt(CENTER))
    for p in bench.build(width=WIDTH):
        ET.SubElement(body, 'geom', name=p.name, type='box', pos=bench.vec(p.center),
                      size=bench.vec(p.half), density=bench.f(p.density), rgba=bench.vec(p.rgba))
    write_xml(OUT / 'bench.xml', root)


def build_scene():
    root = ET.parse(SIM / 'models/minihannover_scene.xml').getroot()
    root.set('model', 'minihannover_open_scene')
    root.find('include').set('file', '../assets/minihannover_open/bench.xml')
    root.find("asset/model[@name='lab_room']").set('file', '../assets/minihannover_open/lab_room.xml')
    root.find('statistic').set('center', room.fmt(CENTER + (-2.8, -0.6, 1.1)))
    root.find('statistic').set('extent', '2.4')
    root.find('visual/global').set('azimuth', '8')
    root.find('visual/global').set('elevation', '-15')
    for node in root.find('worldbody'):
        attachment = node.find('attach')
        on_desk = (attachment is not None and attachment.get('model') in {'sink', 'balance'})
        on_desk |= node.tag == 'body' and (node.get('name', '').startswith('loose_') or node.get('name') == 'wrist_camera_mount')
        if on_desk:
            pos = np.fromstring(node.get('pos', '0 0 0'), sep=' ')
            if attachment is not None and attachment.get('model') == 'balance':
                pos[1] += np.sign(pos[1]) * EDGE_SHIFT
            elif node.tag == 'body':
                # Keep loose work samples and their wrist-camera viewing pose together.
                pos[1] += np.sign(pos[1]) * EDGE_SHIFT
            node.set('pos', room.fmt(pos + CENTER))
    # The fixed wall camera already aims at the room center; retain its calibration.
    # The wrist mount moves with loose_2, preserving its barcode viewing distance.
    write_xml(SIM / 'models/minihannover_open_scene.xml', root)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    build_room()
    build_bench()
    build_scene()
    print(f'Created minihannover_open_scene: 6 x {WIDTH:g} m desk centered at {room.fmt(CENTER)}')


if __name__ == '__main__':
    main()
