#!/usr/bin/env python3
"""Create a shelf-free MiniHannover variant with a centered 6 x 2 m desk.

Run from simulation/: python scripts/generate_minihannover_open.py.
Reuses the original room builders and scene assets without rewriting them.
"""
from pathlib import Path
import xml.etree.ElementTree as ET

import numpy as np

import generate_lab_room as room
import generate_minihannover as bench

SIM = Path(__file__).resolve().parents[1]
OUT = SIM / 'assets/minihannover_open'
WIDTH = 2.0
CENTER = np.array(((room.X0 + room.X1) / 2, (room.Y0 + room.Y1) / 2, 0.0))
HEADER = '<!-- Generated by scripts/generate_minihannover_open.py; do not edit by hand. -->\n'


def write_xml(path, root):
    ET.indent(root, space='  ')
    path.write_text('<?xml version="1.0" encoding="utf-8"?>\n' + HEADER + ET.tostring(root, encoding='unicode') + '\n')


def camera(m, name, eye, target, fovy=60):
    eye, target = np.array(eye, float), np.array(target, float)
    forward = (target - eye) / np.linalg.norm(target - eye)
    right = np.cross(forward, (0, 0, 1))
    right /= np.linalg.norm(right)
    up = np.cross(right, forward)
    m.add(f'<camera name="{name}" pos="{room.fmt(eye)}" xyaxes="{room.fmt(right)} {room.fmt(up)}" fovy="{fovy}"/>')


def build_room():
    m = room.Mjcf()
    for build in (room.shell, room.ceiling, room.lights):
        build(m)
    m.add(f'<frame pos="{room.fmt(CENTER)}">')
    room.central_bench(m, half_width=WIDTH / 2)
    # No gantry/library: omit both the shelf geometry and its supported bottles.
    room.bench_props(m)
    room.snorkels(m)
    m.add('</frame>')
    for build in (room.wall_bench, room.entrance_corner, room.instrument_bench,
                  room.far_end, room.office_beyond):
        build(m)
    cx, cy, _ = CENTER
    camera(m, 'entrance', (room.X0 + 0.6, cy - 1.35, 1.7), (cx, cy, 1.0))
    camera(m, 'aisle', (cx - 3.4, cy - 1.45, 1.7), (cx, cy, 0.95))
    camera(m, 'desk', (cx, cy - 1.55, 2.55), (cx, cy, 0.9), 80)
    camera(m, 'wash', (cx + 4.2, cy - 1.5, 1.9), (cx + 2.9, cy, 0.95))
    camera(m, 'overview', (cx, cy - 0.01, 8.0), (cx, cy, 0.9), 60)
    materials = '\n'.join(f'<material name="{k}" {v}/>' for k,v in room.MATERIALS.items())
    meshes = '\n'.join(f'<mesh name="{n}" file="../lab_room/meshes/{n}.obj" inertia="shell"/>' for n in room.LATHES)
    meshes += '\n' + '\n'.join(f'<mesh name="{name}" vertex="{room.fmt(vertices)}"/>' for name,vertices in m.bevel_meshes.values())
    root = ET.fromstring('<mujoco model="lab_room_open"><asset>' + materials + meshes
                         + '</asset><worldbody><body name="lab_room">'
                         + '\n'.join(m.lines) + '</body></worldbody></mujoco>')
    write_xml(OUT / 'lab_room.xml', root)


def build_bench():
    root = ET.Element('mujoco', model='minihannover_open')
    ET.SubElement(root, 'compiler', angle='radian', autolimits='true')
    body = ET.SubElement(ET.SubElement(root, 'worldbody'), 'body', name='minihannover', pos=room.fmt(CENTER))
    for p in bench.build(width=WIDTH):
        ET.SubElement(body, 'geom', name=p.name, type='box', pos=bench.vec(p.center),
                      size=bench.vec(p.half), density=bench.f(p.density), rgba=bench.vec(p.rgba))
    write_xml(OUT / 'bench.xml', root)


def build_scene():
    root = ET.parse(SIM / 'models/minihannover_scene.xml').getroot()
    root.set('model', 'minihannover_open_scene')
    root.find('include').set('file', '../assets/minihannover_open/bench.xml')
    root.find("asset/model[@name='lab_room']").set('file', '../assets/minihannover_open/lab_room.xml')
    root.find('statistic').set('center', room.fmt(CENTER + (-2.8, -0.6, 1.1)))
    root.find('statistic').set('extent', '2.4')
    root.find('visual/global').set('azimuth', '8')
    root.find('visual/global').set('elevation', '-15')
    for node in root.find('worldbody'):
        attachment = node.find('attach')
        on_desk = (attachment is not None and attachment.get('model') in {'sink', 'balance'})
        on_desk |= node.tag == 'body' and (node.get('name', '').startswith('loose_') or node.get('name') == 'wrist_camera_mount')
        if on_desk:
            pos = np.fromstring(node.get('pos', '0 0 0'), sep=' ')
            node.set('pos', room.fmt(pos + CENTER))
    # The fixed wall camera already aims at the room center; retain its calibration.
    # The wrist mount moves with loose_2, preserving its barcode viewing distance.
    write_xml(SIM / 'models/minihannover_open_scene.xml', root)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    build_room()
    build_bench()
    build_scene()
    print(f'Created minihannover_open_scene: 6 x {WIDTH:g} m desk centered at {room.fmt(CENTER)}')


if __name__ == '__main__':
    main()
