#!/usr/bin/env python3
"""Generate the machine-vision camera that rides on the UR10e's wrist.

Run from simulation/: python scripts/generate_wrist_camera.py.
Writes assets/wrist_camera/wrist_camera.xml, which generate_rail_scene.py
attaches to the arm so the scene shows a camera where the renders come from.

Modelled on a compact GigE industrial camera with a C-mount lens on an L-bracket
clamped round the wrist tube --- a Basler ace class body, 29 x 29 x 42 mm, with
a 16 mm lens. Everything is a primitive; there are no meshes to convert.

**The model's origin is the front face of the lens, +Z along the view.** That is
the pose the MJCF camera is given, so every part of the camera sits at z <= 0 and
none of it can appear in its own picture. Getting that wrong shows up as a black
crescent at the edge of every frame.
"""
import itertools
import math
from pathlib import Path

from generate_lab_room import MATERIALS, Mjcf, fmt

SIM = Path(__file__).resolve().parents[1]
OUT = SIM / 'assets/wrist_camera/wrist_camera.xml'
HEADER = '<!-- Generated by scripts/generate_wrist_camera.py; do not edit by hand. -->\n'

# The camera hangs this far to the side of the tool axis and this far past the
# flange; generate_rail_scene.py places it, and the bracket has to span back to
# the wrist from wherever that is. Keep in step with EIH_OFFSET / EIH_DROP.
TOOL_AXIS_X = -0.09
FLANGE_Z = -0.03


def lens(m: Mjcf) -> None:
    """A 16 mm C-mount lens, front face on the model origin."""
    m.comment('C-mount lens; the hood stops 1 mm short of the origin so that '
              'no part of the camera can reach into its own frame')
    m.cyl('lens_hood', (0, 0, -0.005), 0.0160, 0.004, 'black', solid=True)
    m.cyl('lens_glass', (0, 0, -0.0085), 0.0138, 0.0005, 'glass_clear')
    m.cyl('lens_focus_ring', (0, 0, -0.014), 0.0155, 0.006, 'dark')
    m.cyl('lens_barrel', (0, 0, -0.028), 0.0146, 0.009, 'black', solid=True)
    m.cyl('lens_aperture_ring', (0, 0, -0.038), 0.0152, 0.005, 'dark')
    m.cyl('lens_mount', (0, 0, -0.046), 0.0125, 0.004, 'aluminium')


def body(m: Mjcf) -> None:
    """The 29 x 29 x 42 mm camera body, its connectors and its status light."""
    m.comment('Camera body, behind the lens')
    m.box('cam_front_plate', (0, 0, -0.0515), (0.0150, 0.0150, 0.0025),
          'aluminium', solid=True)
    m.box('cam_body', (0, 0, -0.075), (0.0145, 0.0145, 0.021), 'dark', solid=True)
    # Heat-sink ribs down one flank, which is what these bodies are made of.
    for i in range(5):
        m.box('cam_rib', (0.0148, 0, -0.060 - i * 0.008), (0.0008, 0.013, 0.0022),
              'aluminium')
    m.box('cam_back', (0, 0, -0.0975), (0.0145, 0.0145, 0.0025), 'dark', solid=True)
    m.comment('Connectors and status light')
    m.box('cam_rj45', (0, 0.006, -0.1045), (0.0075, 0.0060, 0.0050), 'black')
    m.cyl('cam_io', (0, -0.008, -0.1035), 0.0055, 0.004, 'aluminium')
    m.ellipsoid('cam_led', (-0.0085, 0.0148, -0.0635), (0.0018, 0.0006, 0.0018),
                'led')
    m.comment('Cable, dressed back along the bracket toward the wrist')
    path = [(0, 0.006, -0.1105), (0, 0.020, -0.115), (-0.030, 0.026, -0.105),
            (TOOL_AXIS_X + 0.02, 0.022, -0.070), (TOOL_AXIS_X, 0.016, -0.050)]
    for a, b in itertools.pairwise(path):
        m.rod('cam_cable', a, b, 0.0035, 'black')


def bracket(m: Mjcf) -> None:
    """Adapter plate at the tool flange, with an arm out to the camera.

    A camera on a wrist is mounted the way any other tooling is: a plate
    sandwiched at the robot flange, under the gripper's own adapter, with an arm
    reaching out to wherever the lens has to sit. A collar clamped round the
    wrist tube was tried first and reads as a dinner plate stuck on the arm.
    """
    riser_x = -0.0175
    m.comment('Adapter plate at the flange, under the gripper')
    # A UR10e tool flange is 90 mm across; the plate sits flush on it.
    m.cyl('bracket_plate', (TOOL_AXIS_X, 0, FLANGE_Z - 0.0035), 0.045, 0.0035,
          'steel', solid=True)
    for i in range(4):
        angle = math.radians(45 + i * 90)
        m.cyl('bracket_bolt',
              (TOOL_AXIS_X + 0.036 * math.cos(angle), 0.036 * math.sin(angle),
               FLANGE_Z - 0.0025), 0.0035, 0.0035, 'aluminium')
    m.comment('Arm from the plate out to the camera, and the riser it bolts to')
    m.span('bracket_arm', (TOOL_AXIS_X + 0.040, -0.012, -0.061),
           (riser_x + 0.002, 0.012, -0.032), 'steel', solid=True)
    m.box('bracket_riser', (riser_x, 0, -0.078), (0.0025, 0.014, 0.024),
          'steel', solid=True)
    m.box('bracket_gusset', (riser_x - 0.006, 0, -0.064), (0.008, 0.010, 0.0025),
          'steel')


def main() -> None:
    m = Mjcf()
    lens(m)
    body(m)
    bracket(m)

    materials = '\n'.join(f'<material name="{k}" {v}/>' for k, v in MATERIALS.items())
    # Mjcf.box rounds the edges of big enough boxes into a mesh; those have to
    # travel with the model.
    meshes = '\n'.join(f'<mesh name="{name}" vertex="{fmt(vertices)}"/>'
                       for name, vertices in m.bevel_meshes.values())
    xml = ('<?xml version="1.0" encoding="utf-8"?>\n' + HEADER
           + '<mujoco model="wrist_camera">\n<asset>\n' + materials + '\n' + meshes
           + '\n</asset>\n<worldbody>\n<body name="wrist_camera">\n'
           + '\n'.join(m.lines)
           + '\n</body>\n</worldbody>\n</mujoco>\n')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(xml)
    print(f'wrote {OUT.relative_to(SIM)}')


if __name__ == '__main__':
    main()
