#!/usr/bin/env python3
"""Generate the single-channel pipette that mounts on the UR10e's flange.

Run from simulation/: python scripts/generate_pipette.py.
generate_rail_scene.py attaches it in place of the gripper.

Modelled on a laboratory air-displacement micropipette of the 100-1000 ul
class, coaxial with the tool flange the way a robot pipetting head is: a
knurled barrel, a tapered shoulder, the cone, and a fixed tip. No disposable
tips and no tip rack --- the tip is part of the tool.

**The origin is the mounting face and +Z runs down the tool axis**, the same
frame the gripper mounts in, so the arm's kinematics do not change shape. The
tool centre point moves to the `tip` site at the very end.

The tip is a body of its own, rigidly attached, for one reason: MuJoCo collides
meshes as their convex hull, so a flask is a solid lump and nothing can be put
inside it. Excluding contact between that body and the vessels lets the tip go
down the bore, while the barrel above it still collides with everything. See
PIPETTING_PLAN.md.
"""
import math
from pathlib import Path

from generate_lab_room import MATERIALS, Mjcf, fmt

SIM = Path(__file__).resolve().parents[1]
OUT = SIM / 'assets/pipette/pipette.xml'
HEADER = '<!-- Generated by scripts/generate_pipette.py; do not edit by hand. -->\n'

# Down the tool axis from the mounting face, in metres.
BARREL = (0.004, 0.086)     # knurled grip body
TAPER = (0.086, 0.112)      # shoulder into the cone
CONE = (0.112, 0.140)       # the cone a disposable tip would push onto
# The tip has to be long enough that the cone above it stays clear of the rim
# while the tip is down at the liquid. The flasks are up to 113 mm tall, and a
# 56 mm tip put the cone --- 11.6 mm across --- level with a 12 mm bore, where
# it wedged and stopped the arm four times out of twelve. A real 1000 ul tip is
# about this long anyway.
TIP = (0.140, 0.265)
TIP_ROOT_R = 0.0028      # the widest part that has to pass a 6 mm bore
TIP_END_R = 0.0009
BARREL_R = 0.0115


def barrel(m: Mjcf) -> None:
    """Grip body, drive block and ejector --- everything above the cone."""
    m.comment('Mounting collar and the drive block a robot head carries')
    m.cyl('pip_collar', (0, 0, 0.002), 0.030, 0.002, 'aluminium', solid=True)
    m.box('pip_drive', (0, 0.020, 0.030), (0.016, 0.010, 0.026), 'dark',
          solid=True)
    m.ellipsoid('pip_led', (0, 0.0305, 0.046), (0.0025, 0.0006, 0.0025), 'led')
    m.comment('Barrel')
    lo, hi = BARREL
    m.cyl('pip_barrel', (0, 0, (lo + hi) / 2), BARREL_R, (hi - lo) / 2,
          'white', solid=True)
    for i in range(6):
        m.cyl('pip_grip_ring', (0, 0, lo + 0.010 + i * 0.011), BARREL_R + 0.0009,
              0.0022, 'blue_hdpe')
    m.comment('Volume window, because a pipette without one looks wrong')
    m.box('pip_window', (0, -BARREL_R, 0.030), (0.007, 0.0012, 0.013), 'screen')


def cone(m: Mjcf) -> None:
    """Shoulder, cone and the shank the tip grows out of."""
    m.comment('Shoulder and cone')
    lo, hi = TAPER
    for i in range(4):
        z = lo + (hi - lo) * (i + 0.5) / 4
        r = BARREL_R - (BARREL_R - 0.0062) * (i + 0.5) / 4
        m.cyl('pip_shoulder', (0, 0, z), r, (hi - lo) / 8, 'white', solid=True)
    lo, hi = CONE
    m.cyl('pip_cone', (0, 0, (lo + hi) / 2), 0.0058, (hi - lo) / 2, 'white',
          solid=True)
    m.cyl('pip_cone_lip', (0, 0, hi - 0.002), 0.0064, 0.002, 'aluminium')


def tip(m: Mjcf) -> None:
    """The fixed tip, its bore and the liquid column that shows in it."""
    m.comment('Fixed tip, tapering to the orifice')
    lo, hi = TIP
    steps = 10
    for i in range(steps):
        z = lo + (hi - lo) * (i + 0.5) / steps
        r = TIP_ROOT_R - (TIP_ROOT_R - TIP_END_R) * (i + 0.5) / steps
        m.cyl('pip_tip', (0, 0, z), r, (hi - lo) / (2 * steps), 'frosted',
              solid=True)
    m.comment('What is held in the tip; the pipetting code resizes it')
    m.cyl('pip_liquid', (0, 0, lo + 0.004), TIP_ROOT_R * 0.55, 0.00001,
          'amber')
    m.add(f'<site name="tip" pos="0 0 {hi:g}" size="0.0015" '
          f'rgba="0.9 0.3 0.2 0.6" group="4"/>')


def main() -> None:
    m = Mjcf()
    barrel(m)
    cone(m)
    body_lines = m.lines

    t = Mjcf()
    tip(t)

    materials = '\n'.join(f'<material name="{k}" {v}/>' for k, v in MATERIALS.items())
    meshes = '\n'.join(f'<mesh name="{name}" vertex="{fmt(vertices)}"/>'
                       for name, vertices in
                       {**m.bevel_meshes, **t.bevel_meshes}.values())
    xml = ('<?xml version="1.0" encoding="utf-8"?>\n' + HEADER
           + '<mujoco model="pipette">\n<asset>\n' + materials + '\n' + meshes
           + '\n</asset>\n<worldbody>\n<body name="pipette">\n'
           + '\n'.join(body_lines)
           + '\n      <body name="pipette_tip">\n'
           + '\n'.join(t.lines)
           + '\n      </body>\n</body>\n</worldbody>\n</mujoco>\n')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(xml)
    print(f'wrote {OUT.relative_to(SIM)}')
    print(f'tool length {TIP[1] * 1000:.0f} mm from the flange, '
          f'tip orifice radius {TIP_END_R * 1000:.1f} mm '
          f'(the narrowest flask mouth is 6.0 mm)')
    print(f'cone reaches {math.degrees(math.atan2(BARREL_R, TIP[1] - BARREL[0])):.0f} '
          f'degrees of half-angle around the tip')


if __name__ == '__main__':
    main()
