#!/usr/bin/env python3
"""The uncap-and-pipette hand for MuJoCo and for Isaac Lab, from iris_pipette_rig.py.

Run from simulation/: python scripts/generate_iris_pipette_scene.py.
Then play it: python scripts/iris_pipette_play.py (MuJoCo) or
scripts/iris_pipette_isaac.py (Isaac Lab).

One kinematic description, two formats, as generate_hand_scene.py does for the
hand alone:

* ``assets/ur10e_iris_pipette/ur10e_iris_pipette.xml`` --- the hand as an
  attachable MJCF, in the arm's tool frame: the arm stub, ``wrist_3_joint``
  with the flange, the Robotiq 2F-85 from ``assets/robotiq_2f85_sensed/``,
  and on the gripper body the hinge mount with the iris clamp and the mast
  with the pipette's slide and swing frame. Position actuators on every joint
  the sequence moves; the planetary train and the blades close through
  tendon and joint equalities, as in the clamp's own MJCF.
* ``assets/ur10e_iris_pipette/reference_bottle.xml`` --- the 60 ml amber
  bottle of ``assets/amber-bottles`` (Ø40 mm, 95 mm), attachable. It is drawn
  with the kit's own glass mesh and collides as a hollow ring of boxes, so the
  pipette can go down its neck; its PP25 cap is a body of its own in the
  scene, drawn with the kit's cap mesh.
* ``models/iris_pipette_scene.xml`` --- the MuJoCo scene: a floor, the hand
  held tool-horizontal from a ``lift`` carriage, the bottle and its cap loose
  on the floor, and three welds the play script switches: the bottle to the
  hand once gripped, the cap to the bottle or to the clamp's carrier. That is
  the page's rule, not physics: the pads squeeze the bottle and the blades
  close on the cap for the look of it, but nothing depends on the contact.
  FULL_PHYSICS_ISAAC.md says how to make it real.
* ``models/iris_pipette_rig.urdf``, ``reference_bottle.urdf``,
  ``reference_cap.urdf`` --- the same for Isaac's URDF importer. The blades
  and planets ``mimic`` the cam ring; the sun is a real joint the Isaac script
  drives to ``yaw - 3 cam``.

The meshes come out of the two asset zips into ``meshes/``, byte for byte, plus
the amber bottle's glass and cap (from its OBJs in ``assets/amber_bottles``, the
cap moved to its own origin) and a small cone MuJoCo has no primitive for.
"""
import math
import struct
import zipfile

import mujoco
import numpy as np

import iris_pipette_plan as plan
import iris_pipette_rig as rig
from generate_hand_scene import (ACTUATED, STUB_MASS, WRIST3_INERTIA,
                                 WRIST3_MASS, gripper_urdf, inertial_xml,
                                 joint_xml, mesh_visual, mimic_ratios, num,
                                 rpy, vec, wrist3_inertial)
from generate_iris_pipette_viewer import flange_x, pad_fit
from hand_linkage import (GRIPPER, MATERIALS, RING_HEIGHT, SIM, STUB_LENGTH,
                          STUB_RADIUS, STUB_TOP, linkage, wrist3_pose)

OUT_DIR = SIM / 'assets/ur10e_iris_pipette'
MESH_DIR = OUT_DIR / 'meshes'
RIG_XML = OUT_DIR / 'ur10e_iris_pipette.xml'
BOTTLE_XML = OUT_DIR / 'reference_bottle.xml'
SCENE_XML = SIM / 'models/iris_pipette_scene.xml'
RIG_URDF = SIM / 'models/iris_pipette_rig.urdf'
BOTTLE_URDF = OUT_DIR / 'reference_bottle.urdf'
CAP_URDF = OUT_DIR / 'reference_cap.urdf'
HEADER = 'Generated by scripts/generate_iris_pipette_scene.py; do not edit by hand.'

LIFT_RANGE = (0.0, 0.3)
CARRIAGE_MASS = 1.0
# The bottle's and the cap's mass and inertia come from their meshes (thin
# walls, inertia="exact") at these densities; the collision geoms weigh nothing.
# Collision bitmasks (contype, conaffinity): the floor is 1/1, the pads 1/1.
# Pads meet the bottle; the pipette meets the clamp, the bottle and the floor;
# the cap and the clamp meet nothing else (the welds carry the cap).
COLLIDE = {'bottle': (1, 9), 'cap': (2, 2), 'clamp': (4, 8), 'pipette': (8, 5)}
# Position actuators: kp, kv, force range.
GAINS = {'clamp_swing': (300, 5, 20), 'cam': (100, 2, 3), 'body_yaw': (150, 1, 8),
         'pipette_slide': (3000, 100, 100), 'pipette_swing': (100, 2, 5),
         'pipette_plunger_slide': (600, 5, 20)}
# What the URDF slaves to the cam ring (multiplier), from JOINT_MAP.
MIMIC_CAM = {f'blade_{k}': -1.0 for k in range(rig.IRIS['n_blades'])}
MIMIC_CAM.update({f'planet_{k}': rig.IRIS['n_ring'] / rig.IRIS['n_planet'] for k in range(3)})


# --- meshes ------------------------------------------------------------------


def write_stl(path, triangles: np.ndarray) -> None:
    tris = np.asarray(triangles, np.float32)
    normals = np.cross(tris[:, 1] - tris[:, 0], tris[:, 2] - tris[:, 0])
    normals /= np.maximum(np.linalg.norm(normals, axis=1, keepdims=True), 1e-12)
    record = np.dtype([('normal', '<f4', 3), ('v', '<f4', (3, 3)), ('attr', '<u2')])
    data = np.zeros(len(tris), record)
    data['normal'], data['v'] = normals, tris
    path.write_bytes(b'\0' * 80 + struct.pack('<I', len(tris)) + data.tobytes())


def cone_stl(radius: float, half_height: float, n: int = 24) -> np.ndarray:
    """A cone centred on its axis, apex at +Z, like three.js's ConeGeometry."""
    a = np.linspace(0, 2 * np.pi, n, endpoint=False)
    ring = np.stack([radius * np.cos(a), radius * np.sin(a), np.full(n, -half_height)], 1)
    nxt = np.roll(ring, -1, axis=0)
    apex, base = np.array([0, 0, half_height]), np.array([0, 0, -half_height])
    sides = np.stack([ring, nxt, np.tile(apex, (n, 1))], 1)
    bottom = np.stack([nxt, ring, np.tile(base, (n, 1))], 1)
    return np.concatenate([sides, bottom])


def mesh_file(key: str) -> str:
    """'iris/body' -> 'iris_body.stl'."""
    return key.replace('/', '_') + '.stl'


def write_meshes() -> None:
    MESH_DIR.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(rig.IRIS_ZIP) as archive:
        for part in rig.IRIS_PARTS:
            (MESH_DIR / mesh_file(f'iris/{part}')).write_bytes(rig.zip_member(archive, f'meshes/{part}.stl'))
    for part in ('glass', 'cap'):
        write_stl(MESH_DIR / mesh_file(f'amber/{part}'), rig.amber_mesh(part))
    with zipfile.ZipFile(rig.PIPETTE_ZIP) as archive:
        for parts in rig.PIPETTE_PARTS.values():
            for part in parts:
                (MESH_DIR / mesh_file(f'pipette/{part}')).write_bytes(rig.zip_member(archive, f'meshes/{part}.stl'))
    (cone,) = [g for b in rig.tree(-0.15) for g in b['geoms'] if g['type'] == 'cone']
    write_stl(MESH_DIR / 'cone_locator.stl', cone_stl(*cone['size']))


# --- MJCF ---------------------------------------------------------------------


def mjcf_geom(g: dict, indent: str) -> str:
    attrs = [f'name="{g["name"]}"', f'pos="{vec(g["pos"])}"']
    if not np.allclose(g['quat'], (1, 0, 0, 0)):
        attrs.append(f'quat="{vec(g["quat"])}"')
    if g['type'] == 'mesh':
        attrs += ['type="mesh"', f'mesh="{g["mesh"].replace("/", "_")}"']
    elif g['type'] == 'cone':
        attrs += ['type="mesh"', 'mesh="cone_locator"']
    else:
        attrs += [f'type="{g["type"]}"', f'size="{vec(g["size"])}"']
    if g['collide']:
        contype, conaffinity = COLLIDE[g['collide']]
        attrs += [f'contype="{contype}"', f'conaffinity="{conaffinity}"', 'group="3"', 'rgba="0.8 0.3 0.3 0.3"']
    else:
        attrs += ['contype="0"', 'conaffinity="0"', 'group="2"', f'material="{g["material"]}"']
    if g['mass'] is not None:
        attrs.append(f'mass="{num(g["mass"])}"')
    return f'{indent}<geom {" ".join(attrs)}/>\n'


def mjcf_body(b: dict, children: dict, indent: str) -> str:
    attrs = f'name="{b["name"]}" pos="{vec(b["pos"])}"'
    if not np.allclose(b['quat'], (1, 0, 0, 0)):
        attrs += f' quat="{vec(b["quat"])}"'
    out = f'{indent}<body {attrs}>\n'
    if b['mass'] is not None:
        out += f'{indent}  <inertial pos="0 0 0" mass="{num(b["mass"])}" diaginertia="1e-6 1e-6 1e-6"/>\n'
    j = b['joint']
    if j is not None:
        rng = '' if j['range'] is None else f' range="{vec(j["range"])}"'
        out += f'{indent}  <joint name="{j["name"]}" type="{j["type"]}" axis="{vec(j["axis"])}"{rng} armature="0.001" damping="0.05"/>\n'
    for g in b['geoms']:
        out += mjcf_geom(g, indent + '  ')
    for s in b['sites']:
        out += f'{indent}  <site name="{s["name"]}" pos="{vec(s["pos"])}" size="0.003" rgba="0.9 0.3 0.1 0.5" group="4"/>\n'
    for c in children.get(b['name'], []):
        out += mjcf_body(c, children, indent + '  ')
    return out + f'{indent}</body>\n'


def write_rig_mjcf(tree: list[dict]) -> None:
    wpos, wquat = wrist3_pose()
    ipos, iquat = wrist3_inertial()
    children = {}
    for b in tree:
        children.setdefault(b['parent'], []).append(b)
    used = {g['material'] for b in tree for g in b['geoms'] if g['material']} | {'linkgray', 'urblue'}
    materials = ''.join(f'    <material name="{k}" rgba="{vec(v)}" specular="0.5" shininess="0.25"/>\n'
                        for k, v in {**MATERIALS, **rig.RIG_MATERIALS}.items() if k in used)
    mesh_keys = sorted({g['mesh'] for b in tree for g in b['geoms'] if g['type'] == 'mesh'})
    meshes = ''.join(f'    <mesh name="{k.replace("/", "_")}" file="{mesh_file(k)}"/>\n' for k in mesh_keys)
    n_sun, n_ring, n_planet = rig.IRIS['n_sun'], rig.IRIS['n_ring'], rig.IRIS['n_planet']
    tendons = (f'    <fixed name="planetary">\n      <joint joint="sun_input" coef="{n_sun}"/>'
               f'<joint joint="cam" coef="{n_ring}"/><joint joint="body_yaw" coef="-{n_sun}"/>\n    </fixed>\n')
    equalities = '    <tendon name="eq_planetary" tendon1="planetary"/>\n'
    for k in range(3):
        tendons += (f'    <fixed name="mesh_planet_{k}">\n      <joint joint="planet_{k}" coef="{n_planet}"/>'
                    f'<joint joint="sun_input" coef="{n_sun}"/><joint joint="body_yaw" coef="-{n_sun}"/>\n    </fixed>\n')
        equalities += f'    <tendon name="eq_planet_{k}" tendon1="mesh_planet_{k}"/>\n'
    for k in range(rig.IRIS['n_blades']):
        equalities += f'    <joint name="eq_blade_{k}" joint1="blade_{k}" joint2="cam" polycoef="0 -1 0 0 0"/>\n'
    actuators = ''
    for b in tree:
        j = b['joint']
        if j is None or j['name'] not in GAINS:
            continue
        kp, kv, force = GAINS[j['name']]
        if j['name'] == 'body_yaw':     # unlimited joint; the control range covers the unscrewing
            lo, hi = 0.0, (rig.IRIS['turns'] + 0.1) * 2 * math.pi
        else:
            lo, hi = j['range']
        actuators += (f'    <position name="{j["name"]}" joint="{j["name"]}" kp="{kp}" kv="{kv}"'
                      f' ctrlrange="{vec((lo, hi))}" forcerange="{vec((-force, force))}"/>\n')
    RIG_XML.write_text(f'''<mujoco model="ur10e_iris_pipette">
  <!-- {HEADER} -->
  <!-- The UR10e past its last wrist joint with the uncap-and-pipette tooling on
       the 2F-85, in the arm's tool frame: origin on the flange face, +Z the
       approach. A fixed cylinder stands in for the arm. See iris_pipette_rig.py
       for the layout and JOINT_MAP for how the joints move together. -->
  <compiler angle="radian" meshdir="meshes" autolimits="true"/>
  <option cone="elliptic" impratio="10"/>   <!-- the 2F-85's, so its pads grip the same -->

  <asset>
    <model name="robotiq_2f85" file="../robotiq_2f85_sensed/2f85_sensed.xml"/>
{materials}    <mesh name="wrist3" file="../../../third_party/mujoco_menagerie/universal_robots_ur10e/assets/wrist3.obj"/>
{meshes}    <mesh name="cone_locator" file="cone_locator.stl"/>
  </asset>

  <worldbody>
    <body name="ur10e_iris_pipette">
      <inertial pos="0 0 {num(STUB_TOP - STUB_LENGTH / 2)}" mass="{num(STUB_MASS)}" diaginertia="0.002 0.002 0.001"/>
      <geom name="arm_stub_housing" type="cylinder" size="{num(STUB_RADIUS)} {num(STUB_LENGTH / 2)}"
            pos="0 0 {num(STUB_TOP - STUB_LENGTH / 2)}" material="linkgray" contype="0" conaffinity="0" group="2" mass="0"/>
      <geom name="arm_stub_ring" type="cylinder" size="{num(STUB_RADIUS + 0.001)} {num(RING_HEIGHT / 2)}"
            pos="0 0 {num(STUB_TOP - RING_HEIGHT / 2)}" material="urblue" contype="0" conaffinity="0" group="2" mass="0"/>
      <body name="wrist_3_link">
        <inertial pos="{vec(ipos)}" quat="{vec(iquat)}" mass="{num(WRIST3_MASS)}" diaginertia="{vec(WRIST3_INERTIA)}"/>
        <joint name="wrist_3_joint" type="hinge" axis="0 0 1" range="-6.28319 6.28319" armature="0.1" damping="2"/>
        <geom name="wrist_3_visual" type="mesh" mesh="wrist3" pos="{vec(wpos)}" quat="{vec(wquat)}"
              material="linkgray" contype="0" conaffinity="0" group="2"/>
        <site name="tool" size="0.004" rgba="0.9 0.3 0.1 0.5" group="4"/>
        <attach model="robotiq_2f85" body="base_mount" prefix=""/>
{''.join(mjcf_body(c, children, '        ') for c in children['wrist_3_link'])}      </body>
    </body>
  </worldbody>

  <tendon>
{tendons}  </tendon>

  <equality>
{equalities}  </equality>

  <actuator>
    <general name="wrist_3" joint="wrist_3_joint" biastype="affine" gainprm="500" biasprm="0 -500 -50"
             ctrlrange="-6.2831 6.2831" forcerange="-56 56"/>
{actuators}  </actuator>
</mujoco>
''')


def bottle_collision() -> list[tuple[str, tuple, tuple, tuple]]:
    """The amber bottle, hollow, as (type, pos, quat, size): its floor, a ring
    of wall boxes up the straight body and a ring of neck boxes around the
    bore. The shoulder between them is left open: nothing reaches it."""
    a = rig.AMBER
    R, wall, floor = a['r'], a['wall'], a['floor']
    shapes = [('cylinder', (0, 0, floor / 2), (1, 0, 0, 0), (R - wall, floor / 2))]
    for n, r_out, r_in, z0, z1 in ((16, R, R - wall, floor, a['shoulder']),
                                   (8, a['neck_r'], a['bore'], a['neck'], a['h'])):
        r_mid, t = (r_out + r_in) / 2, r_out - r_in
        half_w = r_in * math.tan(math.pi / n)
        for k in range(n):
            a = k * 2 * math.pi / n
            shapes.append(('box', (r_mid * math.cos(a), r_mid * math.sin(a), (z0 + z1) / 2), rig.zrot(a),
                           (t / 2, half_w, (z1 - z0) / 2)))
    return shapes


def write_bottle_mjcf() -> None:
    contype, conaffinity = COLLIDE['bottle']
    a = rig.AMBER
    geoms = ''.join(f'      <geom type="{kind}" pos="{vec(pos)}" quat="{vec(quat)}" size="{vec(size)}"'
                    f' contype="{contype}" conaffinity="{conaffinity}" group="3" mass="0" friction="1 0.005 0.0001"/>\n'
                    for kind, pos, quat, size in bottle_collision())
    BOTTLE_XML.write_text(f'''<mujoco model="reference_bottle">
  <!-- {HEADER} -->
  <!-- The 60 ml amber bottle of assets/amber-bottles: Ø{num(2 * a["r"] * 1000)} mm, {num(a["h"] * 1000)} mm to the lip, its PP25
       cap seated {num(a["cap_z"] * 1000)} mm up, bore Ø{num(2 * a["bore"] * 1000)} mm. Origin at the base, on the axis. Drawn with
       the kit's glass mesh, which also gives the mass; it collides as a ring of boxes so the
       pipette can go down the neck. The cap is a body of its own. -->
  <compiler angle="radian" meshdir="meshes"/>
  <asset>
    <mesh name="amber_glass" file="amber_glass.stl" inertia="exact"/>
    <material name="bottle" rgba="{vec(rig.RIG_MATERIALS["bottle"])}" specular="0.5" shininess="0.25"/>
  </asset>
  <worldbody>
    <body name="reference_bottle">
      <geom name="bottle_visual" type="mesh" mesh="amber_glass" material="bottle" density="{num(a["glass_density"])}"
            contype="0" conaffinity="0" group="2"/>
{geoms}    </body>
  </worldbody>
</mujoco>
''')


def cap_geoms_mjcf(indent: str) -> str:
    contype, conaffinity = COLLIDE['cap']
    return (f'{indent}<geom name="cap_visual" type="mesh" mesh="amber_cap" material="cap" density="{num(rig.AMBER["cap_density"])}"'
            f' contype="0" conaffinity="0" group="2"/>\n'
            f'{indent}<geom name="cap_collision" type="cylinder" size="{num(rig.IRIS["cap_r"])} {num(rig.IRIS["cap_h"] / 2)}"'
            f' pos="0 0 {num(rig.IRIS["cap_h"] / 2)}" contype="{contype}" conaffinity="{conaffinity}" group="3" mass="0"/>\n')


def write_scene_mjcf(fx: float, keyframe: str = '') -> None:
    lo, hi = LIFT_RANGE
    SCENE_XML.write_text(f'''<mujoco model="iris_pipette_scene">
  <!-- {HEADER} -->
  <!-- The uncap-and-pipette hand over the reference bottle: python scripts/iris_pipette_play.py.
       The hand hangs tool-horizontal from a lift carriage; its hand frame (the bottle's axis, at
       the base of the reference bottle) is the carriage origin, so lift = the bottle's base height
       once it is held. The welds are the page's parenting rule: the play script switches them. -->
  <compiler angle="radian" autolimits="true" meshdir="../assets/ur10e_iris_pipette/meshes"/>
  <option integrator="implicitfast" timestep="0.001" cone="elliptic" impratio="10"/>
  <statistic center="0 0.05 0.15" extent="0.6"/>
  <visual>
    <headlight diffuse="0.5 0.5 0.5" ambient="0.3 0.3 0.3" specular="0.1 0.1 0.1"/>
    <global azimuth="150" elevation="-20" offwidth="1280" offheight="720"/>
    <quality shadowsize="4096"/>
  </visual>

  <asset>
    <model name="ur10e_iris_pipette" file="../assets/ur10e_iris_pipette/ur10e_iris_pipette.xml"/>
    <model name="reference_bottle" file="../assets/ur10e_iris_pipette/reference_bottle.xml"/>
    <mesh name="amber_cap" file="amber_cap.stl" inertia="exact"/>
    <material name="cap" rgba="{vec(rig.RIG_MATERIALS["cap"])}" specular="0.5" shininess="0.25"/>
    <texture name="grid" type="2d" builtin="checker" rgb1="0.86 0.87 0.88" rgb2="0.8 0.81 0.82" width="512" height="512"/>
    <material name="floor" texture="grid" texrepeat="8 8" reflectance="0.1"/>
  </asset>

  <worldbody>
    <light name="key" pos="0.4 -0.6 1.2" dir="-0.3 0.5 -1" diffuse="0.7 0.7 0.7" castshadow="true"/>
    <geom name="floor" type="plane" size="1 1 0.05" material="floor"/>
    <camera name="side" pos="0.55 -0.55 0.35" xyaxes="0.707 0.707 0 -0.25 0.25 0.935"/>
    <camera name="front" pos="0.75 0.1 0.3" xyaxes="0 1 0 -0.3 0 0.95"/>

    <body name="lift_link" gravcomp="1">
      <inertial pos="0 0 0" mass="{num(CARRIAGE_MASS)}" diaginertia="0.01 0.01 0.01"/>
      <joint name="lift" type="slide" axis="0 0 1" range="{num(lo)} {num(hi)}" damping="40" armature="1"/>
      <frame pos="{vec((fx, 0, rig.GRIP_Z))}" quat="{vec(rig.TOOL_QUAT)}">
        <attach model="ur10e_iris_pipette" body="ur10e_iris_pipette" prefix=""/>
      </frame>
    </body>

    <body name="bottle" pos="0 0 0">
      <freejoint name="bottle"/>
      <attach model="reference_bottle" body="reference_bottle" prefix=""/>
    </body>
    <body name="cap" pos="0 0 {num(rig.IRIS["bottle_h"])}">
      <freejoint name="cap"/>
{cap_geoms_mjcf('      ')}    </body>
  </worldbody>

  <equality>
    <!-- iris_pipette_plan.attachments(): the bottle rides with the hand while the jaws are closed
         on it, the cap with the bottle until the housing turns and with the clamp after. -->
    <weld name="hold_bottle" body1="bottle" body2="hand_frame" active="false"/>
    <weld name="cap_on_bottle" body1="cap" body2="bottle" active="true"/>
    <weld name="cap_in_clamp" body1="cap" body2="carrier" active="false"/>
  </equality>

  <actuator>
    <position name="lift" joint="lift" kp="10000" kv="800" ctrlrange="{num(lo)} {num(hi)}" forcerange="-300 300"/>
  </actuator>
{keyframe}</mujoco>
''')


def home_keyframe(model: mujoco.MjModel) -> str:
    """qpos and ctrl for the start of the sequence, by joint and actuator name."""
    data = mujoco.MjData(model)
    joints = rig.joint_values(plan.START)
    for name, q in joints.items():
        data.qpos[model.joint(name).qposadr[0]] = q
    data.qpos[model.joint('cap').qposadr[0]:][:7] = [0, 0, rig.IRIS['bottle_h'], 1, 0, 0, 0]
    targets = plan.targets(0.0)
    for name, q in targets.items():
        if name == 'right_driver_joint':
            data.ctrl[model.actuator('fingers_actuator').id] = 255 * q / plan.DRIVER_CLOSED
        else:
            data.ctrl[model.actuator(name).id] = q
    return (f'\n  <keyframe>\n    <key name="home" qpos="{vec(data.qpos)}" ctrl="{vec(data.ctrl)}"/>\n'
            '  </keyframe>\n')


# --- URDF ---------------------------------------------------------------------


def urdf_shape(g: dict, mesh_dir: str) -> str:
    if g['type'] == 'mesh':
        return f'<mesh filename="{mesh_dir}/{mesh_file(g["mesh"])}"/>'
    if g['type'] == 'cone':
        return f'<mesh filename="{mesh_dir}/cone_locator.stl"/>'
    if g['type'] == 'box':
        return f'<box size="{vec(2 * np.asarray(g["size"]))}"/>'
    r, half = g['size']    # cylinder, or a capsule URDF has no shape for
    return f'<cylinder radius="{num(r)}" length="{num(2 * half)}"/>'


def urdf_geom(g: dict, mesh_dir: str) -> str:
    origin = f'      <origin xyz="{vec(g["pos"])}" rpy="{vec(rpy(g["quat"]))}"/>\n'
    if g['collide']:
        return f'    <collision>\n{origin}      <geometry>{urdf_shape(g, mesh_dir)}</geometry>\n    </collision>\n'
    return (f'    <visual>\n{origin}      <geometry>{urdf_shape(g, mesh_dir)}</geometry>\n'
            f'      <material name="{g["material"]}"/>\n    </visual>\n')


def write_rig_urdf(tree: list[dict], ratios: dict[str, float], fx: float, rig_model: mujoco.MjModel) -> None:
    """Carriage + hand + tooling as one fixed-base articulation for Isaac's URDF importer."""
    gripper = mujoco.MjModel.from_xml_path(str(GRIPPER))
    ur_dir = '../third_party/mujoco_menagerie/universal_robots_ur10e/assets'
    mesh_dir = '../assets/ur10e_iris_pipette/meshes'
    materials = ''.join(f'  <material name="{k}"><color rgba="{vec(v)}"/></material>\n'
                        for k, v in {**MATERIALS, **rig.RIG_MATERIALS}.items())
    links, joints = [], []

    def link(name, body='', inertial=None):
        inertial = inertial or inertial_xml(1e-3, (0, 0, 0), (1, 0, 0, 0), (1e-7,) * 3)
        links.append(f'  <link name="{name}">\n{inertial}{body}  </link>\n')

    lo, hi = LIFT_RANGE
    link('rig_base')
    link('lift_link', inertial=inertial_xml(CARRIAGE_MASS, (0, 0, 0), (1, 0, 0, 0), (0.01,) * 3))
    joints.append(joint_xml('lift', 'prismatic', 'rig_base', 'lift_link', axis=(0, 0, 1),
                            limit=LIFT_RANGE, effort=300, velocity=0.5))
    stub_z = STUB_TOP - STUB_LENGTH / 2
    stub = ('    <visual>\n'
            f'      <origin xyz="0 0 {num(stub_z)}" rpy="0 0 0"/>\n'
            f'      <geometry><cylinder radius="{num(STUB_RADIUS)}" length="{num(STUB_LENGTH)}"/></geometry>\n'
            '      <material name="linkgray"/>\n'
            '    </visual>\n'
            '    <visual>\n'
            f'      <origin xyz="0 0 {num(STUB_TOP - RING_HEIGHT / 2)}" rpy="0 0 0"/>\n'
            f'      <geometry><cylinder radius="{num(STUB_RADIUS + 0.001)}" length="{num(RING_HEIGHT)}"/></geometry>\n'
            '      <material name="urblue"/>\n'
            '    </visual>\n')
    link('ur10e_hand', stub, inertial_xml(STUB_MASS, (0, 0, stub_z), (1, 0, 0, 0), (0.002, 0.002, 0.001)))
    joints.append(joint_xml('hand_mount', 'fixed', 'lift_link', 'ur10e_hand',
                            pos=(fx, 0, rig.GRIP_Z), quat=rig.TOOL_QUAT))
    wpos, wquat = wrist3_pose()
    ipos, iquat = wrist3_inertial()
    link('wrist_3_link', mesh_visual(f'{ur_dir}/wrist3.obj', 'linkgray', wpos, wquat),
         inertial_xml(WRIST3_MASS, ipos, iquat, WRIST3_INERTIA))
    joints.append(joint_xml('wrist_3_joint', 'revolute', 'ur10e_hand', 'wrist_3_link',
                            axis=(0, 0, 1), limit=(-2 * math.pi, 2 * math.pi), effort=56, velocity=3.14))
    gripper_urdf(gripper, ratios, 'wrist_3_link', links, joints)

    # The tooling: every body a link at its own frame (the joints sit at the
    # body origins), inertia as MuJoCo computed it from the same geometry.
    for b in tree:
        mb = rig_model.body(b['name'])
        body = ''.join(urdf_geom(g, mesh_dir) for g in b['geoms'] if g['visible'] or g['collide'])
        link(b['name'], body, inertial_xml(mb.mass[0], mb.ipos, mb.iquat, mb.inertia))
        j = b['joint']
        if j is None:
            joints.append(joint_xml(f'{b["name"]}_mount', 'fixed', b['parent'], b['name'], b['pos'], b['quat']))
            continue
        kind = 'prismatic' if j['type'] == 'slide' else 'continuous' if j['range'] is None else 'revolute'
        mimic = (('cam', MIMIC_CAM[j['name']]) if j['name'] in MIMIC_CAM else None)
        effort, velocity = (GAINS.get(j['name'], (0, 0, 5))[2], 2.0)
        joints.append(joint_xml(j['name'], kind, b['parent'], b['name'], b['pos'], b['quat'],
                                axis=j['axis'], limit=j['range'], effort=effort, velocity=velocity, mimic=mimic))

    RIG_URDF.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- {HEADER} -->\n'
        '<!-- The uncap-and-pipette hand on a lift carriage, for Isaac\'s URDF importer (fix the\n'
        f'     base). The 2F-85 is actuated at {ACTUATED} (0 open .. 0.8 closed) and its other\n'
        '     finger joints mimic it; the iris blades and planets mimic the cam ring; sun_input is\n'
        '     a real joint, driven to body_yaw - 3 cam. See iris_pipette_rig.py and the generator. -->\n'
        '<robot name="iris_pipette_rig">\n'
        '  <!-- Hints for MuJoCo\'s URDF loader; ignored by every other importer. -->\n'
        '  <mujoco>\n'
        '    <compiler discardvisual="false" fusestatic="false"/>\n'
        '  </mujoco>\n\n'
        f'{materials}\n' + ''.join(links) + '\n' + ''.join(joints) + '</robot>\n')


def body_inertial(model: mujoco.MjModel, name: str) -> str:
    """A compiled body's mass and inertia, for the URDF."""
    b = model.body(name)
    return inertial_xml(b.mass[0], b.ipos, b.iquat, b.inertia)


def write_bottle_urdfs(scene: mujoco.MjModel) -> None:
    body = ('    <visual>\n      <geometry><mesh filename="meshes/amber_glass.stl"/></geometry>\n'
            f'      <material name="bottle"><color rgba="{vec(rig.RIG_MATERIALS["bottle"])}"/></material>\n    </visual>\n')
    for kind, pos, quat, size in bottle_collision():
        shape = (f'<cylinder radius="{num(size[0])}" length="{num(2 * size[1])}"/>' if kind == 'cylinder'
                 else f'<box size="{vec(2 * np.asarray(size))}"/>')
        body += (f'    <collision>\n      <origin xyz="{vec(pos)}" rpy="{vec(rpy(quat))}"/>\n'
                 f'      <geometry>{shape}</geometry>\n    </collision>\n')
    BOTTLE_URDF.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- {HEADER} -->\n'
        '<!-- reference_bottle.xml as a URDF: the 60 ml amber bottle, one free rigid body, origin at\n'
        '     the base on the axis, +Z up, hollow (a ring of boxes) so the pipette can go down the neck. -->\n'
        '<robot name="reference_bottle">\n  <link name="reference_bottle">\n'
        + body_inertial(scene, 'reference_bottle')
        + body + '  </link>\n</robot>\n')
    CAP_URDF.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- {HEADER} -->\n'
        '<!-- The amber bottle\'s PP25 cap: one free rigid body, origin at its underside on the axis,\n'
        '     +Z up. -->\n'
        '<robot name="reference_cap">\n  <link name="reference_cap">\n'
        + body_inertial(scene, 'cap')
        + '    <visual>\n      <geometry><mesh filename="meshes/amber_cap.stl"/></geometry>\n'
        f'      <material name="cap"><color rgba="{vec(rig.RIG_MATERIALS["cap"])}"/></material>\n    </visual>\n'
        f'    <collision>\n      <origin xyz="0 0 {num(rig.IRIS["cap_h"] / 2)}" rpy="0 0 0"/>\n'
        f'      <geometry><cylinder radius="{num(rig.IRIS["cap_r"])}" length="{num(rig.IRIS["cap_h"])}"/></geometry>\n'
        '    </collision>\n  </link>\n</robot>\n')


# --- checks -----------------------------------------------------------------------


def check_kinematics(model: mujoco.MjModel, tree: list[dict], fx: float) -> None:
    """MuJoCo's forward kinematics of the scene against iris_pipette_rig.fk at
    the states the sequence passes through.

    Raises:
        RuntimeError: If a site or body is off by more than a micrometre.
    """
    data = mujoco.MjData(model)
    worst = 0.0
    for n in (3, 6, 8, 10, 13):
        state, _ = plan.state_at(plan.step_end(n) - 1e-6)
        joints = rig.joint_values(state)
        for name, q in joints.items():
            data.qpos[model.joint(name).qposadr[0]] = q
        mujoco.mj_kinematics(model, data)
        root = {'wrist_3_link': (np.array([fx, 0, rig.GRIP_Z + state['lift_z']]), np.array(rig.TOOL_QUAT))}
        poses = rig.fk(tree, joints, root)
        for name in ('pipette_tip', 'cap_seat'):
            worst = max(worst, float(np.linalg.norm(data.site(name).xpos - poses[name][0])))
        for name in ('pipette_swing', 'blade_3', 'clamp_mount'):
            worst = max(worst, float(np.linalg.norm(data.body(name).xpos - poses[name][0])))
    print(f'MuJoCo kinematics vs iris_pipette_rig.fk: within {worst * 1e6:.2f} um')
    if worst > 1e-6:
        raise RuntimeError('the MJCF and the rig tree disagree')


def check_urdf_kinematics(model: mujoco.MjModel, tree: list[dict], fx: float) -> None:
    """The URDF, loaded in MuJoCo, against iris_pipette_rig.fk: every joint set
    (the mimicked ones too), the bodies must sit where the tree puts them.

    Raises:
        RuntimeError: If a body is off by more than 10 um (the URDF's numbers
            are written to six significant digits).
    """
    data = mujoco.MjData(model)
    worst = 0.0
    for n in (3, 6, 8, 10, 13):
        state, _ = plan.state_at(plan.step_end(n) - 1e-6)
        joints = rig.joint_values(state)
        for name, q in joints.items():
            data.qpos[model.joint(name).qposadr[0]] = q
        mujoco.mj_kinematics(model, data)
        root = {'wrist_3_link': (np.array([fx, 0, rig.GRIP_Z + state['lift_z']]), np.array(rig.TOOL_QUAT))}
        poses = rig.fk(tree, joints, root)
        for name in ('pipette_swing', 'pipette_plunger', 'blade_3', 'planet_1', 'clamp_mount', 'carrier'):
            worst = max(worst, float(np.linalg.norm(data.body(name).xpos - poses[name][0])))
    print(f'URDF kinematics vs iris_pipette_rig.fk: within {worst * 1e6:.2f} um')
    if worst > 1e-5:
        raise RuntimeError('the URDF and the rig tree disagree')


def main() -> None:
    closed, opened, fits = linkage()
    fx = flange_x(pad_fit(mujoco.MjModel.from_xml_path(str(GRIPPER)), fits))
    rig.check_clearances()
    tree = rig.tree(fx)
    ratios = mimic_ratios()

    write_meshes()
    write_rig_mjcf(tree)
    write_bottle_mjcf()
    write_scene_mjcf(fx)
    scene = mujoco.MjModel.from_xml_path(str(SCENE_XML))
    write_scene_mjcf(fx, home_keyframe(scene))
    scene = mujoco.MjModel.from_xml_path(str(SCENE_XML))
    check_kinematics(scene, tree, fx)
    write_rig_urdf(tree, ratios, fx, mujoco.MjModel.from_xml_path(str(RIG_XML)))
    write_bottle_urdfs(scene)
    check_urdf_kinematics(mujoco.MjModel.from_xml_path(str(RIG_URDF)), tree, fx)
    for path in (RIG_XML, BOTTLE_XML, SCENE_XML, RIG_URDF, BOTTLE_URDF, CAP_URDF):
        m = mujoco.MjModel.from_xml_path(str(path))   # every file must at least load
        print(f'wrote {path.relative_to(SIM)}: {m.nbody} bodies, {m.njnt} joints, {m.neq} equalities')


if __name__ == '__main__':
    main()
