#!/usr/bin/env python3
"""Make open, part-filled copies of the catalogue's flasks, for pipetting into.

Run from simulation/: python scripts/generate_open_vessels.py.
generate_rail_scene.py calls it for the vessels it puts on the bench.

The catalogue's vessels are capped and empty. This writes a copy of each one
under assets/open_vessels/ with the cap geom gone, a liquid column inside, and
a site at the mouth so the pipetting code has something to aim at. Nothing else
changes: the same meshes, the same label texture, the same mass.

Fill levels are drawn from a seeded generator as a fraction of what the flask
actually holds --- measured off its own mesh, not off the catalogue's nominal
capacity, so the column can never stand above the shoulder.
"""
import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path

import numpy as np

SIM = Path(__file__).resolve().parents[1]
CATALOGUE = SIM / 'assets/labelled_bottles'
OUT = SIM / 'assets/open_vessels'
HEADER = '<!-- Generated by scripts/generate_open_vessels.py; do not edit by hand. -->\n'

FILL_RANGE = (0.25, 0.75)   # fraction of the flask's own usable volume
FILL_SEED = 41
LIQUID_RGBA = '0.86 0.62 0.18 0.55'


@dataclass(frozen=True)
class Bore:
    """The inside of a flask, measured from its glass mesh.

    Attributes:
        inner_radius: Radius of the inner wall through the body, in metres.
        floor: Height of the inside of the base above the flask's origin.
        shoulder: Height where the body starts tapering into the neck.
        mouth: Height of the rim.
        mouth_radius: Radius of the opening at the rim.
        outer_radius: Outside radius of the body, in metres.
        neck_radius: Outside radius of the neck, in metres.
    """

    inner_radius: float
    floor: float
    shoulder: float
    mouth: float
    mouth_radius: float
    outer_radius: float = 0.0
    neck_radius: float = 0.0

    @property
    def capacity(self) -> float:
        """Usable volume in millilitres, as a straight cylinder to the shoulder."""
        return np.pi * self.inner_radius**2 * (self.shoulder - self.floor) * 1e6

    def column(self, millilitres: float) -> tuple[float, float]:
        """Centre height and half-height of a liquid column of this volume."""
        height = min(millilitres * 1e-6 / (np.pi * self.inner_radius**2),
                     self.shoulder - self.floor)
        return self.floor + height / 2, max(height / 2, 1e-5)


WALL = 0.002        # glass wall thickness, m
SHOULDER = 0.72     # where the body starts tapering, as a fraction of height
FLOOR = 0.003       # thickness of the base, m
STAVES = 12         # convex pieces per ring of the collision shell


def measure(mesh: Path, diameter: float, height: float) -> Bore:
    """Work out the inside of a flask.

    The body comes from the catalogue's own dimensions rather than from the
    mesh. The meshes are lathed at wildly different resolutions --- one class
    has 5000 vertices on a few dozen profile rings, another has 437 rings with
    the base cap mixed in --- and every heuristic for finding the shoulder in
    that data broke on one class or another. Nominal dimensions minus a wall
    are predictable and good enough for a liquid level.

    The mouth is taken from the mesh, because that one is robust: above the
    shoulder the neck is the only thing there, so the smallest radius is the
    bore, and it is the number the pipette has to fit through.

    Args:
        mesh: Path to the glass .obj.
        diameter: Outside diameter of the body, in metres.
        height: Overall height, in metres.

    Returns:
        The bore.
    """
    points = np.array([[float(v) for v in line.split()[1:4]]
                       for line in mesh.read_text().splitlines()
                       if line.startswith('v ')])
    radius = np.hypot(points[:, 0], points[:, 1])
    # The neck is the top tenth. Taking everything above the shoulder instead
    # catches the widest part of the taper, and puts the neck ring 3 mm too far
    # out --- wide enough for a tip to drop past it.
    above = points[:, 2] - points[:, 2].min() > height * 0.92
    return Bore(inner_radius=diameter / 2 - WALL,
                floor=FLOOR,
                shoulder=height * SHOULDER,
                mouth=height,
                mouth_radius=float(radius[above].min()),
                outer_radius=diameter / 2,
                neck_radius=float(radius[above].max()))


def bores() -> dict[str, Bore]:
    """Measure every vessel class the catalogue uses."""
    manifest = json.loads((CATALOGUE / 'manifest.json').read_text())
    out = {}
    for name, spec in manifest['vessels'].items():
        mesh = CATALOGUE / f'meshes/{name}_glass.obj'
        if mesh.exists():
            out[name] = measure(mesh, spec['diameter_m'], spec['height_m'])
    return out


def fills(samples: list[str], shapes: dict[str, Bore],
          classes: dict[str, str]) -> dict[str, float]:
    """Pick how much liquid each sample holds, in millilitres.

    Args:
        samples: Sample ids to fill.
        shapes: Bore per vessel class.
        classes: Vessel class per sample id.

    Returns:
        Millilitres per sample, always inside what that flask can hold.
    """
    manifest = json.loads((CATALOGUE / 'manifest.json').read_text())
    rng = np.random.default_rng(FILL_SEED)
    out = {}
    for sample in sorted(samples):
        shape = shapes[classes[sample]]
        nominal = manifest['vessels'][classes[sample]]['container_ml']
        out[sample] = round(min(float(rng.uniform(*FILL_RANGE)) * nominal,
                                shape.capacity), 2)
    return out


def build(sample: str, bore: Bore, millilitres: float) -> Path:
    """Write one open, part-filled vessel.

    Args:
        sample: Catalogue id, e.g. ``SMP-0084``.
        bore: The measured inside of its flask.
        millilitres: How much liquid to put in it.

    Returns:
        Path of the generated MJCF.
    """
    import mujoco

    original = mujoco.MjModel.from_xml_path(str(CATALOGUE / f'{sample}.xml'))
    mass = float(original.body_subtreemass[1])
    inertia = original.body_inertia[1]
    centre_of_mass = original.body_ipos[1]

    xml = (CATALOGUE / f'{sample}.xml').read_text()
    xml = xml.replace('file="meshes/', 'file="../labelled_bottles/meshes/')
    xml = xml.replace('file="textures/', 'file="../labelled_bottles/textures/')
    # Open it: the cap and its sticker are geoms of their own, so the flask opens
    # by deleting two lines. Unscrewing it is a different job and needs it to be
    # its own body.
    xml = re.sub(r'\n\s*<geom name="cap(?:_label)?".*?/>', '', xml)
    xml = re.sub(r'\n\s*<(?:mesh|texture|material) name="(?:\w+_)?cap_label"[^>]*/>', '', xml)
    # The glass keeps its looks and gives up its collision to the shell below.
    xml = re.sub(r'(<geom name="glass"[^/]*?)density="\d+"',
                 r'\1contype="0" conaffinity="0" mass="0"', xml)
    # Mass came from the glass geom's density, so it has to be restated.
    xml = xml.replace(f'<body name="{sample}">',
                      f'<body name="{sample}">\n'
                      f'      <inertial pos="{centre_of_mass[0]:.5f} '
                      f'{centre_of_mass[1]:.5f} {centre_of_mass[2]:.5f}" '
                      f'mass="{mass:.5f}"\n'
                      f'                diaginertia="{inertia[0]:.3e} '
                      f'{inertia[1]:.3e} {inertia[2]:.3e}"/>')

    centre, half = bore.column(millilitres)
    xml = xml.replace('    </body>',
                      shell(bore) + '\n'
                      f'      <geom name="liquid" type="cylinder" '
                      f'pos="0 0 {centre:.5f}"\n'
                      f'            size="{bore.inner_radius:.5f} {half:.5f}" '
                      f'rgba="{LIQUID_RGBA}"\n'
                      f'            contype="0" conaffinity="0" mass="0"/>\n'
                      f'      <site name="mouth" pos="0 0 {bore.mouth:.5f}" '
                      f'size="{bore.mouth_radius:.5f} 0.001" type="cylinder"\n'
                      f'            rgba="0.2 0.7 0.9 0.25" group="4"/>\n'
                      '    </body>')
    xml = xml.replace(f'<mujoco model="{sample}">',
                      f'<mujoco model="{sample}_open">\n  ' + HEADER.strip())

    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f'{sample}.xml'
    path.write_text(xml)
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('samples', nargs='*', help='catalogue ids to open')
    args = parser.parse_args()

    manifest = json.loads((CATALOGUE / 'manifest.json').read_text())
    classes = {k: v['vessel_class'] for k, v in manifest['samples'].items()}
    shapes = bores()
    print('vessel classes, measured off their own meshes:')
    for name, bore in shapes.items():
        print(f'  {name:14s} bore radius {bore.inner_radius * 1000:5.1f} mm, '
              f'mouth radius {bore.mouth_radius * 1000:5.1f} mm, '
              f'holds {bore.capacity:6.1f} ml '
              f'(catalogue says {manifest["vessels"][name]["container_ml"]:.0f})')

    samples = args.samples or sorted(classes)[:12]
    volumes = fills(samples, shapes, classes)
    for sample in samples:
        build(sample, shapes[classes[sample]], volumes[sample])
    print(f'\nwrote {len(samples)} open vessels to {OUT.relative_to(SIM)}')
    for sample in samples:
        print(f'  {sample}  {classes[sample]:14s} {volumes[sample]:6.2f} ml')




def main_for(samples: list[str]) -> dict[str, float]:
    """Generate open, filled copies of exactly these samples.

    Called by generate_rail_scene.py for the vessels it puts on the bench.

    Args:
        samples: Catalogue ids.

    Returns:
        Millilitres placed in each one.
    """
    manifest = json.loads((CATALOGUE / 'manifest.json').read_text())
    classes = {k: v['vessel_class'] for k, v in manifest['samples'].items()}
    shapes = bores()
    volumes = fills(samples, shapes, classes)
    for sample in samples:
        build(sample, shapes[classes[sample]], volumes[sample])
    return volumes


def shell(bore: Bore) -> str:
    """Collision geometry that leaves the inside of a flask open.

    MuJoCo collides a mesh as its convex hull, so the glass mesh is a solid
    slug and nothing can be put inside it. Replacing it with rings of boxes ---
    a barrel's staves --- keeps the outside solid, so the arm still cannot
    reach through a flask and still knocks it over, while the bore stays open
    for a pipette tip.

    Three rings, because the flasks are not straight: the body, the shoulder
    where it tapers, and the neck. Plus a disc for the base.

    Args:
        bore: The measured flask.

    Returns:
        MJCF geom elements, as text.
    """
    neck_start = bore.shoulder + (bore.mouth - bore.shoulder) * 0.35
    rings = (
        ('body', bore.outer_radius, bore.floor, bore.shoulder),
        ('shoulder', (bore.outer_radius + bore.neck_radius) / 2,
         bore.shoulder, neck_start),
        ('neck', bore.neck_radius, neck_start, bore.mouth),
    )
    out = []
    for name, radius, lo, hi in rings:
        mid = radius - WALL / 2
        # Each stave has to be wider than the arc it covers, or the ring is a
        # picket fence: at 0.62 of the spacing the gaps were 3.6 mm and a
        # 2.7 mm tip went straight between two of them. Geoms in one body do
        # not collide with each other, so overlapping them costs nothing.
        width = 2 * np.pi * mid / STAVES * 1.25
        for i in range(STAVES):
            angle = 2 * np.pi * i / STAVES
            out.append(
                f'      <geom name="{name}_{i:02d}" type="box" '
                f'pos="{mid * np.cos(angle):.5f} {mid * np.sin(angle):.5f} '
                f'{(lo + hi) / 2:.5f}"\n'
                f'            size="{WALL / 2:.5f} {width / 2:.5f} '
                f'{(hi - lo) / 2:.5f}" euler="0 0 {np.degrees(angle):.3f}"\n'
                f'            rgba="0 0 0 0" mass="0" group="3"/>')
    out.append(
        f'      <geom name="base" type="cylinder" pos="0 0 {bore.floor / 2:.5f}"\n'
        f'            size="{bore.outer_radius:.5f} {bore.floor / 2:.5f}"\n'
        f'            rgba="0 0 0 0" mass="0" group="3"/>')
    return '\n'.join(out)


if __name__ == '__main__':
    main()
