#!/usr/bin/env python3
"""Cut the roof off a balance so a pipette can reach the pan.

Run from simulation/: python scripts/generate_open_balance.py.
generate_rail_scene.py swaps one of the scene's balances for the result.

The converted balance is a closed draft shield 311 mm tall with a single box
for collision --- no pan, no opening, so nothing can be stood on it and nothing
can be dropped into it. This trims every mesh above `CUT`, leaving an
open-topped enclosure, and replaces the collision box with the three surfaces
that matter: the housing, the weighing pan, and the shield walls, so the arm
still cannot sweep through them.

Measured off the original parts: the chamber floor is at 58 mm, the pan at
77 mm, and the shield runs from 65 mm to 306 mm.
"""
from pathlib import Path

import numpy as np

SIM = Path(__file__).resolve().parents[1]
SOURCE = SIM / 'assets/balance'
OUT = SIM / 'assets/balance_open'
HEADER = '<!-- Generated by scripts/generate_open_balance.py; do not edit by hand. -->\n'

CUT = 0.200         # everything above this comes off, in the balance's frame
PAN_TOP = 0.077     # top of the weighing pan
PAN = (-0.005, 0.031)   # pan centre in x and y
CHAMBER = 0.058     # floor of the weighing chamber
SHIELD_X = 0.100    # inside half-width of the shield
SHIELD_Y = (-0.059, 0.115)


def trim(path: Path, cut: float) -> tuple[Path, bool]:
    """Copy an .obj, dropping every face that reaches above `cut`.

    Args:
        path: Source mesh.
        cut: Height above which geometry is removed.

    Returns:
        The written path, and whether anything survived.
    """
    vertices, faces, other = [], [], []
    for line in path.read_text().splitlines():
        if line.startswith('v '):
            vertices.append([float(v) for v in line.split()[1:4]])
        elif line.startswith('f '):
            faces.append(line)
        elif not line.startswith(('vn ', 'vt ')):
            other.append(line)

    points = np.array(vertices) if vertices else np.zeros((0, 3))
    keep = points[:, 2] <= cut if len(points) else np.zeros(0, dtype=bool)
    # Only the vertices the surviving faces use, renumbered. Leaving the
    # orphans in keeps the mesh's bounding box at its old height, which is
    # exactly what this is trying to lower.
    surviving, remap, out_faces = [], {}, []
    for face in faces:
        idx = [int(token.split('/')[0]) - 1 for token in face.split()[1:]]
        if not all(0 <= i < len(keep) and keep[i] for i in idx):
            continue
        for i in idx:
            if i not in remap:
                remap[i] = len(surviving)
                surviving.append(points[i])
        out_faces.append('f ' + ' '.join(str(remap[i] + 1) for i in idx))

    OUT.mkdir(parents=True, exist_ok=True)
    target = OUT / path.name
    body = '\n'.join(f'v {x:.6f} {y:.6f} {z:.6f}' for x, y, z in surviving)
    target.write_text('\n'.join(other) + '\n' + body + '\n'
                      + '\n'.join(out_faces) + '\n')
    return target, bool(out_faces)


def main() -> None:
    parts = sorted(SOURCE.glob('part_*.obj'))
    kept = []
    for part in parts:
        _, alive = trim(part, CUT)
        kept.append((part.stem, alive))
    print(f'trimmed {len(parts)} parts at {CUT * 1000:.0f} mm; '
          f'{sum(a for _, a in kept)} still have geometry')

    source = (SOURCE / 'balance.xml').read_text()
    meshes = '\n'.join(
        f'    <mesh name="{stem}" file="{stem}.obj" inertia="shell"/>'
        for stem, alive in kept if alive)
    visuals = '\n'.join(
        f'      <geom type="mesh" mesh="{stem}" rgba="{rgba}" '
        f'contype="0" conaffinity="0" density="0" group="1"/>'
        for (stem, alive), rgba in zip(kept, [
            '0.420 0.431 0.482 1', '0.863 0.863 0.863 1', '0.392 0.584 0.929 1',
            '0.255 0.412 0.882 1', '0.227 0.227 0.227 1', '0.700 0.700 0.700 0.48',
            '0.667 0.667 0.667 1', '1.000 0.600 0.196 1', '0.882 0.882 0.784 1',
            '1.000 1.000 1.000 1', '0.757 0.757 0.757 1']) if alive)
    assert 'balance_collision' in source     # the file we measured is still there

    walls = []
    for name, pos, size in (
            ('shield_left', (-SHIELD_X, sum(SHIELD_Y) / 2, (CHAMBER + CUT) / 2),
             (0.003, (SHIELD_Y[1] - SHIELD_Y[0]) / 2, (CUT - CHAMBER) / 2)),
            ('shield_right', (SHIELD_X, sum(SHIELD_Y) / 2, (CHAMBER + CUT) / 2),
             (0.003, (SHIELD_Y[1] - SHIELD_Y[0]) / 2, (CUT - CHAMBER) / 2)),
            ('shield_back', (0, SHIELD_Y[1], (CHAMBER + CUT) / 2),
             (SHIELD_X, 0.003, (CUT - CHAMBER) / 2)),
            ('shield_front', (0, SHIELD_Y[0], (CHAMBER + CUT) / 2),
             (SHIELD_X, 0.003, (CUT - CHAMBER) / 2))):
        walls.append(f'      <geom name="{name}" type="box" '
                     f'pos="{pos[0]:.4f} {pos[1]:.4f} {pos[2]:.4f}"\n'
                     f'            size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}" '
                     f'rgba="0 0 0 0" mass="0" group="3"/>')

    xml = f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}<mujoco model="balance_open">
  <asset>
{meshes}
  </asset>
  <worldbody>
    <body name="balance">
{visuals}
      <geom name="housing" type="box" pos="0 0 {CHAMBER / 2:.4f}"
            size="0.1050 0.1497 {CHAMBER / 2:.4f}" mass="6" group="3"
            rgba="0 0 0 0"/>
      <geom name="pan" type="box" pos="{PAN[0]:.4f} {PAN[1]:.4f} {PAN_TOP - 0.005:.4f}"
            size="0.0430 0.0430 0.0050" mass="0.05" group="3"
            rgba="0.75 0.76 0.78 1"/>
{chr(10).join(walls)}
      <site name="pan" pos="{PAN[0]:.4f} {PAN[1]:.4f} {PAN_TOP:.4f}"
            size="0.04 0.001" type="cylinder" rgba="0.2 0.7 0.9 0.2" group="4"/>
    </body>
  </worldbody>
</mujoco>
'''
    (OUT / 'balance_open.xml').write_text(xml)
    print(f'wrote {(OUT / "balance_open.xml").relative_to(SIM)}')
    print(f'pan at {PAN_TOP * 1000:.0f} mm, shield now open above '
          f'{CUT * 1000:.0f} mm (was closed at 306 mm)')


if __name__ == '__main__':
    main()
