#!/usr/bin/env python3
"""Build the vertical uncap-and-pipette hand of gripper-design/vertical_hand.html for Blender, MuJoCo and Isaac Lab.

Run from simulation/ (needs Blender as a module, which only ships for 3.11):

    uv run --no-project --python 3.11 --with bpy --with mujoco \\
        python scripts/generate_vertical_hand_blend.py

Writes, under ``assets/vertical_hand/``:

* ``vertical_hand.blend`` --- the hand rigged: every joint an empty driven by
  a custom property on the ``vertical_hand`` root (the names of
  vertical_hand_rig.STATE), the 23-step sequence keyframed at 30 fps, the
  reference 60 ml bottle and its cap changing hands by the page's rule
  (Child Of constraints switched by drivers).
* ``vertical_hand.glb`` (+Y up, the sequence baked) and ``vertical_hand.usdc``
  (Blender's USD exporter, animation baked) --- for viewers and for Isaac Sim's
  stage.
* ``meshes/*.stl`` --- one visual mesh per link and material, in the link's
  joint frame, binary STL.
* ``vertical_hand.xml`` --- the MJCF of the hand alone: 20 joints, 9 of them
  actuated, the rest following through joint equalities (MuJoCo).
* ``vertical_hand_scene.xml`` --- the hand over a floor with the bottle and
  the cap as free bodies, the three welds the page's parenting rule switches
  and a ``home`` keyframe; vertical_hand_play.py plays the sequence on it.
* ``vertical_hand.urdf`` --- the same tree for Isaac Lab's URDF importer
  (followers as ``<mimic>``), meshes by relative path.

The four are checked against vertical_hand_rig.fk at the end of several steps
before anything is saved: the .blend's evaluated empties, the MJCF's sites and
the URDF's links (loaded in MuJoCo) must all agree to a micrometre.
"""
import math
import struct
import sys
from pathlib import Path

import bpy
import bmesh  # noqa: E402  (a built-in of bpy, importable only after it)
import mujoco
import numpy as np
from mathutils import Matrix, Vector

sys.path.insert(0, str(Path(__file__).resolve().parent))
import vertical_hand_rig as rig  # noqa: E402
from vertical_hand_rig import (ARM, BEAM, BTN_TOP, CAR, CARRIAGE, CLIPS, COMB_GAP, COMB_X, DEG, FLANGE, FLANGE_C,  # noqa: E402
                               FLANGE_Z, GRIP_Z, HUB_HALF, IRIS, JAW, MAST_BOTTOM, MM, PIP, PIVOT, RAIL, RAIL_TOP,
                               SPINE, STRUT_Y, TAU, TIP_DIVE, YOKE_Y, Z_IRIS, parab)

SIM = Path(__file__).resolve().parents[1]
OUT_DIR = SIM / 'assets/vertical_hand'
MESH_DIR = OUT_DIR / 'meshes'
BLEND = OUT_DIR / 'vertical_hand.blend'
HAND_XML = OUT_DIR / 'vertical_hand.xml'
SCENE_XML = OUT_DIR / 'vertical_hand_scene.xml'
URDF = OUT_DIR / 'vertical_hand.urdf'
FPS = 30
HEADER = 'Generated by scripts/generate_vertical_hand_blend.py from scripts/vertical_hand_rig.py; do not edit by hand.'
B = rig.BOTTLE

# The page's materials: sRGB colour, metallic, roughness (+ extras)
MATERIALS = {
    'linkgray': ((0.82, 0.82, 0.82), 0.35, 0.4), 'urblue': ((0.49, 0.678, 0.8), 0.1, 0.45),
    'black': ((0.12, 0.13, 0.15), 0.35, 0.5), 'gray': ((0.4627, 0.49, 0.53), 0.6, 0.38),
    'liner': ((0.13, 0.14, 0.16), 0.0, 0.92), 'steel': ((0.75, 0.76, 0.78), 0.9, 0.25),
    'bolt': ((0.2, 0.21, 0.23), 0.6, 0.4), 'gold': ((0.83, 0.65, 0.24), 0.7, 0.35),
    'housing': ((0.09, 0.10, 0.11), 0.4, 0.5), 'white': ((0.93, 0.93, 0.92), 0.05, 0.45),
    'blue': ((0.41, 0.58, 0.87), 0.05, 0.4), 'dark': ((0.06, 0.06, 0.07), 0.1, 0.35),
    'display': ((0.02, 0.02, 0.02), 0.1, 0.15), 'led': ((0.21, 0.76, 0.42), 0.0, 0.3),
    'bottle': ((0.62, 0.28, 0.05), 0.05, 0.2), 'liquid': ((0.31, 0.61, 0.85), 0.0, 0.1),
    'cap': ((0.93, 0.93, 0.91), 0.05, 0.5),
}
ALPHA = {'bottle': 0.55, 'liquid': 0.6}
# Who touches whom in MuJoCo: (contype, conaffinity) bits. pads<->bottle, blades<->cap, tip<->bottle/floor, floor<->bottle/cap/tip
COLLIDE = {'pad': (1, 2), 'bottle': (2, 1 | 16 | 32), 'blade': (4, 8), 'cap': (8, 4 | 32), 'tip': (16, 2 | 32), 'floor': (32, 2 | 8 | 16)}
GAINS = {   # kp, kv, force for the position actuators: stiff enough to track the page's speeds within 3 mm / 10 mrad
    'lift': (100000.0, 1000.0, 600.0), 'jaw_l': (2000.0, 20.0, 60.0), 'clamp_y': (20000.0, 300.0, 200.0),
    'clamp_lift': (20000.0, 200.0, 200.0), 'body_yaw': (500.0, 1.0, 20.0), 'cam': (100.0, 1.0, 10.0),
    'pip_slide': (20000.0, 300.0, 200.0), 'pip_swing': (500.0, 2.0, 10.0), 'plunger': (500.0, 5.0, 20.0),
}
CHECK_STEPS = (2, 5, 7, 9, 12, 17, 23)


# ============================== meshes (mm in) ==============================
def cyl(r0, r1, z0, z1, n=48):
    """A cylinder or cone along Z, radius r0 at z0 and r1 at z1."""
    return lathe([(0, z0), (r0, z0), (r1, z1), (0, z1)], n)


def ring(ro, ri, z0, z1, n=96):
    return lathe([(ri, z0), (ro, z0), (ro, z1), (ri, z1), (ri, z0)], n)


def lathe(pts, n=72):
    """Revolve a (r, z) profile about Z; r = 0 points become one vertex."""
    verts, rows = [], []
    for r, z in pts:
        if r > 1e-6:
            rows.append(list(range(len(verts), len(verts) + n)))
            verts += [(r * math.cos(k * TAU / n), r * math.sin(k * TAU / n), z) for k in range(n)]
        else:
            rows.append(len(verts))
            verts.append((0.0, 0.0, z))
    faces = []
    for a, b in zip(rows, rows[1:]):
        for k in range(n):
            k1 = (k + 1) % n
            if isinstance(a, list) and isinstance(b, list):
                faces.append((a[k], a[k1], b[k1], b[k]))
            elif isinstance(a, list):
                faces.append((a[k], a[k1], b))
            elif isinstance(b, list):
                faces.append((a, b[k1], b[k]))
    return verts, faces


def box(x0, x1, y0, y1, z0, z1):
    v = [(x, y, z) for z in (z0, z1) for y in (y0, y1) for x in (x0, x1)]
    f = [(0, 2, 3, 1), (4, 5, 7, 6), (0, 1, 5, 4), (2, 6, 7, 3), (0, 4, 6, 2), (1, 3, 7, 5)]
    return v, f


def rb(axis, a0, a1, b, c, sb, sc, r):
    """The page's softened box: extruded along `axis` from a0 to a1, centred on (b, c) across
    ('x': b=y c=z, 'y': b=x c=z, 'z': b=x c=y), sb x sc across, edges rounded by r."""
    if axis == 'x':
        v, f = box(a0, a1, b - sb / 2, b + sb / 2, c - sc / 2, c + sc / 2)
    elif axis == 'y':
        v, f = box(b - sb / 2, b + sb / 2, a0, a1, c - sc / 2, c + sc / 2)
    else:
        v, f = box(b - sb / 2, b + sb / 2, c - sc / 2, c + sc / 2, a0, a1)
    return v, f, min(r, (a1 - a0) / 2.5, sb / 2.5, sc / 2.5)


def slab(poly, z0, z1):
    """A polygon in XY extruded from z0 to z1."""
    n = len(poly)
    v = [(x, y, z0) for x, y in poly] + [(x, y, z1) for x, y in poly]
    f = [tuple(range(n))[::-1], tuple(range(n, 2 * n))]
    f += [(k, (k + 1) % n, n + (k + 1) % n, n + k) for k in range(n)]
    return v, f


def arc(x0, x1, fn, side, n=48):
    return [(x0 + (x1 - x0) * i / n, side * fn(x0 + (x1 - x0) * i / n)) for i in range(n + 1)]


def outer(x):
    return JAW['liner'] + JAW['plate'] - max(0.0, x * x - HUB_HALF ** 2) / (2 * JAW['p'])


def liner_poly(x0, x1, side):
    return arc(x0, x1, parab, side) + arc(x1, x0, lambda x: parab(x) + JAW['liner'], side)


def plate_poly(x0, x1, side):
    return arc(x0, x1, lambda x: parab(x) + JAW['liner'], side) + arc(x1, x0, lambda x: parab(x) + outer(x), side)


def wing_bands(side):
    H, third = JAW['half_height'], (2 * JAW['half_height'] - 2 * COMB_GAP) / 3
    return [(-H, -H + third), (H - third, H)] if side > 0 else [(-H + third + COMB_GAP, H - third - COMB_GAP)]


def pad_boxes(side):
    """The liner as chord boxes MuJoCo can collide with: (pos, yaw, half size) in the jaw frame (m).

    Each box sits on its chord, pushed out by half the sag so it straddles the parabola.
    """
    out = []
    W, C, H = JAW['half_width'], COMB_X, JAW['half_height']
    for z0, z1 in [(-H, H)] + wing_bands(side):
        ranges = [(-C, C)] if (z0, z1) == (-H, H) else [(C, W), (-W, -C)]
        for x0, x1 in ranges:
            n = max(2, round((x1 - x0) / 4))
            for i in range(n):
                xa, xb = x0 + (x1 - x0) * i / n, x0 + (x1 - x0) * (i + 1) / n
                ya, yb = side * parab(xa), side * parab(xb)
                yaw = math.atan2(yb - ya, xb - xa)
                sag = (xb - xa) ** 2 / (8 * JAW['p'])
                length = math.hypot(xb - xa, yb - ya)
                nx, ny = -math.sin(yaw), math.cos(yaw)         # the chord's normal, toward +y
                off = side * (JAW['liner'] / 2 + sag / 2)       # the liner is on the +y side of the arc for the +y jaw
                cx, cy = (xa + xb) / 2 + nx * off, (ya + yb) / 2 + ny * off
                out.append(((cx * MM, cy * MM, (z0 + z1) / 2 * MM), yaw, (length / 2 * MM, JAW['liner'] / 2 * MM, (z1 - z0) / 2 * MM)))
    return out


def bottle_profile(b):
    R, hs = b['r'], b['neck'] - b['shoulder']
    pts = [(0, 1), (R - 3, 1), (R - 0.8, 0), (R, 2.5), (R, b['shoulder'])]
    for i in range(1, 9):
        t = i / 8
        e = math.sin(t * math.pi / 2)
        pts.append((R + (b['neck_r'] - R) * e, b['shoulder'] + hs * t))
    pts += [(b['neck_r'], b['h']), (b['neck_r'] - 2, b['h']), (b['neck_r'] - 2, b['shoulder'] + 2), (0, b['shoulder'] + 2)]
    return pts


def cap_profile(b):
    c = b['cap_r']
    return [(0, 0), (c - 0.9, 0), (c - 0.3, 0.6), (c - 0.3, b['cap_h'] - 1.2), (c - 1.5, b['cap_h']), (0, b['cap_h'])]


# ============================== Blender ==============================
def srgb_to_linear(c):
    return tuple(((x + 0.055) / 1.055) ** 2.4 if x > 0.04045 else x / 12.92 for x in c)


def material(name):
    mat = bpy.data.materials.get(name)
    if mat is not None:
        return mat
    rgb, metallic, roughness = MATERIALS[name]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes['Principled BSDF']
    lin = srgb_to_linear(rgb)
    alpha = ALPHA.get(name, 1.0)
    bsdf.inputs['Base Color'].default_value = (*lin, 1.0)
    bsdf.inputs['Metallic'].default_value = metallic
    bsdf.inputs['Roughness'].default_value = roughness
    mat.diffuse_color = (*lin, alpha)
    if name == 'led':
        bsdf.inputs['Emission Color'].default_value = (*lin, 1.0)
        bsdf.inputs['Emission Strength'].default_value = 4.0
    if alpha < 1:
        bsdf.inputs['Alpha'].default_value = alpha
        try:
            mat.surface_render_method = 'BLENDED'
        except AttributeError:
            mat.blend_method = 'BLEND'
    return mat


def empty(name, parent=None, pos=(0, 0, 0), yaw=0.0, size=0.02):
    obj = bpy.data.objects.new(name, None)
    obj.empty_display_type = 'ARROWS'
    obj.empty_display_size = size
    bpy.context.scene.collection.objects.link(obj)
    obj.parent = parent
    obj.location = pos
    obj.rotation_mode = 'XYZ'
    obj.rotation_euler = (0, 0, yaw)
    return obj


def part(name, parent, mesh, mat, pos=(0, 0, 0), yaw=0.0, bevel=0.0, smooth_angle=35.0):
    """One mesh object (mm in, metres out) under a link, with sharp edges by angle."""
    verts, faces = mesh[0], mesh[1]
    if len(mesh) == 3:
        bevel = mesh[2]
    me = bpy.data.meshes.new(name)
    me.from_pydata([tuple(c * MM for c in v) for v in verts], [], faces)
    bm = bmesh.new()
    bm.from_mesh(me)
    bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-7)
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    if bevel > 0:
        bmesh.ops.bevel(bm, geom=bm.edges[:], offset=bevel * MM, offset_type='OFFSET', segments=2, profile=0.5,
                        affect='EDGES', clamp_overlap=True)
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    for f in bm.faces:
        f.smooth = True
    for e in bm.edges:
        angle = e.calc_face_angle(None)
        e.smooth = angle is not None and angle < smooth_angle * DEG
    bm.to_mesh(me)
    bm.free()
    me.validate()
    me.update()
    me.materials.append(material(mat))
    obj = bpy.data.objects.new(name, me)
    bpy.context.scene.collection.objects.link(obj)
    obj.parent = parent
    obj.location = tuple(c * MM for c in pos)
    obj.rotation_mode = 'XYZ'
    obj.rotation_euler = (0, 0, yaw)
    return obj


def add_driver(obj, path, index, root, prop, expr):
    fcurve = obj.driver_add(path, index)
    driver = fcurve.driver
    driver.type = 'SCRIPTED'
    var = driver.variables.new()
    var.name = 'a'
    var.type = 'SINGLE_PROP'
    var.targets[0].id = root
    var.targets[0].data_path = f'["{prop}"]'
    driver.expression = expr


def child_of(obj, target):
    c = obj.constraints.new('CHILD_OF')
    c.target = target
    c.set_inverse_pending = False
    c.inverse_matrix = Matrix.Identity(4)
    return c


def build_links(root):
    """The joint tree: a mount empty at the pose and a joint empty under it, per link."""
    joints = {}
    for b in rig.LINKS:
        parent = root if b['parent'] is None else joints[b['parent']]
        mount = empty(f'{b["name"]}_mount', parent, b['pos'], b['yaw'], 0.01)
        j = joints[b['name']] = empty(b['name'], mount, size=0.015)
        j['joint'] = b['joint']['type']
        j['axis'] = list(b['joint']['axis'])
        j['range'] = list(b['joint']['range'])
        j['coupling'] = f'{rig.joint_name(b["name"])} = {b["joint"]["coef"]:.6g} * {b["joint"]["prop"]}'
    return joints


def build_hand(J):
    """The page's geometry, link by link."""
    hand = J['hand']
    grip = empty('grip_frame', hand, (0, 0, GRIP_Z * MM), size=0.01)
    # the U-frame, the beam and its end caps
    for s in (-1, 1):
        part(f'strut_{"l" if s > 0 else "r"}', grip, rb('x', SPINE['x1'] - 14, BEAM['x1'], s * STRUT_Y, 0, 8, 12, 2), 'gray')
    part('crossbar', grip, rb('y', -STRUT_Y - 4, STRUT_Y + 4, SPINE['x1'] - 7, 0, 14, 16, 3), 'gray')
    part('beam', grip, rb('x', BEAM['x0'], BEAM['x1'], 0, 0, 2 * BEAM['half_y'], 2 * BEAM['half_z'], 3), 'gray')
    for s in (-1, 1):
        part(f'beam_cap_{"l" if s > 0 else "r"}', grip,
             rb('x', BEAM['x0'] - 1, BEAM['x1'] + 1, s * (BEAM['half_y'] - 4), 0, 8, 2 * BEAM['half_z'] + 2, 3), 'black')
        rod = cyl(2.2, 2.2, 0, BEAM['x1'] - BEAM['x0'] - 3, 24)
        part(f'beam_rod_{"u" if s > 0 else "d"}', grip, rod, 'steel', pos=(BEAM['x0'] + 1.5, 0, s * (BEAM['half_z'] - 2.2)))
        bpy.data.objects[f'beam_rod_{"u" if s > 0 else "d"}'].rotation_euler = (0, math.pi / 2, 0)
    # the jaws
    for side, name in ((1, 'jaw_l'), (-1, 'jaw_r')):
        jaw = J[name]
        W, H, C = JAW['half_width'], JAW['half_height'], COMB_X
        part(f'{name}_plate', jaw, slab(plate_poly(-C, C, side), -H, H), 'gray')
        part(f'{name}_liner', jaw, slab(liner_poly(-C, C, side), -H, H), 'liner')
        for i, (z0, z1) in enumerate(wing_bands(side)):
            for j, (x0, x1) in enumerate(((C, W), (-W, -C))):
                part(f'{name}_wing{i}{j}_plate', jaw, slab(plate_poly(x0, x1, side), z0, z1), 'gray')
                part(f'{name}_wing{i}{j}_liner', jaw, slab(liner_poly(x0, x1, side), z0, z1), 'liner')
        back = JAW['liner'] + JAW['plate']
        arm_y, car_y = side * (back + ARM['width'] / 2), side * (back - 1 + CARRIAGE['width'] / 2)
        part(f'{name}_arm', jaw, rb('x', ARM['x0'], ARM['x1'], arm_y, 0, ARM['width'], 2 * ARM['half_z'], 3), 'gray')
        part(f'{name}_carriage', jaw, rb('x', CARRIAGE['x0'], CARRIAGE['x1'], car_y, 0, CARRIAGE['width'], 2 * CARRIAGE['half_z'], 3.5), 'black')
        for z in (-6, 6):
            o = part(f'{name}_bolt_{"u" if z > 0 else "d"}', jaw, cyl(2.4, 2.4, 0, 1.2, 20), 'bolt', pos=(CARRIAGE['x1'] - 0.3, car_y, z))
            o.rotation_euler = (0, math.pi / 2, 0)
        for k, x in enumerate((-12, -5)):
            o = part(f'{name}_screw_{k}', jaw, cyl(2.2, 2.2, -0.6, 0.6, 16), 'bolt', pos=(x, side * (back + ARM['width'] + 0.4), 0))
            o.rotation_euler = (math.pi / 2, 0, 0)
    # the harness and the UR flange over it
    part('harness', hand, rb('z', SPINE['z0'], SPINE['z1'], FLANGE_C, 0, SPINE['x1'] - SPINE['x0'], 2 * SPINE['half_y'], 8), 'black')
    part('harness_foot', hand, rb('z', SPINE['z0'] - 2, SPINE['z0'] + 6, FLANGE_C, 0, SPINE['x1'] - SPINE['x0'] + 4, 2 * SPINE['half_y'] + 4, 9), 'gray')
    part('harness_top', hand, rb('z', SPINE['z1'] - 6, SPINE['z1'] + 2, FLANGE_C, 0, SPINE['x1'] - SPINE['x0'] + 4, 2 * SPINE['half_y'] + 4, 9), 'gray')
    for k, z in enumerate((62, 200, 330)):     # one servo window each: gripper, clamp, pipette
        part(f'led_{k}', hand, box(SPINE['x1'] - 0.2, SPINE['x1'] + 0.4, -8, 8, z, z + 6), 'led')
    stub = empty('arm_stub', hand, size=0.01)
    part('arm_stub_housing', stub, cyl(FLANGE['stub_r'], FLANGE['stub_r'], FLANGE_Z + 24, FLANGE_Z + 24 + FLANGE['stub_len'], 64), 'linkgray', pos=(FLANGE_C, 0, 0))
    part('arm_stub_ring', stub, cyl(FLANGE['stub_r'] + 1, FLANGE['stub_r'] + 1, FLANGE_Z + 24, FLANGE_Z + 24 + FLANGE['ring_h'], 64), 'urblue', pos=(FLANGE_C, 0, 0))
    part('wrist_3', hand, lathe([(0, FLANGE_Z), (FLANGE['r'] - 2, FLANGE_Z), (FLANGE['r'], FLANGE_Z + 3), (FLANGE['stub_r'], FLANGE_Z + 8),
                                 (FLANGE['stub_r'], FLANGE_Z + 24), (0, FLANGE_Z + 24)], 96), 'linkgray', pos=(FLANGE_C, 0, 0))
    part('mount_plate', hand, cyl(37.5, 37.5, FLANGE_Z - 0.5, FLANGE_Z + 0.5, 96), 'steel', pos=(FLANGE_C, 0, 0))
    # the clamp's rail
    part('clamp_rail', hand, rb('y', RAIL['y0'], RAIL['y1'], RAIL['x'], RAIL['z'], 12, 12, 3), 'gray')
    part('clamp_rail_root', hand, rb('x', SPINE['x1'] - 2, RAIL['x'] + 6, RAIL['y0'] + 10, RAIL['z'], 20, 20, 4), 'black')
    part('clamp_rail_stop', hand, rb('y', RAIL['y1'] - 2, RAIL['y1'] + 6, RAIL['x'], RAIL['z'], 16, 16, 3), 'black')
    cs = J['clamp_slide']
    part('clamp_carriage', cs, rb('y', RAIL['col_y'] - 20, RAIL['col_y'] + 20, RAIL['x'], RAIL['z'], 22, 24, 4), 'black')
    part('clamp_column', cs, rb('z', Z_IRIS + 30, RAIL['z'] - 8, RAIL['x'], RAIL['col_y'], 6, 24, 2), 'gray')
    cl = J['clamp_lift']      # the iris plane at z = 0
    px, py = RAIL['x'], RAIL['col_y']
    part('lift_carriage', cl, rb('z', 44, 92, px, py, 14, 32, 3), 'black')
    part('bridge_y', cl, rb('y', -4, py + 4, px, 66, 24, 8, 3), 'gray')
    part('bridge_x', cl, rb('x', px - 4, 0, 0, 66, 24, 8, 3), 'gray')
    part('mount_disc', cl, cyl(20, 20, 60, 64, 64), 'housing')
    part('sun_motor', cl, cyl(14, 14, 70, 104, 48), 'housing')
    part('sun_motor_cap', cl, cyl(15, 15, 102, 106, 48), 'gray')
    # the housing, turning with body_yaw
    H, hs = IRIS, J['housing']
    part('housing_front', hs, ring(H['housing_r'], H['housing_ri'], -4, H['z_cam'] - 2), 'housing')
    part('housing_shoulder', hs, ring(H['housing_r'], H['r_ring'] + 12, H['z_cam'] - 2, H['z_cam'] + 2), 'housing')
    for i in range(3):
        a, r = i * TAU / 3 + math.pi / 3, H['r_ring'] + 18
        part(f'housing_strut_{i}', hs, rb('z', H['z_cam'], H['z_top'], 0, 0, 10, 14, 2), 'housing', pos=(r * math.cos(a), r * math.sin(a), 0), yaw=a)
    part('carrier_plate', hs, ring(H['r_ring'] + 10, 6, H['z_carrier'], H['z_carrier'] + H['carrier_t']), 'housing')
    part('clutch_ring', hs, ring(H['r_ring'] + 24, H['r_ring'] + 10, 48, 52), 'gray')
    part('top_ring', hs, ring(H['r_ring'] + 24, H['r_ring'] + 10, H['z_top'] - 4, H['z_top']), 'housing')
    for i in range(3):
        a = i * TAU / 3
        part(f'planet_pin_{i}', hs, cyl(2.5, 2.5, H['z_gears'] - 2, H['z_carrier'] + 2, 16), 'steel', pos=(H['planet_r'] * math.cos(a), H['planet_r'] * math.sin(a), 0))
        part(f'planet_{i}_gear', J[f'planet_{i}'], cyl(H['r_sun'], H['r_sun'], H['z_gears'], H['z_gears'] + H['gear_t'], 24), 'housing')
    for k in range(H['n_blades']):
        phi = k * TAU / H['n_blades']
        part(f'blade_pin_{k}', hs, cyl(2, 2, -2, 18, 16), 'steel', pos=(H['r_pivot'] * math.cos(phi), H['r_pivot'] * math.sin(phi), 0))
        bl = J[f'blade_{k}']
        part(f'blade_{k}_leaf', bl, box(0, H['blade_w'], 0, H['blade_len'], 0, H['blade_t']), 'gold')
        part(f'blade_{k}_tip', bl, cyl(H['blade_w'] / 2, H['blade_w'] / 2, 0, H['blade_t'], 24), 'gold', pos=(H['blade_w'] / 2, H['blade_len'], 0))
    cam = J['cam']
    part('cam_ring', cam, ring(H['r_pivot'] + 4, H['r_pivot'] - 14, H['z_cam'], H['z_cam'] + H['cam_t']), 'gold')
    part('cam_collar', cam, ring(H['r_pivot'] - 6, H['r_ring'] + 8, H['z_cam'] + H['cam_t'], H['z_cam'] + H['cam_t'] + 3), 'gold')
    part('ring_gear', cam, ring(H['r_ring'] + 8, H['r_ring'], H['z_gears'], H['z_gears'] + H['gear_t']), 'gold')
    sun = J['sun']
    part('sun_gear', sun, cyl(H['r_sun'], H['r_sun'], H['z_gears'], H['z_gears'] + H['gear_t'], 24), 'gold')
    part('sun_shaft', sun, cyl(4, 4, H['z_gears'], 70, 16), 'steel')
    # the pipette: brackets, mast, rail, slide, swing frame, the pipette itself
    PX, PY, YY = PIVOT['x'], PIVOT['y'], YOKE_Y
    CY0, CY1 = YY + 7, YY + 19
    for k, z in enumerate((72, 346)):
        part(f'mast_bracket_{k}_y', hand, rb('y', YY - 9, -SPINE['half_y'] + 2, SPINE['x1'] - 6, z, 12, 12, 3), 'gray')
        part(f'mast_bracket_{k}_x', hand, rb('x', SPINE['x1'] - 12, PX + 16, YY - 3, z, 12, 12, 3), 'gray')
    part('mast', hand, rb('z', MAST_BOTTOM, RAIL_TOP + 5, PX, YY - 3, 32, 12, 3), 'gray')
    rail_lo = rig.base_z(B) + TIP_DIVE + CAR[0]
    part('pipette_rail', hand, rb('z', rail_lo, RAIL_TOP, PX, YY + 5, 12, 4, 1), 'housing')
    sl = J['pip_slide']       # its origin is the tip's height
    part('pipette_carriage', sl, rb('z', CAR[0], CAR[1], PX, (CY0 + CY1) / 2, 32, CY1 - CY0, 3), 'gray')
    part('pipette_lug_d', sl, rb('z', CAR[0], CAR[0] + 12, PX, (PY + CY1) / 2, 32, PY - CY1, 2), 'gray')
    part('pipette_lug_u', sl, rb('z', CAR[1] - 12, CAR[1], PX, (PY + CY1) / 2, 32, PY - CY1, 2), 'gray')
    part('swing_motor', sl, rb('x', PX + 16, PX + 46, (CY0 + CY1 - 6) / 2, CAR[1] - 17, CY1 - CY0 + 6, 34, 3), 'housing')
    web = math.atan2(-PY, -PX)
    web_len = math.hypot(PX, PY)
    part('cone_receiver', sl, box(-9, 9, -8, 8, CAR[0] + 30, CAR[0] + 50), 'housing',
         pos=(PX + 21 * math.cos(web) - 16 * math.sin(web), PY + 21 * math.sin(web) + 16 * math.cos(web), 0), yaw=web)
    sw = J['pip_swing']
    part('swing_pin', sw, cyl(5, 5, CAR[0] - 6, CAR[1] + 6, 24), 'steel')
    half_d = PIP['body_d1'] / 2
    ftop, fbot = BTN_TOP + 37, CLIPS[0] - 8
    part('swing_web', sw, rb('x', 5, web_len - half_d - 4, 0, (ftop + fbot) / 2, 8, ftop - fbot, 2), 'gray', yaw=web)
    held = empty('pipette', sw, (-PX * MM, -PY * MM, 0), size=0.01)     # the pipette's frame: tip at the origin
    for k, z in enumerate(CLIPS):
        part(f'pipette_clip_{k}', held, ring(half_d + 5, half_d + 0.5, z - 8, z + 8, 48), 'gray')
    part('plunger_actuator_arm', held, rb('z', BTN_TOP + 25, ftop, 0, half_d + 2, 12, half_d + 14, 2), 'gray')
    part('plunger_actuator', held, cyl(9, 9, BTN_TOP + 10, BTN_TOP + 46, 32), 'housing', pos=(PIP['plunger_x'], 0, 0))
    P = PIP
    part('pipette_tip', held, cyl(P['tip_r0'], P['tip_r1'], 0, P['tip_len'], 32), 'dark')
    part('pipette_shaft', held, cyl(P['tip_r1'], P['shaft_r1'], P['tip_len'], P['tip_len'] + P['shaft_len'], 32), 'blue')
    part('pipette_collar', held, cyl(P['shaft_r1'], P['collar_r1'], P['tip_len'] + P['shaft_len'], P['body_z0'], 40), 'blue')
    part('pipette_body', held, rb('z', P['body_z0'], P['body_z0'] + P['body_len'], 0, 0, P['body_w1'], P['body_d1'], 6), 'white')
    part('pipette_display', held, box(-5.5, 5.5, -P['body_d1'] / 2 - 0.6, -P['body_d1'] / 2 + 1, 148, 174), 'display')
    part('ejector_sleeve', held, cyl(P['ejector_sleeve_r'], P['ejector_sleeve_r'], P['ejector_sleeve_z0'], P['ejector_sleeve_z1'], 32), 'blue')
    part('ejector_rod', held, cyl(P['ejector_r'], P['ejector_r'], P['ejector_sleeve_z1'], P['ejector_btn_z'], 16), 'blue', pos=(P['ejector_x'], 0, 0))
    part('ejector_button', held, cyl(P['ejector_btn_r'], P['ejector_btn_r'], P['ejector_btn_z'], P['ejector_btn_z'] + P['ejector_btn_h'], 32), 'blue', pos=(P['ejector_x'] + 2, 0, 0))
    part('finger_hook', held, rb('x', -P['body_w1'] / 2 - P['hook_reach'], -P['body_w1'] / 2 + 4, 0, P['hook_z'], 16, 7, 3), 'gray')
    pl = J['plunger']
    part('plunger_rod', pl, cyl(P['plunger_r'], P['plunger_r'], P['body_z0'] + P['body_len'] - 2, BTN_TOP - P['button_h'], 24), 'white', pos=(P['plunger_x'], 0, 0))
    part('plunger_button', pl, cyl(P['button_r'], P['button_r'], BTN_TOP - P['button_h'], BTN_TOP, 32), 'blue', pos=(P['plunger_x'], 0, 0))
    part('pusher', pl, cyl(3, 3, BTN_TOP, BTN_TOP + 26, 16), 'steel', pos=(P['plunger_x'], 0, 0))
    # the check points
    sites = {}
    for name, (link, pos) in rig.SITES.items():
        sites[name] = empty(name, J[link], pos, size=0.006)
    return sites


def build_bottle(root, J):
    """The reference bottle, its liquid and the cap, carried as the page carries them."""
    bottle = part('bottle', None, lathe(bottle_profile(B)), 'bottle')
    part('liquid', bottle, lathe([(0, 2.6), (B['r'] - 2.6, 2.6), (B['r'] - 2.6, B['level']), (0, B['level'])], 48), 'liquid')
    cap = part('cap', None, lathe(cap_profile(B), 64), 'cap')
    c = B['cap_r']
    for k in range(24):
        a = k * TAU / 24
        part(f'cap_rib_{k}', cap, box(-0.5, 0.5, -0.5, 0.5, 0, B['cap_h'] - 3.5), 'cap',
             pos=((c - 0.4) * math.cos(a), (c - 0.4) * math.sin(a), 1.5), yaw=a)
    # held: in the hand frame (the origins coincide when the bottle stands on the table)
    hold = child_of(bottle, J['hand'])
    add_driver(hold, 'influence', -1, root, 'grip_aperture', f'1 if a <= {2 * rig.vertex(B["r"]) * MM + 0.3 * MM:.6g} else 0')
    neck = empty('cap_on_bottle', bottle, (0, 0, B['cap_z'] * MM), size=0.008)
    for target, expr in ((neck, '1 if a <= 1e-4 else 0'), (bpy.data.objects['cap_seat'], '1 if a > 1e-4 else 0')):
        add_driver(child_of(cap, target), 'influence', -1, root, 'housing_turns', expr)
    return bottle, cap


def add_drivers(root, J):
    for b in rig.LINKS:
        j, obj = b['joint'], J[b['name']]
        (axis,) = np.flatnonzero(j['axis'])
        sign = float(np.sign(j['axis'][axis]))
        expr = f'{sign * j["coef"]:.9g} * a'
        if j['type'] == 'slide':
            obj.lock_location = (True, True, True)
            add_driver(obj, 'location', int(axis), root, j['prop'], expr)
        else:
            obj.lock_rotation = (True, True, True)
            add_driver(obj, 'rotation_euler', int(axis), root, j['prop'], expr)


def set_state(root, state):
    for k in rig.STATE:
        root[k] = float(state[k])
    root['fill'] = float(state.get('fill', 0.0))
    root.update_tag()              # a property set from Python does not tag the drivers by itself
    for obj in bpy.data.objects:
        if obj.constraints:
            obj.update_tag()
    bpy.context.view_layer.update()


def keyframe_sequence(root, scene):
    frames = rig.keys(B)
    (t_prev, prev), (t_last, last) = frames[-2], frames[-1]
    mid = dict(prev)
    mid['grip_aperture'] = last['grip_aperture']
    frames = frames[:-1] + [((t_prev + t_last) / 2, mid), (t_last, last)]
    for t, state in frames:
        frame = 1 + round(t * FPS)
        for k in (*rig.STATE, 'fill'):
            root[k] = float(state[k])
            root.keyframe_insert(f'["{k}"]', frame=frame)
    scene.frame_start, scene.frame_end = 1, 1 + round((rig.DURATION + rig.TAIL) * FPS)
    scene.render.fps = FPS
    try:
        action = root.animation_data.action
        fcurves = getattr(action, 'fcurves', None)
        if fcurves is None or not len(fcurves):     # slotted actions (Blender >= 4.4)
            fcurves = [f for layer in action.layers for strip in layer.strips
                       for bag in strip.channelbags for f in bag.fcurves]
        for fcurve in fcurves:
            for kp in fcurve.keyframe_points:
                kp.interpolation, kp.easing = 'SINE', 'EASE_IN_OUT'
    except Exception as exc:   # noqa: BLE001 - the file is still right, only the easing differs
        print(f'could not set the easing: {exc}')
    set_state(root, frames[0][1])
    scene.frame_set(1)


# ============================== exports ==============================
def write_stl(path, triangles):
    tris = np.asarray(triangles, np.float32)
    normals = np.cross(tris[:, 1] - tris[:, 0], tris[:, 2] - tris[:, 0])
    normals /= np.maximum(np.linalg.norm(normals, axis=1, keepdims=True), 1e-12)
    record = np.dtype([('normal', '<f4', 3), ('v', '<f4', (3, 3)), ('attr', '<u2')])
    data = np.zeros(len(tris), record)
    data['normal'], data['v'] = normals, tris
    path.write_bytes(b'\0' * 80 + struct.pack('<I', len(tris)) + data.tobytes())


def link_of(obj, J):
    """The joint link a mesh object hangs from."""
    links = set(J.values())
    o = obj
    while o is not None and o not in links:
        o = o.parent
    return o


def export_meshes(J, extra):
    """One STL per (link, material), in the link's joint frame, at the rest pose (all joints 0).

    Returns {link name: [(mesh name, material)]}; `extra` are free objects exported in their own frame.
    """
    MESH_DIR.mkdir(parents=True, exist_ok=True)
    for old in MESH_DIR.glob('*.stl'):
        old.unlink()
    bpy.context.view_layer.update()
    groups = {}
    for obj in bpy.data.objects:
        if obj.type != 'MESH':
            continue
        link = link_of(obj, J)
        if link is None:
            top = obj
            while top.parent is not None:
                top = top.parent
            if top not in extra:
                continue
            link = top
        groups.setdefault((link.name, obj.data.materials[0].name), []).append(obj)
    out = {}
    for (link_name, mat), objs in sorted(groups.items()):
        link = bpy.data.objects[link_name]
        tris = []
        for obj in objs:
            M = link.matrix_world.inverted() @ obj.matrix_world
            me = obj.data
            me.calc_loop_triangles()
            co = np.array([M @ v.co for v in me.vertices], np.float64)
            idx = np.array([t.vertices for t in me.loop_triangles], np.int64)
            tris.append(co[idx])
        name = f'{link_name}__{mat}'
        write_stl(MESH_DIR / f'{name}.stl', np.concatenate(tris))
        out.setdefault(link_name, []).append((name, mat))
    return out


def num(x):
    return f'{x:.6g}'


def vec(v):
    return ' '.join(num(float(x)) for x in v)


def rgba(mat):
    return vec((*MATERIALS[mat][0], ALPHA.get(mat, 1.0)))


def collision_geoms(link):
    """(kind, pos (m), yaw, size) primitives per link, MuJoCo style sizes (half sizes for boxes)."""
    if link in ('jaw_l', 'jaw_r'):
        return [('box', pos, yaw, half, 'pad') for pos, yaw, half in pad_boxes(1 if link == 'jaw_l' else -1)]
    if link.startswith('blade_'):
        return [('box', (IRIS['blade_w'] / 2 * MM, IRIS['blade_len'] / 2 * MM, IRIS['blade_t'] / 2 * MM), 0.0,
                 (IRIS['blade_w'] / 2 * MM, IRIS['blade_len'] / 2 * MM, IRIS['blade_t'] / 2 * MM), 'blade')]
    if link == 'pip_swing':
        # the tip and the shaft, as one cylinder up to the collar, in the held frame
        return [('cylinder', (-PIVOT['x'] * MM, -PIVOT['y'] * MM, (PIP['tip_len'] + PIP['shaft_len']) / 2 * MM), 0.0,
                 (PIP['shaft_r1'] * MM, (PIP['tip_len'] + PIP['shaft_len']) / 2 * MM), 'tip')]
    return []


def mjcf_body(b, children, meshes, indent):
    j = b['joint']
    attrs = f'name="{b["name"]}" pos="{vec(b["pos"])}"'
    if b['yaw']:
        attrs += f' quat="{vec(rig.quat_z(b["yaw"]))}"'
    out = f'{indent}<body {attrs}>\n'
    m = b['mass']
    out += f'{indent}  <inertial pos="0 0 0" mass="{num(m)}" diaginertia="{vec([max(1e-6, m * 2e-4)] * 3)}"/>\n'
    follower = b['name'] in rig.FOLLOWS      # light, so the leader's actuator does not fight the reflected inertia
    armature, damping = (1e-5, 0.01) if follower else (0.001, 0.5 if j['type'] == 'slide' else 0.02)
    out += (f'{indent}  <joint name="{rig.joint_name(b["name"])}" type="{j["type"]}" axis="{vec(j["axis"])}" '
            f'range="{vec(j["range"])}" armature="{armature}" damping="{damping}"/>\n')
    for name, mat in meshes.get(b['name'], []):
        out += f'{indent}  <geom name="{name}" type="mesh" mesh="{name}" material="{mat}" contype="0" conaffinity="0" group="2" mass="0"/>\n'
    for k, (kind, pos, yaw, size, who) in enumerate(collision_geoms(b['name'])):
        ct, ca = COLLIDE[who]
        quat = '' if not yaw else f' quat="{vec(rig.quat_z(yaw))}"'
        out += (f'{indent}  <geom name="{b["name"]}_col_{k}" type="{kind}" pos="{vec(pos)}"{quat} size="{vec(size)}" '
                f'contype="{ct}" conaffinity="{ca}" group="3" rgba="0.8 0.3 0.3 0.3" mass="0"/>\n')
    for name, (link, pos) in rig.SITES.items():
        if link == b['name']:
            out += f'{indent}  <site name="{name}" pos="{vec(pos)}" size="0.003" rgba="0.9 0.3 0.1 0.5" group="4"/>\n'
    for c in children.get(b['name'], []):
        out += mjcf_body(c, children, meshes, indent + '  ')
    return out + f'{indent}</body>\n'


def write_hand_mjcf(meshes):
    children = {}
    for b in rig.LINKS:
        children.setdefault(b['parent'], []).append(b)
    used = sorted({mat for b in rig.LINKS for _, mat in meshes.get(b['name'], [])})
    materials = ''.join(f'    <material name="{m}" rgba="{rgba(m)}" specular="0.5" shininess="0.25"/>\n' for m in used)
    mesh_assets = ''.join(f'    <mesh name="{name}" file="{name}.stl"/>\n'
                          for link in rig.LINKS for name, _ in meshes.get(link['name'], []))
    equalities = ''.join(f'    <joint name="eq_{f}" joint1="{f}" joint2="{leader}" polycoef="0 {num(k)} 0 0 0"/>\n'
                         for f, (leader, k) in rig.FOLLOWS.items())
    actuators = ''
    for b in rig.LINKS:
        name = rig.joint_name(b['name'])
        if name not in GAINS:
            continue
        kp, kv, force = GAINS[name]
        actuators += (f'    <position name="{name}" joint="{name}" kp="{kp}" kv="{kv}" '
                      f'ctrlrange="{vec(b["joint"]["range"])}" forcerange="{vec((-force, force))}"/>\n')
    HAND_XML.write_text(f'''<mujoco model="vertical_hand">
  <!-- {HEADER} -->
  <!-- The vertical uncap-and-pipette hand of gripper-design/vertical_hand.html: the
       parabolic-cradle gripper on a beam under a harness that hangs from the UR flange,
       the iris clamp on a Y rail with its own lift column, the micropipette on a swing
       frame on a vertical slide. Hand frame: +X arm to bottle, Z up, the bottle's axis
       at the origin, the reference bottle's base at z = 0 when lift_z = 0.
       Nine actuated joints; the second jaw, the cam ring's planets, the six blades and
       the sun follow through equalities. See vertical_hand_rig.py. -->
  <compiler angle="radian" meshdir="meshes" autolimits="true"/>
  <default>
    <equality solref="0.005 1"/>   <!-- the followers stay within a few milliradians of their leader -->
  </default>

  <asset>
{materials}{mesh_assets}  </asset>

  <worldbody>
    <body name="vertical_hand">
{''.join(mjcf_body(c, children, meshes, '      ') for c in children[None])}    </body>
  </worldbody>

  <equality>
{equalities}  </equality>

  <actuator>
{actuators}  </actuator>
</mujoco>
''')


def write_scene_mjcf(meshes, keyframe=''):
    bottle_meshes = ''.join(f'    <mesh name="{name}" file="{name}.stl"/>\n' for link in ('bottle', 'cap') for name, _ in meshes.get(link, []))
    bottle_geoms = ''.join(f'      <geom name="{name}" type="mesh" mesh="{name}" material="{mat}" contype="0" conaffinity="0" group="2" mass="0"/>\n'
                           for name, mat in meshes.get('bottle', []))
    cap_geoms = ''.join(f'      <geom name="{name}" type="mesh" mesh="{name}" material="{mat}" contype="0" conaffinity="0" group="2" mass="0"/>\n'
                        for name, mat in meshes.get('cap', []))
    mats = ''.join(f'    <material name="{m}" rgba="{rgba(m)}" specular="0.3" shininess="0.2"/>\n' for m in ('bottle', 'liquid', 'cap'))
    cc, fc = COLLIDE['cap'], COLLIDE['floor']
    SCENE_XML.write_text(f'''<mujoco model="vertical_hand_scene">
  <!-- {HEADER} -->
  <!-- The vertical hand over a floor, the reference 60 ml bottle standing under it and its
       PP25 cap on the neck, both free bodies. The bottle and the cap change hands by the
       page's rule, through the three welds (vertical_hand_play.py engages each at the
       bodies' relative pose of the moment): the bottle rides the hand while the jaws are
       closed on it, the cap rides the bottle until the housing turns and the clamp after.
       Keyframe `home` is the sequence's start. -->
  <compiler angle="radian" meshdir="meshes" autolimits="true"/>
  <option timestep="0.002" integrator="implicitfast"/>

  <asset>
    <model name="hand" file="vertical_hand.xml"/>
    <texture type="2d" name="grid" builtin="checker" rgb1="0.86 0.87 0.89" rgb2="0.8 0.81 0.83" width="256" height="256"/>
    <material name="floor" texture="grid" texrepeat="8 8" reflectance="0.05"/>
{mats}{bottle_meshes}  </asset>

  <worldbody>
    <light pos="0.5 -0.5 1.5" dir="-0.3 0.3 -1" diffuse="0.8 0.8 0.8"/>
    <light pos="-0.6 0.4 1.2" dir="0.4 -0.3 -1" diffuse="0.4 0.4 0.45"/>
    <geom name="floor" type="plane" size="1 1 0.05" material="floor" contype="{fc[0]}" conaffinity="{fc[1]}"/>
    <attach model="hand" body="vertical_hand" prefix=""/>
    <body name="bottle" pos="0 0 0">
      <freejoint name="bottle"/>
      <inertial pos="0 0 {num(B['h'] / 2 * MM)}" mass="0.058" diaginertia="5e-5 5e-5 1.5e-5"/>
{bottle_geoms}{bottle_collision()}      <site name="neck" pos="0 0 {num(B['cap_z'] * MM)}" size="0.003" rgba="0.9 0.3 0.1 0.5" group="4"/>
    </body>
    <body name="cap" pos="0 0 {num(B['cap_z'] * MM)}">
      <freejoint name="cap"/>
      <inertial pos="0 0 {num(B['cap_h'] / 2 * MM)}" mass="0.0025" diaginertia="3e-7 3e-7 3e-7"/>
{cap_geoms}      <geom name="cap_col" type="cylinder" pos="0 0 {num(B['cap_h'] / 2 * MM)}" size="{num(B['cap_r'] * MM)} {num(B['cap_h'] / 2 * MM)}"
            contype="{cc[0]}" conaffinity="{cc[1]}" group="3" rgba="0.8 0.3 0.3 0.3" mass="0"/>
    </body>
  </worldbody>

  <equality>
    <weld name="hold_bottle" body1="hand" body2="bottle" active="false"/>
    <weld name="cap_on_bottle" body1="bottle" body2="cap" active="true"/>
    <weld name="cap_in_clamp" body1="housing" body2="cap" active="false"/>
  </equality>
{keyframe}</mujoco>
''')


def bottle_collision():
    """The bottle as a hollow shell MuJoCo can collide with: a floor disc, a ring of wall boxes up the
    straight body and a ring of neck boxes around the bore; the shoulder is left open, nothing reaches it."""
    ct, ca = COLLIDE['bottle']
    common = f'contype="{ct}" conaffinity="{ca}" group="3" rgba="0.8 0.3 0.3 0.3" mass="0"'
    out = f'      <geom name="bottle_floor" type="cylinder" pos="0 0 {num(1.25 * MM)}" size="{num(B["r"] * MM)} {num(1.25 * MM)}" {common}/>\n'
    for kind, n, r_out, thick, z0, z1 in (('wall', 24, B['r'], 2.0, 2.5, B['shoulder']), ('neck', 12, B['neck_r'], 2.0, B['neck'], B['h'])):
        half_t, rc, half_w, hz, zc = thick / 2, r_out - thick / 2, r_out * math.tan(math.pi / n), (z1 - z0) / 2, (z0 + z1) / 2
        for k in range(n):
            a = k * TAU / n
            out += (f'      <geom name="bottle_{kind}_{k}" type="box" pos="{vec((rc * math.cos(a) * MM, rc * math.sin(a) * MM, zc * MM))}" '
                    f'quat="{vec(rig.quat_z(a))}" size="{vec((half_t * MM, half_w * MM, hz * MM))}" {common}/>\n')
    return out


def home_keyframe(model):
    data = mujoco.MjData(model)
    for name, q in rig.joints(rig.start(B)).items():
        data.qpos[model.joint(name).qposadr[0]] = q
    data.qpos[model.joint('bottle').qposadr[0]:][:7] = (0, 0, 0, 1, 0, 0, 0)
    data.qpos[model.joint('cap').qposadr[0]:][:7] = (0, 0, B['cap_z'] * MM, 1, 0, 0, 0)
    ctrl = [rig.joints(rig.start(B))[model.actuator(a).name] for a in range(model.nu)]
    return (f'\n  <keyframe>\n    <key name="home" qpos="{vec(data.qpos)}" ctrl="{vec(ctrl)}"/>\n  </keyframe>\n')


def urdf_origin(pos, yaw=0.0):
    return f'<origin xyz="{vec(pos)}" rpy="0 0 {num(yaw)}"/>'


def write_urdf(meshes):
    out = f'<?xml version="1.0"?>\n<!-- {HEADER} -->\n<!-- The vertical uncap-and-pipette hand for Isaac Lab\'s URDF importer: the tree of\n     vertical_hand.xml, followers as mimic joints. Root link vertical_hand; fix it to the world. -->\n<robot name="vertical_hand">\n'
    for m in sorted({mat for b in rig.LINKS for _, mat in meshes.get(b['name'], [])}):
        out += f'  <material name="{m}"><color rgba="{rgba(m)}"/></material>\n'
    out += '  <link name="vertical_hand"/>\n'
    for b in rig.LINKS:
        m = b['mass']
        out += f'  <link name="{b["name"]}">\n'
        out += (f'    <inertial><origin xyz="0 0 0"/><mass value="{num(m)}"/>'
                f'<inertia ixx="{num(max(1e-6, m * 2e-4))}" iyy="{num(max(1e-6, m * 2e-4))}" izz="{num(max(1e-6, m * 2e-4))}" ixy="0" ixz="0" iyz="0"/></inertial>\n')
        for name, mat in meshes.get(b['name'], []):
            out += (f'    <visual><origin xyz="0 0 0"/><geometry><mesh filename="meshes/{name}.stl"/></geometry>'
                    f'<material name="{mat}"/></visual>\n')
        for kind, pos, yaw, size, _ in collision_geoms(b['name']):
            if kind == 'box':
                shape = f'<box size="{vec([2 * s for s in size])}"/>'
            else:
                shape = f'<cylinder radius="{num(size[0])}" length="{num(2 * size[1])}"/>'
            out += f'    <collision>{urdf_origin(pos, yaw)}<geometry>{shape}</geometry></collision>\n'
        out += '  </link>\n'
    for b in rig.LINKS:
        j, name = b['joint'], rig.joint_name(b['name'])
        parent = 'vertical_hand' if b['parent'] is None else b['parent']
        typ = 'prismatic' if j['type'] == 'slide' else 'revolute'
        force = GAINS.get(name, (0, 0, 20.0))[2]
        out += f'  <joint name="{name}" type="{typ}">\n'
        out += f'    <parent link="{parent}"/><child link="{b["name"]}"/>\n'
        out += f'    {urdf_origin(b["pos"], b["yaw"])}\n    <axis xyz="{vec(j["axis"])}"/>\n'
        out += f'    <limit lower="{num(j["range"][0])}" upper="{num(j["range"][1])}" effort="{num(force)}" velocity="{2.0 if typ == "prismatic" else 10.0}"/>\n'
        if b['name'] in rig.FOLLOWS:
            leader, k = rig.FOLLOWS[b['name']]
            out += f'    <mimic joint="{leader}" multiplier="{num(k)}" offset="0"/>\n'
        out += '  </joint>\n'
    out += '</robot>\n'
    URDF.write_text(out)


# ============================== checks ==============================
def check_states():
    for n in CHECK_STEPS:
        state, _ = rig.state_at(rig.step_end(n) - 1e-6)
        yield n, state, rig.fk(state)


def check_blender(root, sites, bottle, cap):
    worst = 0.0
    for n, state, want in check_states():
        set_state(root, state)
        for name, obj in sites.items():
            err = float((Vector(want[name]) - obj.matrix_world.translation).length)
            worst = max(worst, err)
            if err > 1e-6:
                print(f'  blend, step {n}: {name} off by {err * 1000:.4f} mm')
        # the bottle and the cap, where the page's rule puts them
        held, in_clamp = rig.attachments(state, B)
        bottle_want = np.array([0, 0, state['lift_z'] if held else 0.0])
        cap_want = want['cap_seat'] if in_clamp else bottle_want + [0, 0, B['cap_z'] * MM]
        for name, obj, exp in (('bottle', bottle, bottle_want), ('cap', cap, cap_want)):
            err = float((Vector(exp) - obj.matrix_world.translation).length)
            worst = max(worst, err)
            if err > 1e-6:
                print(f'  blend, step {n}: {name} off by {err * 1000:.4f} mm (held {held}, in clamp {in_clamp})')
    print(f'.blend against fk: worst {worst * 1e6:.3f} um over steps {CHECK_STEPS}')
    if worst > 1e-6:
        raise RuntimeError('the .blend disagrees with vertical_hand_rig.fk')


def check_mjcf(path):
    model = mujoco.MjModel.from_xml_path(str(path))
    data = mujoco.MjData(model)
    worst = 0.0
    for n, state, want in check_states():
        for name, q in rig.joints(state).items():
            data.qpos[model.joint(name).qposadr[0]] = q
        mujoco.mj_kinematics(model, data)
        for name in rig.SITES:
            err = float(np.linalg.norm(data.site_xpos[model.site(name).id] - want[name]))
            worst = max(worst, err)
            if err > 1e-6:
                print(f'  mjcf, step {n}: {name} off by {err * 1000:.4f} mm')
    print(f'{path.name} against fk: worst {worst * 1e6:.3f} um; {model.nbody} bodies, {model.njnt} joints, {model.nu} actuators, {model.neq} equalities')
    if worst > 1e-6:
        raise RuntimeError(f'{path.name} disagrees with vertical_hand_rig.fk')


def check_urdf():
    model = mujoco.MjModel.from_xml_path(str(URDF))
    data = mujoco.MjData(model)
    worst = 0.0
    for n, state, want in check_states():
        for name, q in rig.joints(state).items():
            data.qpos[model.joint(name).qposadr[0]] = q
        mujoco.mj_kinematics(model, data)
        for name, (link, pos) in rig.SITES.items():
            b = model.body(link).id
            got = data.xpos[b] + data.xmat[b].reshape(3, 3) @ np.array(pos)
            err = float(np.linalg.norm(got - want[name]))
            worst = max(worst, err)
            if err > 1e-6:
                print(f'  urdf, step {n}: {name} off by {err * 1000:.4f} mm')
    print(f'{URDF.name} (loaded in MuJoCo) against fk: worst {worst * 1e6:.3f} um; {model.njnt} joints, {model.neq} mimic equalities')
    if worst > 1e-6:
        raise RuntimeError('the URDF disagrees with vertical_hand_rig.fk')
    if model.neq != len(rig.FOLLOWS):
        print(f'  note: MuJoCo turned {model.neq} of the {len(rig.FOLLOWS)} <mimic> tags into equalities')


# ============================== main ==============================
def main() -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = 'METRIC'
    scene.unit_settings.length_unit = 'MILLIMETERS'

    root = empty('vertical_hand', size=0.03)
    for k, (default, lo, hi, subtype, desc) in rig.PROPS.items():
        root[k] = float(default)
        ui = root.id_properties_ui(k)
        ui.update(min=lo, max=hi, soft_min=lo, soft_max=hi, description=desc, subtype=subtype)
    root['fill'] = 0.0
    root.id_properties_ui('fill').update(min=0.0, max=1.0, description='How full the tip is (render only)')
    root['steps'] = [name for name, _, _ in rig.STEPS]

    J = build_links(root)
    sites = build_hand(J)
    bottle, cap = build_bottle(root, J)

    # meshes and the simulator files come from the rest pose, before the drivers move anything
    meshes = export_meshes(J, {bottle, cap})
    n_tris = sum(1 for _ in MESH_DIR.glob('*.stl'))
    print(f'wrote {n_tris} STL meshes to {MESH_DIR.relative_to(SIM)}')
    write_hand_mjcf(meshes)
    write_scene_mjcf(meshes)
    write_scene_mjcf(meshes, home_keyframe(mujoco.MjModel.from_xml_path(str(SCENE_XML))))
    write_urdf(meshes)
    check_mjcf(HAND_XML)
    check_mjcf(SCENE_XML)
    check_urdf()

    add_drivers(root, J)
    check_blender(root, sites, bottle, cap)
    keyframe_sequence(root, scene)

    # a light, a world and a camera for renders
    sun = bpy.data.objects.new('sun', bpy.data.lights.new('sun', 'SUN'))
    sun.data.energy = 4
    sun.rotation_euler = (0.6, 0.3, 0.8)
    scene.collection.objects.link(sun)
    cam = bpy.data.objects.new('camera', bpy.data.cameras.new('camera'))
    cam.location, cam.rotation_euler = (0.75, -0.7, 0.55), (1.25, 0, 0.8)
    scene.collection.objects.link(cam)
    scene.camera = cam
    world = bpy.data.worlds.new('world')
    world.color = (0.35, 0.35, 0.38)
    scene.world = world

    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND), check_existing=False)
    BLEND.with_suffix('.blend1').unlink(missing_ok=True)
    glb = BLEND.with_suffix('.glb')
    bpy.ops.export_scene.gltf(filepath=str(glb), export_format='GLB', export_yup=True, export_apply=True,
                              export_animations=True, export_animation_mode='SCENE', export_extras=True)
    usd = BLEND.with_suffix('.usdc')
    try:
        bpy.ops.wm.usd_export(filepath=str(usd), export_animation=True, export_materials=True, root_prim_path='/vertical_hand')
    except Exception as exc:   # noqa: BLE001
        print(f'USD export failed: {exc}')
    for f in (BLEND, glb, usd, HAND_XML, SCENE_XML, URDF):
        if f.exists():
            print(f'wrote {f.relative_to(SIM)} ({f.stat().st_size / 1e6:.2f} MB)')

    # It has to come back with its properties.
    bpy.ops.wm.open_mainfile(filepath=str(BLEND))
    root = bpy.data.objects['vertical_hand']
    missing = [k for k in rig.PROPS if k not in root]
    if missing:
        raise RuntimeError(f'properties lost on save: {missing}')
    print(f'{BLEND.name} reopens with {len(rig.PROPS)} properties, {bpy.context.scene.frame_end} frames')


if __name__ == '__main__':
    main()
