#!/usr/bin/env python3
"""Generate the beaker the pipette dispenses into.

Run from simulation/: python scripts/generate_beaker.py.
generate_rail_scene.py calls it and stands the result on the bench.

The lab room already carries a beaker mesh --- 100 mm tall, 76 mm across, open
at the top --- so this only wraps it: the mesh for looks, a squat cylinder for
collision so it stands and can be knocked over, and a liquid column the
pipetting code resizes.

Its collision is a plain cylinder rather than the mesh, because MuJoCo collides
a mesh as its convex hull and a beaker's hull is a solid slug either way. What
goes in the beaker is bookkeeping, not geometry.
"""
from pathlib import Path

SIM = Path(__file__).resolve().parents[1]
OUT = SIM / 'assets/beaker/beaker.xml'
HEADER = '<!-- Generated by scripts/generate_beaker.py; do not edit by hand. -->\n'

RADIUS = 0.038          # outside, from the mesh
WALL = 0.002
HEIGHT = 0.100
FLOOR = 0.003
MASS = 0.085            # an empty 150 ml borosilicate beaker


def main() -> None:
    inner = RADIUS - WALL
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}<mujoco model="beaker">
  <asset>
    <mesh name="beaker" file="../lab_room/meshes/beaker.obj" inertia="shell"/>
    <material name="glass_clear" rgba="0.88 0.94 0.97 0.30" specular="0.9" shininess="0.95"/>
    <material name="contents" rgba="0.86 0.62 0.18 0.55"/>
  </asset>
  <worldbody>
    <body name="beaker">
      <inertial pos="0 0 {HEIGHT * 0.35:.4f}" mass="{MASS}"
                diaginertia="8e-5 8e-5 6e-5"/>
      <geom name="glass" type="mesh" mesh="beaker" material="glass_clear"
            contype="0" conaffinity="0" mass="0"/>
      <geom name="shell" type="cylinder" pos="0 0 {HEIGHT / 2:.4f}"
            size="{RADIUS:.4f} {HEIGHT / 2:.4f}" rgba="0 0 0 0" mass="0"/>
      <geom name="liquid" type="cylinder" pos="0 0 {FLOOR:.4f}"
            size="{inner:.4f} 0.00001" material="contents"
            contype="0" conaffinity="0" mass="0"/>
      <site name="mouth" pos="0 0 {HEIGHT:.4f}" type="cylinder"
            size="{inner:.4f} 0.001" rgba="0.2 0.7 0.9 0.25" group="4"/>
    </body>
  </worldbody>
</mujoco>
'''
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(xml)
    capacity = 3.14159 * inner**2 * (HEIGHT - FLOOR) * 1e6
    print(f'wrote {OUT.relative_to(SIM)}  (holds {capacity:.0f} ml to the rim)')


if __name__ == '__main__':
    main()
