#!/usr/bin/env python3
"""Cut a balance down so the arm can put a vessel on the pan and take it back.

Run from simulation/: python scripts/generate_open_balance.py.
generate_rail_scene.py swaps one of the scene's balances for the result.

The converted balance is a closed draft shield 311 mm tall with a single box
for collision --- no pan, no opening, so nothing can be stood on it and nothing
can be dropped into it. This trims every mesh above `CUT`, leaving an
open-topped enclosure, and replaces the collision box with the three surfaces
that matter: the housing, the weighing pan, and the shield walls, so the arm
still cannot sweep through them.

Measured off the original parts: the chamber floor is at 58 mm, the pan at
77 mm, and the shield runs from 65 mm to 306 mm.

How much comes off is set by the tool, not by taste. The first cut left the
draft shield standing to 200 mm, which is fine for a pipette --- it goes in from
above and is thinner than the chamber. The cage hand does not: it is 232 mm
across where the shield's opening is 200, so it cannot enter the chamber at any
height, and the beaker's rim at 177 mm sits below the shield's top. The hand
could dose into the beaker and never take it out again. Cutting to just over the
pan leaves the shield as a lip the hand reaches over instead of a wall it has to
fit through.
"""
from pathlib import Path

import numpy as np

SIM = Path(__file__).resolve().parents[1]
SOURCE = SIM / 'assets/balance'
OUT = SIM / 'assets/balance_open'
HEADER = '<!-- Generated by scripts/generate_open_balance.py; do not edit by hand. -->\n'

CUT = 0.095         # everything above this comes off, in the balance's frame
PAN_TOP = 0.077     # top of the weighing pan
PAN = (-0.005, 0.031)   # pan centre in x and y
CHAMBER = 0.058     # floor of the weighing chamber
SHIELD_X = 0.100    # inside half-width of the shield
SHIELD_Y = (-0.059, 0.115)

# The display. part_04 is the fixed "0.0000", extruded geometry rather than a
# texture --- there is not a single texture in this model --- so the only way
# to make the number change is to throw those digits away and build segments
# that can be switched on and off. Plane fitted to part_04's own vertices.
DIGITS_PART = 'part_04'
DIGITS_CENTRE = (0.00219, -0.10257, 0.03895)
# Flipped from the plane fit, which came out along -X: laid out that way the
# digits read right to left and each glyph is mirrored.
DIGITS_WIDTH_AXIS = (1.0, 0.0032, 0.0014)
DIGITS_HEIGHT_AXIS = (-0.0035, 0.9195, 0.3931)
CELL = 0.0118       # width of one digit cell
DIGIT = (0.0072, 0.0116)    # segment span across and up
SEGMENT = 0.0013    # segment thickness
PLACES = 4          # decimals the balance reads
ON = '0.09 0.11 0.13 1'
OFF = '0.55 0.62 0.68 0.10'

# Which segments each numeral lights, in the usual a-g order.
NUMERALS = {
    '0': 'abcdef', '1': 'bc', '2': 'abdeg', '3': 'abcdg', '4': 'bcfg',
    '5': 'acdfg', '6': 'acdefg', '7': 'abc', '8': 'abcdefg', '9': 'abcdfg',
    ' ': '',
}


def trim(path: Path, cut: float) -> tuple[Path, bool]:
    """Copy an .obj, dropping every face that reaches above `cut`.

    Args:
        path: Source mesh.
        cut: Height above which geometry is removed.

    Returns:
        The written path, and whether anything survived.
    """
    vertices, faces, other = [], [], []
    for line in path.read_text().splitlines():
        if line.startswith('v '):
            vertices.append([float(v) for v in line.split()[1:4]])
        elif line.startswith('f '):
            faces.append(line)
        elif not line.startswith(('vn ', 'vt ')):
            other.append(line)

    points = np.array(vertices) if vertices else np.zeros((0, 3))
    keep = points[:, 2] <= cut if len(points) else np.zeros(0, dtype=bool)
    # Only the vertices the surviving faces use, renumbered. Leaving the
    # orphans in keeps the mesh's bounding box at its old height, which is
    # exactly what this is trying to lower.
    surviving, remap, out_faces = [], {}, []
    for face in faces:
        idx = [int(token.split('/')[0]) - 1 for token in face.split()[1:]]
        if not all(0 <= i < len(keep) and keep[i] for i in idx):
            continue
        for i in idx:
            if i not in remap:
                remap[i] = len(surviving)
                surviving.append(points[i])
        out_faces.append('f ' + ' '.join(str(remap[i] + 1) for i in idx))

    OUT.mkdir(parents=True, exist_ok=True)
    target = OUT / path.name
    body = '\n'.join(f'v {x:.6f} {y:.6f} {z:.6f}' for x, y, z in surviving)
    target.write_text('\n'.join(other) + '\n' + body + '\n'
                      + '\n'.join(out_faces) + '\n')
    return target, bool(out_faces)


def display() -> str:
    """Seven-segment digits laid into the plane of the balance's own display.

    Each segment is a thin box whose local axes are the display's width, height
    and normal, so the whole thing sits flat on the sloping panel. They are
    emitted lit; `pipetting.show_mass` turns them off again.

    Returns:
        MJCF geom elements, as text.
    """
    centre = np.array(DIGITS_CENTRE)
    across = np.array(DIGITS_WIDTH_AXIS)
    across /= np.linalg.norm(across)
    up = np.array(DIGITS_HEIGHT_AXIS)
    up /= np.linalg.norm(up)
    wide, tall = DIGIT
    axes = ' '.join(f'{v:.4f}' for v in (*across, *up))

    def box(name, u, v, half_u, half_v):
        pos = centre + across * u + up * v
        return (f'      <geom name="{name}" type="box" '
                f'pos="{pos[0]:.5f} {pos[1]:.5f} {pos[2]:.5f}"\n'
                f'            size="{half_u:.5f} {half_v:.5f} 0.0004" '
                f'xyaxes="{axes}"\n'
                f'            rgba="{ON}" contype="0" conaffinity="0" '
                f'group="1"/>')

    out = []
    # One digit, the decimal point, then the decimals; laid out right to left
    # from the right-hand edge of the original digit block.
    slots = [(0, 0.0)] + [(i + 1, 0.0) for i in range(PLACES)]
    first = -(len(slots) - 1) / 2 * CELL
    for index, _ in slots:
        u0 = first + index * CELL
        half, top = wide / 2, tall / 2
        for seg, (u, v, hu, hv) in {
                'a': (u0, top, half, SEGMENT / 2),
                'g': (u0, 0.0, half, SEGMENT / 2),
                'd': (u0, -top, half, SEGMENT / 2),
                'f': (u0 - half, top / 2, SEGMENT / 2, tall / 4),
                'b': (u0 + half, top / 2, SEGMENT / 2, tall / 4),
                'e': (u0 - half, -top / 2, SEGMENT / 2, tall / 4),
                'c': (u0 + half, -top / 2, SEGMENT / 2, tall / 4),
        }.items():
            out.append(box(f'seg_{index}_{seg}', u, v, hu, hv))
    out.append(box('point', first + 0.5 * CELL, -tall / 2,
                   SEGMENT * 0.8, SEGMENT * 0.8))
    return '\n'.join(out)


def main() -> None:
    parts = sorted(SOURCE.glob('part_*.obj'))
    kept = []
    for part in parts:
        # The fixed digits go; segments that can be switched replace them.
        alive = part.stem != DIGITS_PART and trim(part, CUT)[1]
        kept.append((part.stem, alive))
    print(f'trimmed {len(parts)} parts at {CUT * 1000:.0f} mm; '
          f'{sum(a for _, a in kept)} still have geometry')

    source = (SOURCE / 'balance.xml').read_text()
    meshes = '\n'.join(
        f'    <mesh name="{stem}" file="{stem}.obj" inertia="shell"/>'
        for stem, alive in kept if alive)
    visuals = '\n'.join(
        f'      <geom type="mesh" mesh="{stem}" rgba="{rgba}" '
        f'contype="0" conaffinity="0" density="0" group="1"/>'
        for (stem, alive), rgba in zip(kept, [
            '0.420 0.431 0.482 1', '0.863 0.863 0.863 1', '0.392 0.584 0.929 1',
            '0.255 0.412 0.882 1', '0.227 0.227 0.227 1', '0.700 0.700 0.700 0.48',
            '0.667 0.667 0.667 1', '1.000 0.600 0.196 1', '0.882 0.882 0.784 1',
            '1.000 1.000 1.000 1', '0.757 0.757 0.757 1']) if alive)
    assert 'balance_collision' in source     # the file we measured is still there

    walls = []
    for name, pos, size in (
            ('shield_left', (-SHIELD_X, sum(SHIELD_Y) / 2, (CHAMBER + CUT) / 2),
             (0.003, (SHIELD_Y[1] - SHIELD_Y[0]) / 2, (CUT - CHAMBER) / 2)),
            ('shield_right', (SHIELD_X, sum(SHIELD_Y) / 2, (CHAMBER + CUT) / 2),
             (0.003, (SHIELD_Y[1] - SHIELD_Y[0]) / 2, (CUT - CHAMBER) / 2)),
            ('shield_back', (0, SHIELD_Y[1], (CHAMBER + CUT) / 2),
             (SHIELD_X, 0.003, (CUT - CHAMBER) / 2)),
            ('shield_front', (0, SHIELD_Y[0], (CHAMBER + CUT) / 2),
             (SHIELD_X, 0.003, (CUT - CHAMBER) / 2))):
        walls.append(f'      <geom name="{name}" type="box" '
                     f'pos="{pos[0]:.4f} {pos[1]:.4f} {pos[2]:.4f}"\n'
                     f'            size="{size[0]:.4f} {size[1]:.4f} {size[2]:.4f}" '
                     f'rgba="0 0 0 0" mass="0" group="3"/>')

    xml = f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}<mujoco model="balance_open">
  <asset>
{meshes}
  </asset>
  <worldbody>
    <body name="balance">
{visuals}
      <geom name="housing" type="box" pos="0 0 {CHAMBER / 2:.4f}"
            size="0.1050 0.1497 {CHAMBER / 2:.4f}" mass="6" group="3"
            rgba="0 0 0 0"/>
      <geom name="pan" type="box" pos="{PAN[0]:.4f} {PAN[1]:.4f} {PAN_TOP - 0.005:.4f}"
            size="0.0430 0.0430 0.0050" mass="0.05" group="3"
            rgba="0.75 0.76 0.78 1"/>
{chr(10).join(walls)}
{display()}
      <site name="pan" pos="{PAN[0]:.4f} {PAN[1]:.4f} {PAN_TOP:.4f}"
            size="0.04 0.001" type="cylinder" rgba="0.2 0.7 0.9 0.2" group="4"/>
    </body>
  </worldbody>
</mujoco>
'''
    (OUT / 'balance_open.xml').write_text(xml)
    print(f'wrote {(OUT / "balance_open.xml").relative_to(SIM)}')
    print(f'pan at {PAN_TOP * 1000:.0f} mm, shield now open above '
          f'{CUT * 1000:.0f} mm (was closed at 306 mm)')
    print(f'display: {PLACES + 1} seven-segment digits replacing the moulded '
          f'"0.0000"')


if __name__ == '__main__':
    main()
